# Load ggplot2
.load_ggplot2 <- function() {
  if (!requireNamespace("ggplot2", quietly = TRUE)) {
    stop(paste("This function should not be called directly,",
               "and ggplot2 is needed to work.",
               "Please install it."),
         call. = FALSE)
  }
}

#' Convert a fmdat object to a data frame for ggplot2.
#'
#' \code{fortify} takes a \code{fmdat} object generated by
#' \code{\link{reformat_data}} and convert it to a data frame .
#' \code{fortify} requires \code{\link[ggplot2]{ggplot2}}.
#'
#' @param model \code{fmdat} object generated by
#'   \code{\link{reformat_data}}.
#' @param data Not used by this method.
#' @param ... Further arguments (ignored).
#' @return \code{fortify} retruns a data frame for \code{ggplot2}.
#'
#' @examples
#' library(ggplot2)
#' data(B500)
#' fmdat <- reformat_data(B500$good_er_scores, B500$labels)
#' df <- fortify(fmdat)
#' p <- ggplot(df, aes(x = x, y = y, color = x))
#' p <- p + geom_jitter()
#' p <- p + coord_flip()
#' p
fortify.fmdat <- function(model, data = NULL, ...) {
  # === Check package availability  ===
  .load_ggplot2()

  # === Validate input arguments ===
  .validate(model)

  # === Prepare a data frame for ggplot2 ===
  df <- data.frame(x = model[["obslabs"]],
                   y = model[["ranks"]])
}

#' Plot score distibutions by rank.
#'
#' \code{autoplot} takes a \code{fmdat} object generated by
#' \code{\link{reformat_data}} and plot score distribution by rank.
#' \code{autoplot} requires \code{\link[ggplot2]{ggplot2}}.
#'
#' @param object \code{fmdat} object generated by
#'   \code{\link{reformat_data}}.
#' @param ... Other arguments (ignored).
#' @return \code{autoplot} automatically shows a plot or returns
#'   a \code{ggplot} object.
#'
#' @examples
#' library(ggplot2)
#' data(B500)
#' fmdat <- reformat_data(B500$good_er_scores, B500$labels)
#' autoplot(fmdat)
autoplot.fmdat <- function(object, ...) {
  # === Check package availability  ===
  .load_ggplot2()

  # === Validate input arguments ===
  .validate(object)

  # === Prepare a data frame for ggplot2 ===
  df <- ggplot2::fortify(object)

  # === Create a ggplot object ===
  p <- ggplot2::ggplot(df, aes(x = x, y = y, color = x))
  p <- p + geom_jitter()
  p <- p + coord_flip()
  p <- p + theme_bw()
  p <- p + ggtitle("Score distributions by rank")
  p <- p + xlab(NULL)
  p <- p + ylab("rank")
  p <- p + theme(legend.position = "none")

  p
}

#' Convert a cmats object to a data frame for ggplot2.
#'
#' \code{fortify} takes a \code{cmats} object generated by
#' \code{\link{create_confmats}} and convert it to a data frame .
#' \code{fortify} requires \code{\link[ggplot2]{ggplot2}}.
#'
#' @param model \code{cmats} object generated by
#'   \code{\link{create_confmats}}.
#' @param data Not used by this method.
#' @param ... Further arguments (ignored).
#' @return \code{fortify} retruns a data frame for \code{ggplot2}.
#'
#' @examples
#' library(ggplot2)
#' data(B500)
#' cmat <- create_confmats(scores = B500$good_er_scores,
#'                         obslabs = B500$labels)
#' df <- fortify(cmat)
#' p <- ggplot2::ggplot(df, aes(x = x, y = y, color = group))
#' p <- p + geom_line()
#' p
fortify.cmats <- function(model, data = NULL, ...) {
  # === Check package availability  ===
  .load_ggplot2()

  # === Validate input arguments ===
  .validate(model)

  # === Prepare a data frame for ggplot2 ===
  n <- length(model[["ranks"]])
  df <- data.frame(x = rep(1:length(model[["ranks"]]), 4),
                   y = c(model[["tp"]],
                         model[["fn"]],
                         model[["fp"]],
                         model[["tn"]]),
                   group = factor(c(rep("TPs", n), rep("FNs", n),
                                    rep("FPs", n), rep("TNs", n)),
                                  levels = c("TPs", "FNs", "FPs", "TNs")))
}

#' Plot TPs, FNs, FPs, TNs by threshold IDs.
#'
#' \code{autoplot} takes a \code{cmats} object generated by
#' \code{\link{create_confmats}} and plot TPs, FNs, FPs, TNs by threshold IDs.
#' Threshold IDs are automatically generated.
#' \code{autoplot} requires \code{\link[ggplot2]{ggplot2}}.
#'
#' @param object \code{cmats} object generated by
#'   \code{\link{create_confmats}}.
#' @param ... Further arguments (ignored).
#' @return \code{autoplot} automatically shows a plot or returns
#'   a \code{ggplot} object.
#'
#' @examples
#' library(ggplot2)
#'
#' data(B500)
#' cmat <- create_confmats(scores = B500$good_er_scores,
#'                         obslabs = B500$labels)
#' autoplot(cmat)
autoplot.cmats <- function(object, ...) {
  # === Check package availability  ===
  .load_ggplot2()

  # === Validate input arguments ===
  .validate(object)

  # === Prepare a data frame for ggplot2 ===
  df <- ggplot2::fortify(object)

  # === Create a ggplot object ===
  p <- ggplot2::ggplot(df, aes(x = x, y = y, color = group))
  p <- p + geom_line()
  p <- p + theme_bw()
  p <- p + ggtitle("TPs, FNs, FPs, and TNs by threshold IDs")
  p <- p + xlab("threshold ID")
  p <- p + ylab("count")
  p <- p + theme(legend.title = element_blank())

  p
}

#' Convert an evals object to a data frame for ggplot2.
#'
#' \code{fortify} takes an \code{evals} object generated by
#' \code{\link{calc_measures}} and convert it to a data frame .
#' \code{fortify} requires \code{\link[ggplot2]{ggplot2}}.
#'
#' @param model \code{evals} object generated by
#'   \code{\link{calc_measures}}.
#' @param data Not used by this method.
#' @param ... Further arguments (ignored).
#' @return \code{fortify} retruns a data frame for \code{ggplot2}.
#'
#' @examples
#' library(ggplot2)
#' data(B500)
#' evals <- calc_measures(scores = B500$good_er_scores,
#'                        obslabs = B500$labels)
#' df <- fortify(evals)
#' p <- ggplot(df, aes(x = x, y = y))
#' p <- p + facet_wrap(~ group, ncol = 2)
#' p <- p + geom_line()
#' p
fortify.evals <- function(model, data = NULL, ...) {
  # === Check package availability  ===
  .load_ggplot2()

  # === Validate input arguments ===
  .validate(model)

  # === Prepare a data frame for ggplot2 ===
  n <- length(model[["error"]])
  df <- data.frame(x = rep(1:n, 6),
                   y = c(model[["error"]],
                         model[["accuracy"]],
                         model[["specificity"]],
                         model[["sensitivity"]],
                         1 - model[["specificity"]],
                         model[["precision"]]),
                   group = factor(c(rep("error", n),
                                    rep("accuracy", n),
                                    rep("specificity", n),
                                    rep("sensitivity", n),
                                    rep("1 - specificity", n),
                                    rep("precision", n)),
                                  levels = c("error", "accuracy",
                                             "specificity", "sensitivity",
                                             "1 - specificity",
                                             "precision")))
}

#' Plot basic evaluation measures by threshold IDs.
#'
#' \code{autoplot} takes \code{evals} object generated by
#' \code{\link{calc_measures}} and plot error-rate, accuracy, specificity,
#'   sensitivity, and precision values by threshold IDs.
#' Threshold IDs are automatically generated.
#' \code{autoplot} requires \code{\link[ggplot2]{ggplot2}}.
#'
#' @param object \code{evals} object generated by
#'   \code{\link{calc_measures}}.
#' @param ... Other arguments (ignored).
#' @return \code{autoplot} automatically shows a plot or returns
#'   a \code{ggplot} object.
#'
#' @examples
#' library(ggplot2)
#'
#' data(B500)
#' evals <- calc_measures(scores = B500$good_er_scores,
#'                        obslabs = B500$labels)
#' autoplot(evals)
autoplot.evals <- function(object, ...) {
  # === Check package availability  ===
  .load_ggplot2()

  # === Validate input arguments ===
  .validate(object)

  # === Prepare a data frame for ggplot2 ===
  df <- ggplot2::fortify(object)

  # === Create a ggplot object ===
  p <- ggplot2::ggplot(df, aes(x = x, y = y))
  p <- p + facet_wrap(~ group, ncol = 2)
  p <- p + geom_line()
  p <- p + theme_bw()
  p <- p + ggtitle("Evaluation measures by threshold IDs")
  p <- p + xlab("threshold ID")
  p <- p + ylab("evaluation value")

  p
}

#' Convert a roc_curve object to a data frame for ggplot2.
#'
#' \code{fortify} takes a \code{roc_curve} object generated by
#' \code{\link{create_roc}} and convert it to a data frame .
#' \code{fortify} requires \code{\link[ggplot2]{ggplot2}}.
#'
#' @param model \code{roc_curve} object generated by
#'   \code{\link{create_roc}}.
#' @param data Not used by this method.
#' @param ... Further arguments (ignored).
#' @return \code{fortify} retruns a data frame for \code{ggplot2}.
#'
#' @examples
#' library(ggplot2)
#' data(B500)
#' roc_curve <- create_roc(scores = B500$good_er_scores,
#'                         obslabs = B500$labels)
#' df <- fortify(roc_curve)
#' p <- ggplot2::ggplot(df, aes(x = x, y = y))
#' p <- p + geom_line()
#' p
fortify.roc_curve <- function(model, data = NULL, ...) {
  # === Check package availability  ===
  .load_ggplot2()

  # === Validate input arguments ===
  .validate(model)

  # === Prepare a data frame for ggplot2 ===
  df <- data.frame(x = model[["x"]], y = model[["y"]])

}

#' Plot a ROC curve.
#'
#' \code{autoplot} takes \code{roc_curve} object generated by
#' \code{\link{create_roc}} and plot a ROC curve.
#' \code{autoplot} requires \code{\link[ggplot2]{ggplot2}}.
#'
#' @param object \code{roc_curve} object generated by
#'   \code{\link{create_roc}}.
#' @param ... Other arguments (ignored).
#' @return \code{autoplot} automatically shows a plot or returns
#'   a \code{ggplot} object.
#'
#' @examples
#' library(ggplot2)
#'
#' data(B500)
#' roc_curve <- create_roc(scores = B500$good_er_scores,
#'                         obslabs = B500$labels)
#' autoplot(roc_curve)
autoplot.roc_curve <- function(object, ...) {
  # === Check package availability  ===
  .load_ggplot2()

  # === Validate input arguments ===
  .validate(object)

  # === Create a ggplot object for ROC&PRC, ROC, or PRC ===
  np <- object[["pos_num"]]
  nn <- object[["neg_num"]]
  df <- ggplot2::fortify(object)

  # === Create a ggplot object ===
  p <- ggplot2::ggplot(df, aes(x = x, y = y))
  p <- p + geom_line()
  p <- p + geom_abline(intercept = 0, slope = 1, colour = "grey",
                       linetype = 3)
  p <- p + theme_bw()
  p <- p + ggtitle(paste("ROC - P: ", np, ", N: ", nn, sep=""))
  p <- p + xlab("1 - Specificity")
  p <- p + ylab("Sensitivity")

  p
}

#' Convert a prc_curve object to a data frame for ggplot2.
#'
#' \code{fortify} takes a \code{prc_curve} object generated by
#' \code{\link{create_prc}} and convert it to a data frame .
#' \code{fortify} requires \code{\link[ggplot2]{ggplot2}}.
#'
#' @param model \code{prc_curve} object generated by
#'   \code{\link{create_prc}}.
#' @param data Not used by this method.
#' @param ... Further arguments (ignored).
#' @return \code{fortify} retruns a data frame for \code{ggplot2}.
#'
#' @examples
#' library(ggplot2)
#' data(B500)
#' prc_curve <- create_prc(scores = B500$good_er_scores,
#'                         obslabs = B500$labels)
#' df <- fortify(prc_curve)
#' p <- ggplot2::ggplot(df, aes(x = x, y = y))
#' p <- p + geom_line()
#' p
fortify.prc_curve <- function(model, data = NULL, ...) {
  fortify.roc_curve(model, data)
}

#' Plot a Precision-Recall curve.
#'
#' \code{autoplot} takes \code{prc_curve} object generated by
#' \code{\link{create_prc}} and plot a Precision-Recall curve.
#' \code{autoplot} requires \code{\link[ggplot2]{ggplot2}}.
#'
#' @param object \code{prc_curve} object generated by
#'   \code{\link{create_prc}}.
#' @param ... Other arguments (ignored).
#' @return \code{autoplot} automatically shows a plot or returns
#'   a \code{ggplot} object.
#'
#' @examples
#' library(ggplot2)
#'
#' data(B500)
#' prc_curve <- create_prc(scores = B500$good_er_scores,
#'                         obslabs = B500$labels)
#' autoplot(prc_curve)
autoplot.prc_curve <- function(object, ...) {
  # === Check package availability  ===
  .load_ggplot2()

  # === Validate input arguments ===
  .validate(object)

  # === Create a ggplot object for ROC&PRC, ROC, or PRC ===
  np <- object[["pos_num"]]
  nn <- object[["neg_num"]]
  df <- ggplot2::fortify(object)

  # === Create a ggplot object ===
  p <- ggplot2::ggplot(df, aes(x = x, y = y))
  p <- p + geom_line()
  p <- p + geom_hline(yintercept = np / (np + nn), colour = "grey",
                      linetype = 3)
  p <- p + theme_bw()
  p <- p + scale_y_continuous(limits = c(0.0, 1.0))
  p <- p + ggtitle(paste("Precision-Recall - P: ", np, ", N: ", nn, sep=""))
  p <- p + xlab("Recall")
  p <- p + ylab("Precision")

  p
}

#' Convert a curves object to a data frame for ggplot2.
#'
#' \code{fortify} takes a \code{curves} object generated by
#' \code{\link{create_curves}} and convert it to a data frame .
#' \code{fortify} requires \code{\link[ggplot2]{ggplot2}}.
#'
#' @param model \code{curves} object generated by
#'   \code{\link{create_curves}}.
#' @param data Not used by this method.
#' @param ... Further arguments (ignored).
#' @return \code{fortify} retruns a data frame for \code{ggplot2}.
#'
#' @examples
#' library(ggplot2)
#' data(B500)
#' curves <- create_curves(scores = B500$good_er_scores,
#'                         obslabs = B500$labels)
#' df <- fortify(curves)
#' p_roc <- ggplot2::ggplot(subset(df, group == "ROC"), aes(x = x, y = y))
#' p_roc <- p_roc + geom_line()
#' p_roc
#'
#' p_prc <- ggplot2::ggplot(subset(df, group == "PRC"), aes(x = x, y = y))
#' p_prc <- p_prc + geom_line()
#' p_prc
fortify.curves <- function(model, data = NULL, ...) {
  # === Check package availability  ===
  .load_ggplot2()

  # === Validate input arguments ===
  .validate(model)

  # === Prepare a data frame for ggplot2 ===
  x = c(model[["roc"]][["x"]], model[["prc"]][["x"]])
  y = c(model[["roc"]][["y"]], model[["prc"]][["y"]])
  group = factor(c(rep("ROC",
                       length(model[["roc"]][["x"]])),
                   rep("PRC", length(model[["prc"]][["x"]]))))
  df <- data.frame(x = x, y = y, group = group)

}

#' Plot ROC and Precision-Recall curves.
#'
#' \code{autoplot} takes \code{curves} object generated by
#' \code{\link{create_curves}} and plot ROC and Precion-Recall curves.
#' \code{autoplot} requires \code{\link[ggplot2]{ggplot2}} and
#' \code{\link[gridExtra]{grid.arrange}}.
#'
#' @param object \code{curves} object generated by
#'   \code{\link{create_curves}}.
#' @param ... Other arguments (ignored).
#' @return \code{autoplot} automatically shows a plot or returns
#'   a \code{ggplot} object.
#'
#' @examples
#' library(ggplot2)
#' library(gridExtra)
#'
#' data(B500)
#' curves <- create_curves(scores = B500$good_er_scores,
#'                         obslabs = B500$labels)
#' autoplot(curves)
autoplot.curves <- function(object, curvetype = c("ROC", "PRC"), ...) {
  # === Check package availability  ===
  .load_ggplot2()
  if (!requireNamespace("gridExtra", quietly = TRUE)) {
    stop("gridExtra needed for this function to work. Please install it.",
         call. = FALSE)
  }

  # === Validate input arguments ===
  .validate(object)

  if (!is.atomic(curvetype) || !is.character(curvetype) || length(curvetype) > 2
      || length(setdiff(curvetype, c("ROC", "PRC"))) != 0)
  {
    stop("Invalid 'curvetype' value")
  }

  # === Create a ggplot object for ROC&PRC, ROC, or PRC ===
  if ("ROC" %in% curvetype) {
    p_roc <- autoplot(object[["roc"]])
  }

  if ("PRC" %in% curvetype) {
    p_prc <- autoplot(object[["prc"]])
  }

  if ("ROC" %in% curvetype && "PRC" %in% curvetype) {
    gridExtra::grid.arrange(p_roc, p_prc, ncol=2)
  } else if ("PRC" %in% curvetype) {
    p_prc
  } else if ("ROC" %in% curvetype) {
    p_roc
  }
}

