#' Create partical ROC and Precision-Recall curves.
#'
#' \code{clip_curves} takes ROC and Precision-Recall curves as
#' \code{curves} object and returns another \code{curves} object.
#'
#' @param curves \code{curves} S3 object generated by
#'   \code{\link{create_curves}} or \code{clip_curves} itself.
#' @param x.left A numeric value to specifiy an interval of the
#'   x-axis (TPRs and Recall for ROC and Precision-Recall, respectively).
#' @param x.right A numeric value to specifiy an interval of the
#'   x-axis (TPRs and Recall for ROC and Precision-Recall, respectively).
#' @param y.bottom A numeric value to specifiy an interval of the
#'   x-axis (TPRs and Recall for ROC and Precision-Recall, respectively).
#' @param y.top A numeric value to specifiy an interval of the
#'   x-axis (TPRs and Recall for ROC and Precision-Recall, respectively).
#' @param vtype Not used.
#' @return \code{clip_curves} returns an \code{curves} S3 object that
#'   contains partial ROC and Precision-Recall curves.
#'
#' @examples
#' data(P10N10)
#' fmdat <- reformat_data(P10N10$scores, P10N10$labels)
#' cdat <- create_confmats(fmdat)
#' evals <- calc_measures(cdat)
#' curves <- create_curves(evals)
#' pcurves <- clip_curves(curves)
clip_curves <- function(curves, ctype = c("ROC", "PRC"), x.left = 0.0,
                        x.right = 1.0, y.bottom = 0.0, y.top = 1.0,
                        vtype = "pct") {
  # === Validate input arguments ===
  .validate_clip_curves_args(evals, ctype, x.left, x.right, y.bottom,
                             y.top, vtype)

  # === Create ROC and Precision-Recall curves ===
  # Calculate a ROC curve
  roc_curve <- create_roc_curve(evals[["specificity"]], evals[["sensitivity"]],
                                x.interval)
  if (roc_curve[["ERRMSG"]] != "") {
    stop(paste("An internal function (create_roc_curve()) failed:",
               roc_curve[["ERRMSG"]]))
  }

  # Calculate AUC for ROC
  roc_auc <- calc_auc(roc_curve[["FPR"]], roc_curve[["TPR"]])
  if (roc_auc[["ERRMSG"]] == "invalid-x-vals") {
    warning("Invalid FPR values detected. AUC(ROC) can be inaccurate.")
  } else if (roc_auc[["ERRMSG"]] != "") {
    stop(paste("An internal function (roc_auc()) failed for PRCAUC:",
               roc_auc[["ERRMSG"]]))
  }

  # Calculate a Precision-Recall curve
  prc_curve <- create_prc_curve(evals[["cmats"]][["TPs"]],
                                evals[["cmats"]][["FPs"]],
                                evals[["sensitivity"]],
                                evals[["precision"]],
                                x.interval)
  if (prc_curve[["ERRMSG"]] != "") {
    stop(paste("An internal function (create_prc_curve()) failed:",
               prc_curve[["ERRMSG"]]))
  }

  # Calculate AUC for Precision-Recall
  prc_auc <- calc_auc(prc_curve[["REC"]], prc_curve[["PREC"]])
  if (prc_auc[["ERRMSG"]] == "invalid-x-vals") {
    warning("Invalid sensitivity values detected. AUC(PRC) can be inaccurate.")
  } else if (prc_auc[["ERRMSG"]] != "") {
    stop(paste("An internal function (roc_auc()) failed for PRCAUC:",
               prc_auc[["ERRMSG"]]))
  }

  # === Create an S3 object ===
  curves = list(P = evals[["P"]], N = evals[["N"]],
                FPR = roc_curve[["FPR"]], TPR = roc_curve[["TPR"]],
                ROC_orig_points = roc_curve[["ROC_orig_points"]],
                ROCAUC = roc_auc[["AUC"]],
                REC = prc_curve[["REC"]], PREC = prc_curve[["PREC"]],
                PRC_orig_points = prc_curve[["PRC_orig_points"]],
                PRCAUC = prc_auc[["AUC"]])
  curves[["evals"]] <- evals
  curves[["validated"]] <- FALSE

  # Call .validate.evalvals()
  .validate(structure(curves, class = "evalcurves"))
}
