# General function for creating ROC and Precision-Recall curves
.create_curve <- function(x_name, y_name, func, func_name, class_name,
                          evals, x_interval = 0.001, scores = NULL,
                          obslabs = NULL, ...) {
  # === Validate input arguments ===
  .validate_create_curves_args(evals, "evals", x_interval, scores, obslabs,
                               ...)
  # Create evals from scores and obslabs if it's missing
  evals <- .create_by_scores_and_labels(evals, "evals", calc_measures,
                                        scores, obslabs, ...)

  # === Create a curve ===
  # Calculate a curve
  crv <- func(evals[["cmats"]][["tp"]], evals[["cmats"]][["fp"]],
              evals[[x_name]], evals[[y_name]], x_interval)
  .check_cpp_func_error(crv, func_name)

  # Calculate AUC
  auc <- calc_auc(crv[["x"]], crv[["y"]])
  if (auc[["errmsg"]] == "invalid-x-vals") {
    warning(paste("Invalid", x_name, "values detected. AUC can be inaccurate."))
  } else {
    .check_cpp_func_error(auc, "calc_auc")
  }

  # === Create an S3 object ===
  crv[["errmsg"]] <- NULL
  crv[["pos_num"]] <- evals[["pos_num"]]
  crv[["neg_num"]] <- evals[["neg_num"]]
  crv[["auc"]] <- auc[["auc"]]
  crv[["auc2"]] <- NA
  crv[["clipped"]] <- FALSE
  crv[["x_limits"]] <- c(0, 1)
  crv[["y_limits"]] <- c(0, 1)
  crv[["smoothed"]] <- FALSE
  crv[["smooth_method"]] <- NA
  crv[["orig_curve"]] <- NA
  crv[["evals"]] <- evals
  crv[["validated"]] <- FALSE

  # Call .validate.roc_curve() or .validate.prc_curve()
  .validate(structure(crv, class = class_name))
}

#' Create a ROC curve.
#'
#' \code{create_roc} takes basic evaluation measures as
#' \code{evals} object and returns a \code{roc_curve} object.
#' \code{roc_curve} contains a ROC curve.
#' \code{create_roc} can also take scores and lables directly.
#'
#' @param evals \code{evals} S3 object generated by
#'   \code{\link{calc_measures}}.
#' @param x_interval A numeric value to specifiy an interval of the
#'   x-axis (TPRs).
#' @param scores A numeric vector of predicted scores.
#'   Ignored when \code{cmats} is set.
#' @param obslabs A numeric vector or a factor of observed labels.
#'   Ignored when \code{cmats} is set.
#' @param ... Other arguments passed to \code{\link{reformat_data}} via
#'   \code{\link{calc_measures}} and \code{\link{create_confmats}}.
#' @return \code{create_roc} returns a \code{roc_curve} S3 object that
#'   contains a ROC curve.
#'
#' @examples
#' data(P10N10)
#' fmdat <- reformat_data(P10N10$scores, P10N10$labels)
#' cdat <- create_confmats(fmdat)
#' evals <- calc_measures(cdat)
#' create_roc(evals)
#' create_roc(scores = P10N10$scores, obslabs = P10N10$labels)
create_roc <- function(evals, x_interval = 0.001, scores = NULL,
                       obslabs = NULL, ...) {
  # === Create a ROC curve ===
  .create_curve("specificity", "sensitivity", create_roc_curve,
                "create_roc_curve", "roc_curve", evals, x_interval,
                scores, obslabs, ...)
}

#' Create a Precision-Recall curve.
#'
#' \code{create_prc} takes basic evaluation measures as
#' \code{evals} object and returns a \code{prc_curve} object.
#' \code{prc_curve} contains a Precision-Recall curve.
#' \code{create_roc} can also take scores and lables directly.
#'
#' @param evals \code{evals} S3 object generated by
#'   \code{\link{calc_measures}}.
#' @param x_interval A numeric value to specifiy an interval of the
#'   x-axis (recall).
#' @param scores A numeric vector of predicted scores.
#'   Ignored when \code{cmats} is set.
#' @param obslabs A numeric vector or a factor of observed labels.
#'   Ignored when \code{cmats} is set.
#' @param ... Other arguments passed to \code{\link{reformat_data}} via
#'   \code{\link{calc_measures}} and \code{\link{create_confmats}}.
#' @return \code{create_prc} returns a \code{prc_curve} S3 object that
#'   contains a Precision-Recall curve.
#'
#' @examples
#' data(P10N10)
#' fmdat <- reformat_data(P10N10$scores, P10N10$labels)
#' cdat <- create_confmats(fmdat)
#' evals <- calc_measures(cdat)
#' create_roc(evals)
#' create_roc(scores = P10N10$scores, obslabs = P10N10$labels)
create_prc <- function(evals, x_interval = 0.001, scores = NULL,
                       obslabs = NULL, ...) {
  # === Create a Precision-Recall curve ===
  .create_curve("sensitivity", "precision", create_prc_curve,
                "create_prc_curve", "prc_curve", evals, x_interval,
                scores, obslabs, ...)
}

#' Create ROC and Precision-Recall curves.
#'
#' \code{create_curves} takes basic evaluation measures as
#' \code{evals} object and returns a \code{curves} object.
#' \code{curves} contains ROC and Precision-Recall curves.
#' \code{create_curves} can also take scores and lables directly.
#'
#' @param evals \code{evals} S3 object generated by
#'   \code{\link{calc_measures}}.
#' @param x_interval A numeric value to specifiy an interval of the
#'   x-axis (TPRs for ROC and recall for Precision-Recall).
#' @param scores A numeric vector of predicted scores.
#'   Ignored when \code{cmats} is set.
#' @param obslabs A numeric vector or a factor of observed labels.
#'   Ignored when \code{cmats} is set.
#' @param ... Other arguments passed to \code{\link{reformat_data}} via
#'   \code{\link{calc_measures}} and \code{\link{create_confmats}}.
#' @return \code{create_curves} returns a \code{curves} S3 object that
#'   contains ROC and Precision-Recall curves.
#'
#' @examples
#' data(P10N10)
#' fmdat <- reformat_data(P10N10$scores, P10N10$labels)
#' cdat <- create_confmats(fmdat)
#' evals <- calc_measures(cdat)
#' create_curves(evals)
#' create_curves(scores = P10N10$scores, obslabs = P10N10$labels)
create_curves <- function(evals, x_interval = 0.001, scores = NULL,
                          obslabs = NULL, ...) {
  # === Validate input arguments ===
  .validate_create_curves_args(evals, "evals", x_interval,
                               scores, obslabs,  ...)

  # Create evals from scores and obslabs if it's missing
  evals <- .create_by_scores_and_labels(evals, "evals", calc_measures,
                                        scores, obslabs, ...)

  # === Create ROC and Precision-Recall curves ===
  roc_curve <- create_roc(evals, x_interval)
  prc_curve <- create_prc(evals, x_interval)

  # === Create an S3 object ===
  curves <- list(roc = roc_curve, prc = prc_curve)
  curves[["validated"]] <- FALSE

  # Call .validate.curves()
  .validate(structure(curves, class = "curves"))
}
