#' Calculate confusion matrices for all possible threshold values.
#'
#' \code{create_confmats} takes predicted scores and binary lables as
#' \code{fmdat} object and returns a \code{cmats} object.
#' \code{cmats} contains TPs, FPs, FNs, TNs, and ranks that are used
#' by a subsequent function, \code{\link{calc_measures}}, in the perforamcne
#' evaluation pipeline. \code{create_confmats} can also take scores and lables
#' directly.
#'
#' @param fmdat \code{fmdat} S3 object generated by
#'   \code{\link{reformat_data}}.
#' @param scores A numeric vector of predicted scores.
#'   Ignored when \code{fmdat} is set.
#' @param obslabs A numeric vector or a factor of observed labels.
#'   Ignored when \code{fmdat} is set.
#' @param ... Other arguments passed to \code{\link{reformat_data}}.
#' @return \code{create_confmats} returns a \code{cmats} S3 object that
#'   contains TPs, FPs, FNs, and TNs.
#'
#' @examples
#' data(P10N10)
#' fmdat <- reformat_data(P10N10$scores, P10N10$labels)
#' create_confmats(fmdat)
#' create_confmats(scores = P10N10$scores, obslabs = P10N10$labels)
create_confmats <- function(fmdat, scores = NULL, obslabs = NULL, ...) {
  # === Validate input arguments ===
  # Create fmdat from scores and obslabs if it's missing
  fmdat <- .create_by_scores_and_labels(fmdat, "fmdat", reformat_data,
                                        scores, obslabs, ...)

  # === Create confusion matrices for all possible threshold values ===
  # Call a cpp function via Rcpp interface
  cmats <- create_confusion_matrices(fmdat[["obslabs"]], fmdat[["ranks"]],
                                     fmdat[["rank_idx"]])
  .check_cpp_func_error(cmats, "create_confusion_matrices")

  # === Create an S3 object ===
  cmats[["errmsg"]] <- NULL
  cmats[["fmdat"]] <- fmdat
  cmats[["validated"]] <- FALSE

  # Call .validate.confmats()
  .validate(structure(cmats, class = "cmats"))
}
