#
# Validate 'smcurves' object generated by pl_main()
#
.validate.smcurves <- function(smcurves) {
  # Need to validate only once
  if (class(smcurves) == "mscurves" && attr(smcurves, "validated")) {
    return(smcurves)
  }

  # Check smcurves
  if (class(smcurves) != "smcurves") {
    stop("'mscurves' S3 object created by pl_main() expected")
  }

  attr(smcurves, "validated") <- TRUE
  smcurves
}

#
# Validate 'smroc' object generated by pl_main()
#
.validate.smroc <- function(smroc) {
  # Need to validate only once
  if (class(smroc) == "smroc" && attr(smroc, "validated")) {
    return(smroc)
  }

  # Check smroc
  if (class(smroc) != "smroc") {
    stop("'smroc' S3 object created by pl_main() expected")
  }

  attr(smroc, "validated") <- TRUE
  smroc
}

#
# Validate 'smprc' object generated by pl_main()
#
.validate.smprc <- function(smprc) {
  # Need to validate only once
  if (class(smprc) == "smprc" && attr(smprc, "validated")) {
    return(smprc)
  }

  # Check smprc
  if (class(smprc) != "smprc") {
    stop("'smprc' S3 object created by pl_main() expected")
  }

  attr(smprc, "validated") <- TRUE
  smprc
}
