#
# Validate 'mscurves' object generated by pl_main()
#
.validate.mscurves <- function(mscurves) {
  # Need to validate only once
  if (is(mscurves, "mscurves") && attr(mscurves, "validated")) {
    return(mscurves)
  }

  # Check mscurves
  if (!is(mscurves, "mscurves")) {
    stop("'mscurves' S3 object created by pl_main() expected")
  }

  attr(mscurves, "validated") <- TRUE
  mscurves
}

#
# Validate 'msroc' object generated by pl_main()
#
.validate.msroc <- function(msroc) {
  # Need to validate only once
  if (is(msroc, "msroc") && attr(msroc, "validated")) {
    return(msroc)
  }

  # Check msroc
  if (!is(msroc, "msroc")) {
    stop("'msroc' S3 object created by pl_main() expected")
  }

  attr(msroc, "validated") <- TRUE
  msroc
}

#
# Validate 'msprc' object generated by pl_main()
#
.validate.msprc <- function(msprc) {
  # Need to validate only once
  if (is(msprc, "msprc") && attr(msprc, "validated")) {
    return(msprc)
  }

  # Check msprc
  if (!is(msprc, "msprc")) {
    stop("'msprc' S3 object created by pl_main() expected")
  }

  attr(msprc, "validated") <- TRUE
  msprc
}
