#
# Validate 'mdat' object generated by mmdata()
#
.validate.mdat <- function(mdat) {
  # Need to validate only once
  if (is(mdat, "mdat") && attr(mdat, "validated")) {
    return(mdat)
  }

  # Check mdat
  if (!is(mdat, "mdat")) {
    stop("'mdat' S3 object created by mmdata() expected")
  }

  # Check attributes
  if (length(mdat) != nrow(attr(mdat, "data_info"))) {
    stop("Invalid modnames and dsids")
  }

  attr(mdat, "validated") <- TRUE
  mdat
}

#
# Validate 'fmdat' object generated by reformat_data()
#
.validate.fmdat <- function(fmdat) {
  # Need to validate only once
  if (is(fmdat, "fmdat") && attr(fmdat, "validated")) {
    return(fmdat)
  }

  # Validate class items and attributes
  item_names <- c("labels", "ranks", "rank_idx")
  attr_names <- c("modname", "dsid", "nn", "np", "args", "validated")
  arg_names <- c("na_worst", "ties_method", "modname", "dsid")
  .validate_basic(fmdat, "fmdat", "reformat_data", item_names, attr_names,
                  arg_names)

  # Check values of class items
  if (length(fmdat[["labels"]]) == 0
      || length(fmdat[["labels"]]) != length(fmdat[["ranks"]])
      || length(fmdat[["labels"]]) != length(fmdat[["rank_idx"]])) {
    stop("Items in 'fmdat' must be of the same length")
  }

  # Labels
  assertthat::assert_that(is.atomic(fmdat[["labels"]]),
                          is.vector(fmdat[["labels"]]),
                          is.numeric(fmdat[["labels"]]))

  # Ranks
  assertthat::assert_that(is.atomic(fmdat[["ranks"]]),
                          is.vector(fmdat[["ranks"]]),
                          is.numeric(fmdat[["ranks"]]))

  # Rank index
  assertthat::assert_that(is.atomic(fmdat[["rank_idx"]]),
                          is.vector(fmdat[["rank_idx"]]),
                          is.integer(fmdat[["rank_idx"]]))

  attr(fmdat, "validated") <- TRUE
  fmdat
}

#
# Validate 'cmats' object generated by create_confmats()
#
.validate.cmats <- function(cmats) {
  # Need to validate only once
  if (is(cmats, "cmats") && attr(cmats, "validated")) {
    return(cmats)
  }

  # Validate class items and attributes
  item_names <- c("pos_num", "neg_num", "tp", "fp", "tn", "fn", "ranks")
  attr_names <- c("modname", "dsid", "nn", "np", "args", "cpp_errmsg",
                  "src", "validated")
  arg_names <- c("na_worst", "ties_method", "modname", "dsid", "keep_fmdat")
  .validate_basic(cmats, "cmats", "create_confmats", item_names, attr_names,
                  arg_names)

  # Check values of class items
  n <- length(cmats[["tp"]])
  if (length(cmats[["fp"]]) != n || length(cmats[["tn"]]) != n
      || length(cmats[["fn"]]) != n) {
    stop("tp, fp, tn, and fn in 'cmats' must be the same length")
  }

  # TP
  assertthat::assert_that(is.atomic(cmats[["tp"]]),
                          is.vector(cmats[["tp"]]),
                          is.numeric(cmats[["tp"]]),
                          cmats[["tp"]][1] == 0,
                          cmats[["tp"]][n] == cmats[["pos_num"]])

  # FP
  assertthat::assert_that(is.atomic(cmats[["fp"]]),
                          is.vector(cmats[["fp"]]),
                          is.numeric(cmats[["fp"]]),
                          cmats[["fp"]][1] == 0,
                          cmats[["fp"]][n] == cmats[["neg_num"]])

  # FN
  assertthat::assert_that(is.atomic(cmats[["fn"]]),
                          is.vector(cmats[["fn"]]),
                          is.numeric(cmats[["fn"]]),
                          cmats[["fn"]][1] == cmats[["pos_num"]],
                          cmats[["fn"]][n] == 0)

  # TN
  assertthat::assert_that(is.atomic(cmats[["tn"]]),
                          is.vector(cmats[["tn"]]),
                          is.numeric(cmats[["tn"]]),
                          cmats[["tn"]][1] == cmats[["neg_num"]],
                          cmats[["tn"]][n] == 0)

  attr(cmats, "validated") <- TRUE
  cmats
}

#
# Validate 'pevals' object generated by calc_measures()
#
.validate.pevals <- function(pevals) {
  # Need to validate only once
  if (is(pevals, "pevals") && attr(pevals, "validated")) {
    return(pevals)
  }

  # Validate class items and attributes
  item_names <- c("basic")
  attr_names <- c("modname", "dsid", "nn", "np", "args", "cpp_errmsg",
                  "src", "validated")
  arg_names <- c("na_worst", "ties_method", "modname", "dsid", "keep_fmdat")
  .validate_basic(pevals, "pevals", "calc_measures", item_names, attr_names,
                  arg_names)

  pb <- pevals[["basic"]]

  # Check values of class items
  n <- length(pb[["error"]])
  if (length(pb[["accuracy"]]) != n
      || length(pb[["specificity"]]) != n
      || length(pb[["sensitivity"]]) != n
      || length(pb[["precision"]]) != n) {
    stop("All evaluation vectors must be the same length")
  }

  # Error rate
  assertthat::assert_that(is.atomic(pb[["error"]]),
                          is.vector(pb[["error"]]),
                          is.numeric(pb[["error"]]))

  # Accuracy
  assertthat::assert_that(is.atomic(pb[["accuracy"]]),
                          is.vector(pb[["accuracy"]]),
                          is.numeric(pb[["accuracy"]]))

  # Error rate & Arruracy
  assertthat::assert_that(pb[["error"]][1] + pb[["accuracy"]][1] == 1,
                          pb[["error"]][n] + pb[["accuracy"]][n] ==1)

  # SP
  assertthat::assert_that(is.atomic(pb[["specificity"]]),
                          is.vector(pb[["specificity"]]),
                          is.numeric(pb[["specificity"]]),
                          pb[["specificity"]][1] == 1,
                          pb[["specificity"]][n] == 0)

  # SN
  assertthat::assert_that(is.atomic(pb[["sensitivity"]]),
                          is.vector(pb[["sensitivity"]]),
                          is.numeric(pb[["sensitivity"]]),
                          pb[["sensitivity"]][1] == 0,
                          pb[["sensitivity"]][n] == 1)

  # PREC
  assertthat::assert_that(is.atomic(pb[["precision"]]),
                          is.vector(pb[["precision"]]),
                          is.numeric(pb[["precision"]]),
                          pb[["precision"]][1] == pb[["precision"]][2])

  attr(pevals, "validated") <- TRUE
  pevals
}

#
# Validate 'roc_curve' object generated by create_roc()
#
.validate.roc_curve <- function(roc_curve) {
  # Need to validate only once
  if (is(roc_curve, "roc_curve") && attr(roc_curve, "validated")) {
    return(roc_curve)
  }

  # Validate class items and attributes
  .validate_curve(roc_curve, "roc_curve", "create_roc")

  attr(roc_curve, "validated") <- TRUE
  roc_curve
}

#
# Validate 'prc_curve' object generated by create_roc()
#
.validate.prc_curve <- function(prc_curve) {
  # Need to validate only once
  if (is(prc_curve, "prc_curve") && attr(prc_curve, "validated")) {
    return(prc_curve)
  }

  # Validate class items and attributes
  .validate_curve(prc_curve, "prc_curve", "create_prc")

  attr(prc_curve, "validated") <- TRUE
  prc_curve
}

#
# Validate 'roc_curve' or 'prc_curve'
#
.validate_curve <- function(obj, class_name, func_name) {
  # Validate class items and attributes
  item_names <- c("x", "y", "orig_points")
  attr_names <- c("modname", "dsid", "nn", "np", "auc", "args",
                  "cpp_errmsg1", "cpp_errmsg2", "src", "validated")
  arg_names <- c("x_bins", "na_worst", "ties_method",
                 "modname", "dsid", "keep_fmdat", "keep_cmats")
  .validate_basic(obj, class_name, func_name, item_names, attr_names,
                  arg_names)

  # Check values of class items
  if ((length(obj[["x"]]) != length(obj[["y"]]))
      || (length(obj[["x"]]) != length(obj[["orig_points"]]))) {
    stop("x, y, and orig_points must be the same length")
  } else if (!(length(obj[["x"]]) > 2)) {
    stop("x, y, and orig_points must be >2")
  }

  # Check values of class attributes
  # AUC
  assertthat::assert_that((attr(obj, "auc") >= 0) && (attr(obj, "auc") <= 1))

}

#
# Validate 'curves' object generated by create_curves()
#
.validate.curves <- function(curves) {
  # Need to validate only once
  if (is(curves, "curves") && attr(curves, "validated")) {
    return(curves)
  }

  # Validate class items and attributes
  item_names <- c("roc", "prc")
  attr_names <- c("modname", "dsid", "nn", "np", "args", "src",
                  "validated")
  arg_names <- c("x_bins", "na_worst", "ties_method", "modname", "dsid",
                 "keep_fmdat", "keep_cmats")
  .validate_basic(curves, "curves", "calc_measures", item_names, attr_names,
                  arg_names)

  # Check values of class items
  curves[["roc"]] <- .validate(curves[["roc"]])
  curves[["prc"]] <- .validate(curves[["prc"]])

  attr(curves, "validated") <- TRUE
  curves
}

#
# Validate 'avgcurves' object generated by create_curves()
#
.validate.avgcurves <- function(avgcurves) {
  # Need to validate only once
  if (is(avgcurves, "avgcurves") && attr(avgcurves, "validated")) {
    return(avgcurves)
  }

  # Validate class items and attributes
  item_names <- NULL
  attr_names <- c("args", "src", "validated")
  arg_names <- c("ci_alpha", "x_bins")
  .validate_basic(avgcurves, "avgcurves", "calc_avg", item_names, attr_names,
                  arg_names)

  # Check values of class items


  attr(avgcurves, "validated") <- TRUE
  avgcurves
}

