#
# Validate 'sscurves' object generated by pl_main()
#
.validate.sscurves <- function(sscurves) {
  # Need to validate only once
  if (is(sscurves, "sscurves") && attr(sscurves, "validated")) {
    return(sscurves)
  }

  # Check sscurves
  if (!is(sscurves, "sscurves")) {
    stop("'sscurves' S3 object created by pl_main() expected")
  }

  attr(sscurves, "validated") <- TRUE
  sscurves
}

#
# Validate 'ssroc' object generated by pl_main()
#
.validate.ssroc <- function(ssroc) {
  # Need to validate only once
  if (is(ssroc, "ssroc") && attr(ssroc, "validated")) {
    return(ssroc)
  }

  # Check ssroc
  if (!is(ssroc, "ssroc")) {
    stop("'ssroc' S3 object created by pl_main() expected")
  }

  attr(ssroc, "validated") <- TRUE
  ssroc
}

#
# Validate 'ssprc' object generated by pl_main()
#
.validate.ssprc <- function(ssprc) {
  # Need to validate only once
  if (is(ssprc, "ssprc") && attr(ssprc, "validated")) {
    return(ssprc)
  }

  # Check ssprc
  if (!is(ssprc, "ssprc")) {
    stop("'ssprc' S3 object created by pl_main() expected")
  }

  attr(ssprc, "validated") <- TRUE
  ssprc
}
