# Validate 'mdat' object generated by mmdata()
.validate.mdat <- function(mdat) {
  # Need to validate only once
  if (class(mdat) == "mmdata" && attr(mdat, "validated")) {
    return(mdat)
  }

  # Check mdat
  if (class(mdat) != "mdat") {
    stop("'mdat' S3 object created by mmdata() expected")
  }

  # Check attributes
  if (length(mdat) != length(attr(mdat, "model_names"))) {
    stop("Invalid 'model_names'")
  }

  if (length(mdat) != length(attr(mdat, "data_nos"))) {
    stop("Invalid 'data_nos'")
  }

  attr(mdat, "validated") <- TRUE
  mdat
}

# Validate 'mfmdat' object generated by reformat_mdata()
.validate.mfmdat <- function(mfmdat) {
  # Need to validate only once
  if (class(mfmdat) == "mfmdat" && attr(mfmdat, "validated")) {
    return(mfmdat)
  }

  # Check mdat
  if (class(mfmdat) != "mfmdat") {
    stop("'mfmdat' S3 object created by reformat_mdata() expected")
  }

  attr(mfmdat, "validated") <- TRUE
  mfmdat
}

# Validate 'mroc_curves' object generated by .get_curves()
.validate.mroc_curves <- function(mroc_curves) {
  # Need to validate only once
  if (class(mroc_curves) == "mroc_curves" && attr(mroc_curves, "validated")) {
    return(mroc_curves)
  }

  # Check mroc_curves
  if (class(mroc_curves) != "mroc_curves") {
    stop("'mroc_curves' S3 object created by .get_curves() expected")
  }

  attr(mroc_curves, "mroc_curves") <- TRUE
  mroc_curves
}

# Validate 'mprc_curves' object generated by .get_curves()
.validate.mprc_curves <- function(mprc_curves) {
  # Need to validate only once
  if (class(mprc_curves) == "mprc_curves" && attr(mprc_curves, "validated")) {
    return(mprc_curves)
  }

  # Check mprc_curves
  if (class(mprc_curves) != "mprc_curves") {
    stop("'mroc_curves' S3 object created by .get_curves() expected")
  }

  attr(mprc_curves, "mroc_curves") <- TRUE
  mprc_curves
}

# Validate 'mcurves' object generated by evalmulti()
.validate.mcurves <- function(mcurves) {
  # Need to validate only once
  if (class(mcurves) == "mcurves" && attr(mcurves, "validated")) {
    return(mcurves)
  }

  # Check mcurves
  if (class(mcurves) != "mcurves") {
    stop("'mcurves' S3 object created by evalmulti() expected")
  }

  vfunc <- function(s) {
    .validate(mcurves[["mcurves"]][[s]])
  }
  mapply(vfunc, seq_along(mcurves[["mcurves"]]))

  attr(mcurves, "mcurves") <- TRUE
  mcurves
}

