#' Plot ROC and Precision-Recall curves of a single model
#'
#' The \code{plot} function plots ROC and Precion-Recall curves.
#'
#' @param x \code{sscurves} object generated by
#'   \code{\link{evalmod}}.
#'
#' @param curvetype a character vector with the following curve types.
#'   \itemize{
#'     \item "ROC"
#'     \item "PRC"
#'     \item c("ROC", "PRC")
#'   }
#'
#' @param ... Not used by this method.
#'
#' @return The \code{plot} function shows a plot and returns NULL.
#'
#' @seealso \code{\link{evalmod}} for generating \code{sscurves}.
#'   \code{\link{autoplot.sscurves}} for plotting curves with
#'   \code{\link[ggplot2]{ggplot2}}.
#'
#' @examples
#'
#' ## Load a dataset with 10 positives and 10 negatives
#' data(P10N10)
#'
#' ## Generate an sscurve object
#' curves <- evalmod(scores = P10N10$scores, labels = P10N10$labels)
#'
#' ## Plot both ROC and Precision-Recall curves
#' plot(curves)
#'
#' ## Plot a ROC curve
#' readline("Press <Enter> to continue...")
#' plot(curves, curvetype = "ROC")
#'
#' ## Plot a Precision-Recall curve
#' readline("Press <Enter> to continue...")
#' plot(curves, curvetype = "PRC")
#'
#' ## Create sample datasets with 100 positives and 100 negatives
#' samps <- create_sim_samples(1, 100, 100, "all")
#' mdat <- mmdata(samps[["scores"]], samps[["labels"]],
#'                modnames = samps[["modnames"]],
#'                dsids = samps[["dsids"]])
#'
#' ## Generate an mscurve object
#' curves <- evalmod(mdat)
#'
#' ## Plot both ROC and Precision-Recall curves
#' plot(curves)
#'
#' ## Plot a ROC curve
#' plot(curves, curvetype = "ROC")
#'
#' ## Plot a Precision-Recall curve
#' plot(curves, curvetype = "PRC")
#'
#' ## Hide the legend
#' plot(curves, show_legend = FALSE)
#'
#' ## Prepare input data
#' samps <- create_sim_samples(10, 100, 100, "poor_er")
#' mdat <- mmdata(samps[["scores"]], samps[["labels"]],
#'                modnames = samps[["modnames"]],
#'                dsids = samps[["dsids"]])
#'
#' ## Generate an mscurve object
#' curves <- evalmod(mdat)
#'
#' ## Plot both ROC and Precision-Recall curves
#' plot(curves)
#'
#' ## Plot a ROC curve
#' plot(curves, curvetype = "ROC")
#'
#' ## Plot a Precision-Recall curve
#' plot(curves, curvetype = "PRC")
#'
#' ## Prepare input data
#' samps <- create_sim_samples(10, 100, 100, "all")
#' mdat <- mmdata(samps[["scores"]], samps[["labels"]],
#'                modnames = samps[["modnames"]],
#'                dsids = samps[["dsids"]])
#'
#' ## Generate an mscurve object
#' curves <- evalmod(mdat)
#'
#' ## Plot both ROC and Precision-Recall curves
#' plot(curves)
#'
#' ## Plot a ROC curve
#' plot(curves, curvetype = "ROC")
#'
#' ## Plot a Precision-Recall curve
#' plot(curves, curvetype = "PRC")
#' @name plot
NULL

#
# Plot ROC and Precision-Recall
#
.plot_multi <- function(x, curvetype = c("ROC", "PRC"), type = "l",
                        show_ci = FALSE, all_curves = TRUE, add_np_nn = TRUE,
                        show_legend = FALSE, ...) {

  # === Validate input arguments ===
  .check_show_legend(show_legend)
  .validate(x)
  .check_curvetype(curvetype)

  # === Create a plot ===
  show_legend2 <- show_legend
  if (length(curvetype) > 1) {
    .set_layout(length(curvetype), show_legend)
    on.exit(layout(1), add = TRUE)
    show_legend2 <- FALSE
  }

  for (ct in curvetype) {
    .plot_single(x, ct, type = type, show_ci = show_ci,
                 all_curves = all_curves, add_np_nn = add_np_nn,
                 show_legend = show_legend2, ...)
  }

  if (length(curvetype) > 1) {
    .show_legend(x, show_legend)
  }
}

#
# Set layout
#
.set_layout <- function(ctype_len, show_legend) {

  if (ctype_len == 1) {
    nrow1 <- 2
    ncol1 <- 1
    mat1 <- c(1, 2)
    mat2 <- c(1)
    heights = c(0.85, 0.15)
  } else  if (ctype_len == 2) {
    nrow1 <- 2
    ncol1 <- 2
    mat1 <- c(1, 2, 3, 3)
    mat2 <- c(1, 2)
    heights = c(0.85, 0.15)
  } else if (ctype_len == 3) {
    nrow1 <- 2
    ncol1 <- 3
    mat1 <- c(1, 2, 3, 4, 4, 4)
    mat2 <- c(1, 2, 3)
    heights = c(0.85, 0.15)
  } else if (ctype_len == 4) {
    nrow1 <- 3
    ncol1 <- 2
    mat1 <- c(1, 2, 3, 4, 5, 5)
    mat2 <- c(1, 2, 3, 4)
    heights = c(0.425, 0.425, 0.15)
  } else if (ctype_len > 4) {
    nrow1 <- 3
    ncol1 <- 3
    mat1 <- c(1, 2, 3, 4, 5, 6, 7, 7, 7)
    mat2 <- c(1, 2, 3, 4, 5, 6)
    heights = c(0.425, 0.425, 0.15)
  }

  if (show_legend) {
    m <- matrix(mat1, nrow = nrow1, ncol = ncol1, byrow = TRUE)
    layout(mat = m, heights = heights)
  } else {
    m <- matrix(mat2, nrow = nrow1 - 1, ncol = ncol1)
    layout(mat = m)
  }
}

#
# matplot wrapper
#
.matplot_wrapper <- function(obj, type, curvetype, main, xlab, ylab) {

  # === Validate input arguments ===
  .validate(obj[[curvetype]])

  # === Create line colours ===
  model_type <- attr(obj, "model_type")

  if (model_type == "single") {
    line_col <- "black"
  } else {
    line_col <- .make_multi_colors(obj)
  }

  # === Create a plot ===
  mats <- .make_matplot_mats(obj[[curvetype]])
  if (type == "l" || type == "p") {
    ltype = type
  }

  matplot(mats[["x"]], mats[["y"]], type = "l", lty = 1,
          col = line_col,
          main = main, xlab = xlab, ylab = ylab,
          ylim = c(0, 1), xlim = c(0, 1))
}

#
# Make matrices for matplot
#
.make_matplot_mats <- function(obj) {
  ncol <- length(obj)

  max_nrow <- max(unlist(lapply(obj, function(o) length(o[["x"]]))))

  x <- matrix(as.double(NA), nrow = max_nrow, ncol = ncol)
  y <- matrix(as.double(NA), nrow = max_nrow, ncol = ncol)

  for (i in seq_along(obj)) {
    x[1:length(obj[[i]][["x"]]), i] <- obj[[i]][["x"]]
    y[1:length(obj[[i]][["y"]]), i] <- obj[[i]][["y"]]
  }

  list(x = x, y = y)
}

#
# Make colours for multiple models and multiple datasets
#
.make_multi_colors <- function(obj) {
  uniq_modnames <- attr(obj, "uniq_modnames")
  modnames <- attr(obj, "data_info")[["modnames"]]

  uniq_col <- rainbow(length(uniq_modnames))
  modnams_idx <- as.numeric(factor(modnames, levels = uniq_modnames))
  unlist(lapply(seq_along(modnames), function(i) uniq_col[modnams_idx[i]]))
}

#
# Plot average line with CI
#
.plot_avg <- function(obj, type, curvetype, main, xlab, ylab, show_ci) {
  # === Create a plot ===
  avgcurves <- attr(obj[[curvetype]], "avgcurves")

  plot(1, type = "l", main = main, xlab = xlab, ylab = ylab,
       ylim = c(0, 1), xlim = c(0, 1))

  if (length(avgcurves) == 1) {
    lcols <- "blue"
  } else {
    lcols <- rainbow(length(avgcurves))
  }

  for (i in 1:length(avgcurves)) {
    .add_curve_with_ci(avgcurves, i, "grey", lcols[i], show_ci)
  }
}

#
# Add a curve with CI
#
.add_curve_with_ci <- function(avgcurves, idx, pcol, lcol, show_ci) {
  x <- avgcurves[[idx]][["x"]]
  y <- avgcurves[[idx]][["y_avg"]]

  if (show_ci) {
    ymin <- avgcurves[[idx]][["y_ci_l"]]
    ymax <- avgcurves[[idx]][["y_ci_h"]]

    g <- col2rgb(pcol)
    polygon(c(x, rev(x)), c(ymin, rev(ymax)), border = FALSE,
            col = rgb(g[1], g[2], g[3], 180, maxColorValue = 255))
  }

  b <- col2rgb(lcol)
  lines(x, y, col = rgb(b[1], b[2], b[3], 200, maxColorValue = 255))
}

#
# Plot ROC or Precision-Recall
#
.plot_single <- function(x, curvetype, type = type, show_ci = FALSE,
                         all_curves = FALSE, add_np_nn = TRUE,
                         show_legend = TRUE, ...) {

  tlist <- .get_titiles(curvetype)
  main <- tlist[["main"]]

  if (add_np_nn) {
    np <- attr(x[[tlist[["ctype"]]]][[1]], "np")
    nn <- attr(x[[tlist[["ctype"]]]][[1]], "nn")
    main <- paste0(main, " - P: ", np, ", N: ", nn)
  }

  old_pty <- par(pty = "s")
  on.exit(par(old_pty), add = TRUE)

  if (show_legend) {
    .set_layout(1, show_legend)
    on.exit(layout(1), add = TRUE)
  }

  # === Create a plot ===
  if (all_curves) {
    .matplot_wrapper(x, type, tlist[["ctype"]], main, tlist[["xlab"]],
                     tlist[["ylab"]])
  } else {
    .plot_avg(x, type, tlist[["ctype"]], main, tlist[["xlab"]],
              tlist[["ylab"]], show_ci)
  }

  if (curvetype == "ROC") {
    abline(a = 0, b = 1, col = "grey", lty = 3)

  } else if (curvetype == "PRC" && add_np_nn) {
    abline(h = np / (np + nn), col = "grey", lty = 3)
  }

  .show_legend(x, show_legend)
}

#
# Get title and subtitles
#
.get_titiles <- function(curvetype) {
  tlist = list()

  if (curvetype == "ROC") {
    tlist[["main"]] <- "ROC"
    tlist[["xlab"]] <- "1 - Specificity"
    tlist[["ylab"]] <- "Sensitivity"
    tlist[["ctype"]] <- "rocs"
  } else if (curvetype == "PRC") {
    tlist[["main"]] <- "Precision-Recall"
    tlist[["xlab"]] <- "Recall"
    tlist[["ylab"]] <- "Precision"
    tlist[["ctype"]] <- "prcs"
  } else {
    mnames <- list(error = "err", accuracy = "acc", specificity = "sp",
                   sensitivity = "sn", precision = "prec")
    main <- paste0(toupper(substring(curvetype, 1, 1)), substring(curvetype,2))
    tlist[["main"]] <- main
    tlist[["xlab"]] <- "threshold"
    tlist[["ylab"]] <- curvetype
    tlist[["ctype"]] <- mnames[[curvetype]]
  }

  tlist
}

#
# Show legend
#
.show_legend <- function(obj, show_legend, gnames = "modnames") {
  if (show_legend) {
    old_mar <- par(mar = c(0, 0, 0, 0))
    on.exit(par(old_mar), add = TRUE)
    old_pty <- par(pty = "m")
    on.exit(par(old_pty), add = TRUE)

    gnames <- attr(obj, paste0("uniq_", gnames))
    plot(1, type = "n", axes = FALSE, xlab = "", ylab = "")
    legend(x = "top", lty = 1,
           legend = gnames,
           col = rainbow(length(gnames)),
           horiz = TRUE)
  }
}
