#' Convert sscurves to a data frame for ggplot2.
#'
#' \code{fortify} converts an \code{sscurves} object generated by
#'   \code{\link{evalmod}} to a data frame for
#'   \code{\link[ggplot2]{ggplot2}}.
#'
#' @param model \code{sscurves} object generated by
#'   \code{\link{evalmod}}.
#'
#' @param ... Not used by this method.
#'
#' @return The \code{fortify} function retruns a data frame for
#'   \code{\link[ggplot2]{ggplot2}}.
#'
#' @seealso \code{\link{evalmod}} for generating \code{sscurves}.
#'  \code{\link{autoplot.sscurves}} for plotting curves.
#'
#' @examples
#'
#' ## Load ggplot2
#' library(ggplot2)
#'
#' ## Load a dataset with 10 positives and 10 negatives
#' data(P10N10)
#'
#' ## Convert sscurve object to a data frame
#' curves <- evalmod(scores = P10N10$scores, labels = P10N10$labels)
#' df <- fortify(curves)
#'
#' ## Fortified data frame can be used for plotting a ROC curve
#' p_roc <- ggplot(subset(df, group == "ROC"), aes(x = x, y = y))
#' p_roc <- p_roc + geom_line()
#' p_roc
#'
#' ## Fortified data frame can be used for plotting a Precision-Recall curve
#' p_prc <- ggplot(subset(df, group == "PRC"), aes(x = x, y = y))
#' p_prc <- p_prc + geom_line()
#' p_prc
#'
#' ## Create sample datasets with 100 positives and 100 negatives
#' samps <- create_sim_samples(1, 100, 100, "all")
#' mdat <- mmdata(samps[["scores"]], samps[["labels"]],
#'                modnames = samps[["modnames"]],
#'                dsids = samps[["dsids"]])
#'
#' ## Convert sscurve object to a data frame
#' curves <- evalmod(scores = P10N10$scores, labels = P10N10$labels)
#' df <- fortify(curves)
#'
#' ## Fortified data frame can be used for plotting a ROC curve
#' df_roc <- subset(df, group == "ROC")
#' p_roc <- ggplot(df_roc, aes(x = x, y = y, color = modname))
#' p_roc <- p_roc + geom_line()
#' p_roc
#'
#' ## Fortified data frame can be used for plotting a Precision-Recall curve
#' df_prc <- subset(df, group == "PRC")
#' p_prc <- ggplot(df_prc, aes(x = x, y = y, color = modname))
#' p_prc <- p_prc + geom_line()
#' p_prc
#'
#' ## Prepare input data
#' samps <- create_sim_samples(10, 100, 100, "poor_er")
#' mdat <- mmdata(samps[["scores"]], samps[["labels"]],
#'                modnames = samps[["modnames"]],
#'                dsids = samps[["dsids"]])
#'
#' ## Convert sscurve object to a data frame
#' curves <- evalmod(mdat)
#' df <- fortify(curves)
#'
#' ## Fortified data frame can be used for plotting a ROC curve
#' df_roc <- subset(df, group == "ROC")
#' p_roc <- ggplot(df_roc, aes(x = x, y = y, ymin = ymin, ymax = ymax))
#' p_roc <- p_roc + geom_smooth(stat = "identity")
#' p_roc
#'
#' ## Fortified data frame can be used for plotting a Precision-Recall curve
#' df_prc <- subset(df, group == "PRC")
#' p_prc <- ggplot(df_roc, aes(x = x, y = y, ymin = ymin, ymax = ymax))
#' p_prc <- p_roc + geom_smooth(stat = "identity")
#' p_prc
#'
#' ## Prepare input data
#' samps <- create_sim_samples(10, 100, 100, "all")
#' mdat <- mmdata(samps[["scores"]], samps[["labels"]],
#'                modnames = samps[["modnames"]],
#'                dsids = samps[["dsids"]])
#'
#' ## Convert sscurve object to a data frame
#' curves <- evalmods_m(mdat)
#' df <- fortify(curves)
#'
#' ## Fortified data frame can be used for plotting a ROC curve
#' df_roc <- subset(df, group == "ROC")
#' p_roc <- ggplot(df_roc, aes(x = x, y = y, ymin = ymin, ymax = ymax,
#'                             color = modname))
#' p_roc <- p_roc + geom_smooth(stat = "identity")
#' p_roc
#'
#' ## Fortified data frame can be used for plotting a Precision-Recall curve
#' df_prc <- subset(df, group == "PRC")
#' p_prc <- ggplot(df_roc, aes(x = x, y = y, ymin = ymin, ymax = ymax,
#'                             color = modname))
#' p_prc <- p_roc + geom_smooth(stat = "identity")
#' p_prc
#'
#'
#'
#' ## Load ggplot2
#' library(ggplot2)
#'
#' ## Load a dataset with 10 positives and 10 negatives
#' data(P10N10)
#'
#' ## Convert sscurve object to a data frame
#' curves <- evalmod(mode = "basic", scores = P10N10$scores,
#'                   labels = P10N10$labels)
#' df <- fortify(curves)
#'
#' ## Create sample datasets with 100 positives and 100 negatives
#' samps <- create_sim_samples(1, 100, 100, "all")
#' mdat <- mmdata(samps[["scores"]], samps[["labels"]],
#'                modnames = samps[["modnames"]],
#'                dsids = samps[["dsids"]])
#'
#' ## Convert sscurve object to a data frame
#' points <- evalmod(mode = "basic", scores = P10N10$scores,
#'                   labels = P10N10$labels)
#' df <- fortify(points)
#'
#' ## Prepare input data
#' samps <- create_sim_samples(10, 100, 100, "poor_er")
#' mdat <- mmdata(samps[["scores"]], samps[["labels"]],
#'                modnames = samps[["modnames"]],
#'                dsids = samps[["dsids"]])
#'
#' ## Convert sscurve object to a data frame
#' points <- evalmod_m(mdat)
#' df <- fortify(points)
#'
#' ## Prepare input data
#' samps <- create_sim_samples(10, 100, 100, "all")
#' mdat <- mmdata(samps[["scores"]], samps[["labels"]],
#'                modnames = samps[["modnames"]],
#'                dsids = samps[["dsids"]])
#'
#' ## Convert sscurve object to a data frame
#' points <- evalmod(mdat)
#' df <- fortify(points)
#'
#' @name fortify
NULL

#
# Make a dataframe for plotting
#
.fortify_common <- function(obj, mode = "rocprc", raw_curves = TRUE, ...) {
  # === Check package availability  ===
  .load_ggplot2()

  # === Validate input arguments ===
  .validate(obj)

  # Prepare variables
  uniq_modnames <- attr(obj, "uniq_modnames")
  uniq_dsids <- attr(obj, "uniq_dsids")
  modnames <- attr(obj, "data_info")[["modnames"]]
  dsids <- attr(obj, "data_info")[["dsids"]]

  if (mode == "rocprc") {
    curvetype_names <- list(ROC = "rocs", PRC = "prcs")
  } else if (mode == "basic") {
    curvetype_names <- list(error = "err", accuracy = "acc",
                            specificity = "sp", sensitivity = "sn",
                            precision = "prec")
  }

  # Make dsis-modname pairs
  i <- 1
  dsid_modnames <- vector(mode = "character",
                          length = length(uniq_modnames) * length(uniq_dsids))
  for (modname in uniq_modnames) {
    for (dsid in uniq_dsids) {
      dsid_modnames[i] <- paste(modname, dsid, sep = ":")
      i <- i + 1
    }
  }

  # Create curve_df
  if (raw_curves) {
    curve_df <- .fortify_curve(obj, uniq_modnames, uniq_dsids, modnames,
                               dsids, dsid_modnames, curvetype_names)
  } else {
    curve_df <- .fortify_curve_avg(obj, uniq_modnames, uniq_dsids, modnames,
                                   dsids, dsid_modnames, curvetype_names)
  }

  curve_df
}

#
# Make a dataframe for plotting with regular curves
#
.fortify_curve <- function(obj, uniq_modnames, uniq_dsids, modnames, dsids,
                           dsid_modnames, curvetype_names) {

  curve_df <- NULL
  for (curvetype in names(curvetype_names)) {
    curves <- obj[[curvetype_names[[curvetype]]]]
    for (i in seq_along(curves)) {
      x <- curves[[i]][["x"]]
      y <- curves[[i]][["y"]]

      modname <- factor(rep(modnames[i], length(x)), levels = uniq_modnames)
      dsid <- factor(rep(dsids[i], length(x)), levels = uniq_dsids)
      dsid_modname <- factor(rep(paste(modnames[i], dsids[i], sep = ":"),
                                 length(x)),
                             levels = dsid_modnames)
      curvename <- factor(rep(curvetype, length(x)),
                          levels = names(curvetype_names))
      curve_df <- rbind(curve_df, data.frame(x = x, y = y, modname = modname,
                                             dsid = dsid,
                                             dsid_modname = dsid_modname,
                                             curvetype = curvename))
    }
  }

  curve_df
}

#
# Make a dataframe for plotting with average curves
#
.fortify_curve_avg <- function(obj, uniq_modnames, uniq_dsids, modnames, dsids,
                               dsid_modnames, curvetype_names) {

  grp_avg <- attr(obj, "grp_avg")
  curve_df <- NULL
  for (curvetype in names(curvetype_names)) {
    avgcurves <- grp_avg[[curvetype_names[[curvetype]]]]

    for (i in seq_along(avgcurves)) {
      x <- avgcurves[[i]][["x"]]
      y <- avgcurves[[i]][["y_avg"]]
      ymin <- avgcurves[[i]][["y_ci_l"]]
      ymax <- avgcurves[[i]][["y_ci_h"]]

      modname <- factor(rep(uniq_modnames[i], length(x)),
                        levels = uniq_modnames)
      curvename <- factor(rep(curvetype, length(x)),
                          levels = names(curvetype_names))
      curve_df <- rbind(curve_df, data.frame(x = x, y = y,
                                             ymin = ymin, ymax = ymax,
                                             modname = modname,
                                             curvetype = curvename))
    }
  }

  curve_df
}
