#' Plot score distibutions by rank.
#'
#' \code{autoplot} takes a \code{fmdat} object generated by
#' \code{\link{reformat_data}} and plot score distribution by rank.
#' \code{autoplot} requires \code{\link[ggplot2]{ggplot2}}.
#'
#' @param object \code{fmdat} object generated by
#'   \code{\link{reformat_data}}.
#' @param ... Other arguments (ignored).
#' @return \code{autoplot} automatically shows a plot or returns
#'   a \code{ggplot} object.
#'
#' @examples
#' library(ggplot2)
#' data(B500)
#' fmdat <- reformat_data(B500$good_er_scores, B500$labels)
#' autoplot(fmdat)
autoplot.fmdat <- function(object, ...) {
  df <- .prepare_autoplot(object)

  # === Create a ggplot object ===
  p <- ggplot2::ggplot(df, aes(x = x, y = y, color = x))
  p <- p + ggplot2::geom_jitter()
  p <- p + ggplot2::coord_flip()
  p <- .geom_basic(p, "Score distributions by rank", NULL, "rank")
  p <- p + ggplot2::theme(legend.position = "none")

  p
}

#' Plot TPs, FNs, FPs, TNs by threshold IDs.
#'
#' \code{autoplot} takes a \code{cmats} object generated by
#' \code{\link{create_confmats}} and plot TPs, FNs, FPs, TNs by threshold IDs.
#' Threshold IDs are automatically generated.
#' \code{autoplot} requires \code{\link[ggplot2]{ggplot2}}.
#'
#' @param object \code{cmats} object generated by
#'   \code{\link{create_confmats}}.
#' @param ... Further arguments (ignored).
#' @return \code{autoplot} automatically shows a plot or returns
#'   a \code{ggplot} object.
#'
#' @examples
#' library(ggplot2)
#'
#' data(B500)
#' cmat <- create_confmats(pscores = B500$good_er_scores,
#'                         olabs = B500$labels)
#' autoplot(cmat)
autoplot.cmats <- function(object, ...) {
  df <- .prepare_autoplot(object)

  # === Create a ggplot object ===
  p <- ggplot2::ggplot(df, aes(x = x, y = y, color = group))
  p <- .geom_line_wrapper(p, "TPs, FNs, FPs, and TNs by threshold IDs",
                          "threshold ID", "count")
  p <- p + ggplot2::theme(legend.title = element_blank())

  p
}

#' Plot basic evaluation measures by threshold IDs.
#'
#' \code{autoplot} takes \code{pevals} object generated by
#' \code{\link{calc_measures}} and plot error-rate, accuracy, specificity,
#'   sensitivity, and precision values by threshold IDs.
#' Threshold IDs are automatically generated.
#' \code{autoplot} requires \code{\link[ggplot2]{ggplot2}}.
#'
#' @param object \code{pevals} object generated by
#'   \code{\link{calc_measures}}.
#' @param ... Other arguments (ignored).
#' @return \code{autoplot} automatically shows a plot or returns
#'   a \code{ggplot} object.
#'
#' @examples
#' library(ggplot2)
#'
#' data(B500)
#' pevals <- calc_measures(pscores = B500$good_er_scores,
#'                         olabs = B500$labels)
#' autoplot(pevals)
autoplot.pevals <- function(object, ...) {
  df <- .prepare_autoplot(object)

  # === Create a ggplot object ===
  p <- ggplot2::ggplot(df, aes(x = x, y = y))
  p <- p + ggplot2::facet_wrap(~ group, ncol = 2)

  p <- .geom_line_wrapper(p, "Evaluation measures by threshold IDs",
                          "threshold ID", "evaluation value")

  p
}

#' Plot a ROC curve.
#'
#' \code{autoplot} takes \code{roc_curve} object generated by
#' \code{\link{create_roc}} and plot a ROC curve.
#' \code{autoplot} requires \code{\link[ggplot2]{ggplot2}}.
#'
#' @param object \code{roc_curve} object generated by
#'   \code{\link{create_roc}}.
#' @param ... Other arguments (ignored).
#' @return \code{autoplot} automatically shows a plot or returns
#'   a \code{ggplot} object.
#'
#' @examples
#' library(ggplot2)
#'
#' data(B500)
#' roc_curve <- create_roc(pscores = B500$good_er_scores,
#'                         olabs = B500$labels)
#' autoplot(roc_curve)
autoplot.roc_curve <- function(object, ...) {
  df <- .prepare_autoplot(object)

  # === Create a ggplot object ===
  p <- ggplot2::ggplot(df, aes(x = x, y = y))
  p <- .geom_roc_line_wrapper(p, object)

  p
}

#' Plot a Precision-Recall curve.
#'
#' \code{autoplot} takes \code{prc_curve} object generated by
#' \code{\link{create_prc}} and plot a Precision-Recall curve.
#' \code{autoplot} requires \code{\link[ggplot2]{ggplot2}}.
#'
#' @param object \code{prc_curve} object generated by
#'   \code{\link{create_prc}}.
#' @param ... Other arguments (ignored).
#' @return \code{autoplot} automatically shows a plot or returns
#'   a \code{ggplot} object.
#'
#' @examples
#' library(ggplot2)
#'
#' data(B500)
#' prc_curve <- create_prc(pscores = B500$good_er_scores,
#'                         olabs = B500$labels)
#' autoplot(prc_curve)
autoplot.prc_curve <- function(object, ...) {
  df <- .prepare_autoplot(object)

  # === Create a ggplot object ===
  p <- ggplot2::ggplot(df, aes(x = x, y = y))
  p <- .geom_prc_line_wrapper(p, object)

  p
}

#' Plot ROC and Precision-Recall curves.
#'
#' \code{autoplot} takes \code{curves} object generated by
#' \code{\link{evalmod}} or \code{\link{create_curves}}
#'  and plot ROC and Precion-Recall curves.
#' \code{autoplot} requires \code{\link[ggplot2]{ggplot2}} and
#' \code{\link[gridExtra]{grid.arrange}}.
#'
#' @param object \code{curves} object generated by
#'   \code{\link{evalmod}} or \code{\link{create_curves}}.
#' @param ... Other arguments (ignored).
#' @return \code{autoplot} automatically shows a plot or returns
#'   a \code{ggplot} object.
#'
#' @examples
#' library(ggplot2)
#' library(gridExtra)
#'
#' data(B500)
#' curves <- create_curves(pscores = B500$good_er_scores,
#'                         olabs = B500$labels)
#' autoplot(curves)
autoplot.curves <- function(object, curvetype = c("ROC", "PRC"), ...) {
  # === Check package availability  ===
  .load_ggplot2()
  .load_gridExtra()
  .validate(object)
  .check_curvetype(curvetype)

  # === Create a ggplot object for ROC&PRC, ROC, or PRC ===
  if ("ROC" %in% curvetype) {
    p_roc <- ggplot2::autoplot(object[["roc"]])
  }

  if ("PRC" %in% curvetype) {
    p_prc <- ggplot2::autoplot(object[["prc"]])
  }

  if ("ROC" %in% curvetype && "PRC" %in% curvetype) {
    gridExtra::grid.arrange(p_roc, p_prc, ncol=2)
  } else if ("PRC" %in% curvetype) {
    p_prc
  } else if ("ROC" %in% curvetype) {
    p_roc
  }
}

# Plot ROC curves for multiple models
autoplot.mroc_curves <- function(object, ...) {
  df <- .prepare_autoplot(object)

  # === Create a ggplot object ===
  p <- ggplot2::ggplot(df, aes(x = x, y = y, color = model_name))
  p <- .geom_roc_line_wrapper(p, object[["curves"]][[1]])
}

# Plot Precision-Recall curves for multiple models
autoplot.mprc_curves <- function(object, ...) {
  df <- .prepare_autoplot(object)

  # === Create a ggplot object ===
  p <- ggplot2::ggplot(df, aes(x = x, y = y, color = model_name))
  p <- .geom_prc_line_wrapper(p, object[["curves"]][[1]])

  p
}

#' Plot ROC and Precision-Recall curves for multiple models.
#'
#' \code{autoplot} takes \code{mcurves} object generated by
#' \code{\link{evalmulti}} and plot ROC and Precion-Recall curves.
#' \code{autoplot} requires \code{\link[ggplot2]{ggplot2}} and
#' \code{\link[gridExtra]{grid.arrange}}.
#'
#' @param object \code{mcurves} object generated by
#'   \code{\link{evalmulti}}.
#' @param ... Other arguments (ignored).
#' @return \code{autoplot} automatically shows a plot or returns
#'   a \code{ggplot} object.
#'
#' @examples
#' library(ggplot2)
#' library(gridExtra)
#'
#' s1 <- c(1, 2, 3, 4)
#' s2 <- c(5, 6, 7, 8)
#' s3 <- c(2, 4, 6, 8)
#' mscores <- combine_scores(s1, s2, s3)
#'
#' l1 <- c(1, 0, 1, 1)
#' l2 <- c(1, 1, 0, 0)
#' l3 <- c(0, 1, 0, 1)
#' mobslabs <- combine_obslbs(l1, l2, l3)
#'
#' mfmdat <- reformat_mdata(mscores, mobslabs)
#'
#' mcurves <- evalmulti(mfmdat)
#' autoplot(mcurves)
autoplot.mcurves <- function(object, curvetype = c("ROC", "PRC"), ...) {
  # === Check package availability  ===
  .load_ggplot2()
  .load_grid()
  .load_gridExtra()
  .validate(object)
  .check_curvetype(curvetype)

  # === Create a ggplot object for ROC&PRC, ROC, or PRC ===
  if ("ROC" %in% curvetype) {
    p_roc <- ggplot2::autoplot(object[["mroc_curves"]])
  }

  if ("PRC" %in% curvetype) {
    p_prc <- ggplot2::autoplot(object[["mprc_curves"]])
  }

  if ("ROC" %in% curvetype && "PRC" %in% curvetype) {
    .grid_arrange_shared_legend(p_roc, p_prc)
  } else if ("PRC" %in% curvetype) {
    p_prc
  } else if ("ROC" %in% curvetype) {
    p_roc
  }
}
