#' Plot ROC and Precision-Recall curves
#'
#' The \code{autoplot} function plots ROC and Precion-Recall curves
#'   by using \code{ggplot2} instead of the general R plot.
#'
#' @param object \code{sscurves} object generated by
#'   \code{\link{evalmod}}.
#'
#' @param curvetype a character vector with the following curve types
#'   \describe{
#'     \item{"ROC"}{ROC curve}
#'     \item{"PRC"}{Precision-Recall curve}
#'     \item{c("ROC", "PRC")}{ROC and Precision-Recall curves}
#'   }
#'
#' @param ret_grob A logical value to indicate whether
#'   \code{autoplot} returns a frame grob object.
#'
#' @param ... Not used by this method.
#'
#' @return The \code{autoplot} function returns a \code{ggplot} object
#'   for a single-panel plot and a frame-grob object for a multiple-panel plot.
#'
#' @seealso \code{\link{evalmod}} for generating \code{sscurves},
#'  \code{mscurves}, \code{smcurves}, and \code{mmcurves}.
#'  \code{\link{fortify}} for converting a curve object to a list.
#'  \code{\link{plot}} for plotting the same curves
#'   with the general R plot.
#'
#' @examples
#'
#' ## Load libraries
#' library(ggplot2)
#' library(grid)
#' library(gridExtra)
#'
#' ## Load a dataset with 10 positives and 10 negatives
#' data(P10N10)
#'
#' ## Generate an sscurve object
#' curves <- evalmod(scores = P10N10$scores, labels = P10N10$labels)
#'
#' ## Plot both ROC and Precision-Recall curves
#' autoplot(curves)
#'
#' ## Plot a ROC curve
#' autoplot(curves, curvetype = "ROC")
#'
#' ## Plot a Precision-Recall curve
#' pp1 <- autoplot(curves, curvetype = "PRC")
#' pp1
#'
#' ## autoplot returns a grob object.
#' pp2 <- autoplot(curves, ret_grob = TRUE)
#' plot.new()
#' grid.draw(pp2)
#'
#' ## Create sample datasets with 100 positives and 100 negatives
#' samps <- create_sim_samples(1, 100, 100, "all")
#' mdat <- mmdata(samps[["scores"]], samps[["labels"]],
#'                modnames = samps[["modnames"]],
#'                dsids = samps[["dsids"]])
#'
#' ## Generate an mscurve object
#' curves <- evalmod(mdat)
#'
#' ## Plot both ROC and Precision-Recall curves
#' autoplot(curves)
#'
#' ## Prepare input data
#' samps <- create_sim_samples(10, 100, 100, "poor_er")
#' mdat <- mmdata(samps[["scores"]], samps[["labels"]],
#'                modnames = samps[["modnames"]],
#'                dsids = samps[["dsids"]])
#'
#' ## Generate an smcurve object
#' curves <- evalmod(mdat)
#'
#' ## Plot both ROC and Precision-Recall curves
#' autoplot(curves)
#'
#'
#' ## Prepare input data
#' samps <- create_sim_samples(10, 100, 100, "all")
#' mdat <- mmdata(samps[["scores"]], samps[["labels"]],
#'                modnames = samps[["modnames"]],
#'                dsids = samps[["dsids"]])
#'
#' ## Generate an mscurve object
#' curves <- evalmod(mdat)
#'
#' ## Plot both ROC and Precision-Recall curves
#' autoplot(curves)
#'
#' @name autoplot
NULL


#' @rdname autoplot
#' @export
autoplot.sscurves <- function(object, curvetype = c("ROC", "PRC"),
                              ret_grob = FALSE, ...) {

  .autoplot_multi(object, curvetype = curvetype, show_ci = FALSE,
                  all_curves = TRUE, show_legend = FALSE, add_np_nn = TRUE,
                  ret_grob = ret_grob)

}

#' @rdname autoplot
#' @export
autoplot.mscurves <- function(object, curvetype = c("ROC", "PRC"),
                              show_legend = TRUE, ret_grob = FALSE, ...) {

  .autoplot_multi(object, curvetype = curvetype, show_ci = FALSE,
                  all_curves = TRUE, show_legend = TRUE, add_np_nn = TRUE,
                  ret_grob = ret_grob)
}

#' @rdname autoplot
#' @export
autoplot.smcurves <- function(object, curvetype = c("ROC", "PRC"),
                              show_ci = TRUE, all_curves = FALSE,
                              ret_grob = FALSE, ...) {

  .autoplot_multi(object, curvetype = curvetype, show_ci = show_ci,
                  all_curves = all_curves, show_legend = FALSE, add_np_nn = TRUE,
                  ret_grob = ret_grob)
}

#' @rdname autoplot
#' @export
autoplot.mmcurves <- function(object, curvetype = c("ROC", "PRC"),
                              show_ci = FALSE, all_curves = FALSE,
                              show_legend = TRUE, ret_grob = FALSE, ...) {

  .autoplot_multi(object, curvetype = curvetype, show_ci = show_ci,
                  all_curves = all_curves, show_legend = show_legend,
                  add_np_nn = TRUE, ret_grob = ret_grob)
}
