#' Plot ROC and Precision-Recall curves for multiple models
#'
#' The \code{autoplot} function plots ROC and Precion-Recall curves.
#'
#' @param object \code{sscurves} object generated by
#'   \code{\link{evalmods}}.
#'
#' @param curvetype a character vector with the following curve types
#'   \describe{
#'     \item{"ROC"}{ROC curve}
#'     \item{"PRC"}{Precision-Recall curve}
#'     \item{c("ROC", "PRC")}{ROC and Precision-Recall curves}
#'   }
#'
#' @param show_legend A boolean value to indicate whether the legend is added.
#'
#' @param ret_grob A boolean value to indicate whether
#'   \code{autoplot} returns a frame grob object.
#'
#' @param ... Not used by this method.
#'
#' @return The \code{autoplot} function returns a \code{ggplot} object
#'   for a single plot and a frame grob object for multiple plots.
#'
#' @seealso \code{\link{evalmods}} for generating \code{mscurves}.
#'  \code{\link{fortify.mscurves}} for converting \code{mscurves} to list.
#'  \code{\link{plot.mscurves}} for plotting the same curves
#'   with the general R plot.
#'
#' @examples
#'
#' ## Load libraries
#' library(ggplot2)
#' library(grid)
#' library(gridExtra)
#'
#' ## Create sample datasets with 100 positives and 100 negatives
#' samps <- create_sim_samples(1, 100, 100, "all")
#' mdat <- mmdata(samps[["scores"]], samps[["labels"]],
#'                modnames = samps[["modnames"]],
#'                setids = samps[["setids"]])
#'
#' ## Generate an mscurve object
#' curves <- evalmods(mdat)
#'
#' ## Plot both ROC and Precision-Recall curves
#' autoplot(curves)
#'
#' ## Plot a ROC curve
#' autoplot(curves, curvetype = "ROC")
#'
#' ## Plot a Precision-Recall curve
#' pp1 <- autoplot(curves, curvetype = "PRC")
#' pp1
#'
#' ## Hide the legend
#' autoplot(curves, show_legend = FALSE)
#'
#' ## autoplot returns a grob object
#' pp2 <- autoplot(curves, ret_grob = TRUE)
#' plot.new()
#' grid.draw(pp2)
#'
#' @export
autoplot.mscurves <- function(object, curvetype = c("ROC", "PRC"),
                              show_legend = TRUE, ret_grob = FALSE, ...) {
  # === Check package availability  ===
  .load_ggplot2()
  .validate(object)
  .check_curvetype(curvetype)
  .check_show_legend(show_legend)
  .check_ret_grob(ret_grob)

  # === Create a ggplot object for ROC&PRC, ROC, or PRC ===
  if ("ROC" %in% curvetype) {
    p_roc <- ggplot2::autoplot(object[["rocs"]], show_legend = show_legend)
  }

  if ("PRC" %in% curvetype) {
    p_prc <- ggplot2::autoplot(object[["prcs"]], show_legend = show_legend)
  }

  if ("ROC" %in% curvetype && "PRC" %in% curvetype) {
    .combine_roc_prc(p_roc, p_prc, show_legend, ret_grob)
  } else if ("PRC" %in% curvetype) {
    p_prc
  } else if ("ROC" %in% curvetype) {
    p_roc
  }
}

#
# Plot ROC curves for multiple models
#
autoplot.msroc <- function(object, show_legend = TRUE, ...) {
  df <- .prepare_autoplot(object)

  # === Create a ggplot object ===
  p <- ggplot2::ggplot(df, ggplot2::aes(x = x, y = y, color = modname))
  p <- p + ggplot2::geom_line()
  p <- .geom_basic_roc(p, object[[1]], show_legend = show_legend)
}

#
# Plot Precision-Recall curves for multiple models
#
autoplot.msprc <- function(object, show_legend = TRUE, ...) {
  df <- .prepare_autoplot(object)

  # === Create a ggplot object ===
  p <- ggplot2::ggplot(df, ggplot2::aes(x = x, y = y, color = modname))
  p <- p + ggplot2::geom_line()
  p <- .geom_basic_prc(p, object[[1]], show_legend = show_legend)
}
