#' Plot ROC and Precision-Recall curves for multiple models with multiple datasets
#'
#' The \code{autoplot} function plots ROC and Precion-Recall curves.
#'
#' @param object \code{mmcurves} object generated by
#'   \code{\link{evalmods_m}}.
#'
#' @param curvetype a character vector with the following curve types
#'   \describe{
#'     \item{"ROC"}{ROC curve}
#'     \item{"PRC"}{Precision-Recall curve}
#'     \item{c("ROC", "PRC")}{ROC and Precision-Recall curves}
#'   }
#'
#' @param ret_grob A boolean value to indicate whether
#'   \code{autoplot} returns a frame grob object.
#'
#' @param ... Not used by this method.
#'
#' @return The \code{autoplot} function returns a \code{ggplot} object
#'   for a single plot and a frame grob object for multiple plots.
#'
#' @seealso \code{\link{evalmods_m}} for generating \code{smcurves}.
#'
#' @seealso \code{\link{evalmods_m}} for generating \code{smcurves}.
#'  \code{\link{fortify.smcurves}} for converting \code{smcurves} to list.
#'  \code{\link{plot.smcurves}} for plotting the same curves
#'   with the general R plot.
#'
#' @examples
#'
#' ## Load libraries
#' library(ggplot2)
#' library(grid)
#' library(gridExtra)
#'
#' ## Prepare input data
#' samps <- create_sim_samples(10, 100, 100, "all")
#' mdat <- mmdata(samps[["scores"]], samps[["labels"]],
#'                modnames = samps[["modnames"]],
#'                dsids = samps[["dsids"]])
#'
#' ## Generate an mscurve object
#' curves <- evalmod(mdat)
#'
#' ## Plot both ROC and Precision-Recall curves
#' autoplot(curves)
#'
#' ## Plot a ROC curve
#' autoplot(curves, curvetype = "ROC")
#'
#' ## Plot a Precision-Recall curve
#' pp1 <- autoplot(curves, curvetype = "PRC")
#' pp1
#'
#' ## autoplot returns a grob object.
#' pp2 <- autoplot(curves, ret_grob = TRUE)
#' plot.new()
#' grid.draw(pp2)
#'
#' @export
autoplot.mmcurves <- function(object, curvetype = c("ROC", "PRC"),
                              show_ci = FALSE, all_curves = FALSE,
                              show_legend = TRUE, ret_grob = FALSE, ...) {

  # === Check package availability  ===
  .load_ggplot2()
  .validate(object)
  .check_curvetype(curvetype)
  .check_ret_grob(ret_grob)

  # === Create a ggplot object for ROC&PRC, ROC, or PRC ===
  curve_df <- ggplot2::fortify(object, all_curves = all_curves, ...)

  if ("ROC" %in% curvetype) {
    p_roc <- .plot_single(object, curve_df = curve_df, curvetype = "ROC",
                          show_ci = show_ci, all_curves = all_curves,
                          show_legend = TRUE, add_np_nn = TRUE)
  }

  if ("PRC" %in% curvetype) {
    p_prc <- .plot_single(object, curve_df = curve_df, curvetype = "PRC",
                          show_ci = show_ci, all_curves = all_curves,
                          show_legend = TRUE, add_np_nn = TRUE)
  }

  if ("ROC" %in% curvetype && "PRC" %in% curvetype) {
    .combine_roc_prc(p_roc, p_prc, show_legend = show_legend,
                     ret_grob = ret_grob)
  } else if ("PRC" %in% curvetype) {
    p_prc
  } else if ("ROC" %in% curvetype) {
    p_roc
  }
}
