#' Plot score distibutions by rank.
#'
#' \code{autoplot} takes a \code{fmdat} object generated by
#' \code{\link{reformat_data}} and plot score distribution by rank.
#' \code{autoplot} requires \code{\link[ggplot2]{ggplot2}}.
#'
#' @param object \code{fmdat} object generated by
#'   \code{\link{reformat_data}}.
#' @param ... Other arguments (ignored).
#' @return \code{autoplot} automatically shows a plot or returns
#'   a \code{ggplot} object.
#'
#' @examples
#' library(ggplot2)
#' data(B500)
#' fmdat <- reformat_data(B500$good_er_scores, B500$labels)
#' autoplot(fmdat)
autoplot.fmdat <- function(object, ...) {
  df <- .prepare_autoplot(object)

  # === Create a ggplot object ===
  p <- ggplot2::ggplot(df, aes(x = x, y = y, color = x))
  p <- p + ggplot2::geom_jitter()
  p <- p + ggplot2::coord_flip()
  p <- .geom_basic(p, "Score distributions by rank", NULL, "rank")
  p <- p + ggplot2::theme(legend.position = "none")

  p
}

#' Plot TPs, FNs, FPs, TNs by threshold IDs.
#'
#' \code{autoplot} takes a \code{cmats} object generated by
#' \code{\link{create_confmats}} and plot TPs, FNs, FPs, TNs by threshold IDs.
#' Threshold IDs are automatically generated.
#' \code{autoplot} requires \code{\link[ggplot2]{ggplot2}}.
#'
#' @param object \code{cmats} object generated by
#'   \code{\link{create_confmats}}.
#' @param ... Further arguments (ignored).
#' @return \code{autoplot} automatically shows a plot or returns
#'   a \code{ggplot} object.
#'
#' @examples
#' library(ggplot2)
#'
#' data(B500)
#' cmat <- create_confmats(scores = B500$good_er_scores,
#'                         olabs = B500$labels)
#' autoplot(cmat)
autoplot.cmats <- function(object, ...) {
  df <- .prepare_autoplot(object)

  # === Create a ggplot object ===
  p <- ggplot2::ggplot(df, aes(x = x, y = y, color = group))
  p <- .geom_line_wrapper(p, "TPs, FNs, FPs, and TNs by threshold IDs",
                          "threshold ID", "count")
  p <- p + ggplot2::theme(legend.title = element_blank())

  p
}

#' Plot basic evaluation measures by threshold IDs.
#'
#' \code{autoplot} takes \code{pevals} object generated by
#' \code{\link{calc_measures}} and plot error-rate, accuracy, specificity,
#'   sensitivity, and precision values by threshold IDs.
#' Threshold IDs are automatically generated.
#' \code{autoplot} requires \code{\link[ggplot2]{ggplot2}}.
#'
#' @param object \code{pevals} object generated by
#'   \code{\link{calc_measures}}.
#' @param ... Other arguments (ignored).
#' @return \code{autoplot} automatically shows a plot or returns
#'   a \code{ggplot} object.
#'
#' @examples
#' library(ggplot2)
#'
#' data(B500)
#' pevals <- calc_measures(scores = B500$good_er_scores,
#'                         olabs = B500$labels)
#' autoplot(pevals)
autoplot.pevals <- function(object, ...) {
  df <- .prepare_autoplot(object)

  # === Create a ggplot object ===
  p <- ggplot2::ggplot(df, aes(x = x, y = y))
  p <- p + ggplot2::facet_wrap(~ group, ncol = 2)

  p <- .geom_line_wrapper(p, "Evaluation measures by threshold IDs",
                          "threshold ID", "evaluation value")

  p
}

# Plot a ROC curve
autoplot.roc_curve <- function(object, ...) {
  df <- .prepare_autoplot(object)

  # === Create a ggplot object ===
  p <- ggplot2::ggplot(df, aes(x = x, y = y))
  p <- .geom_roc_line_wrapper(p, object)

  p
}

# Plot a Precision-Recall curve
autoplot.prc_curve <- function(object, ...) {
  df <- .prepare_autoplot(object)

  # === Create a ggplot object ===
  p <- ggplot2::ggplot(df, aes(x = x, y = y))
  p <- .geom_prc_line_wrapper(p, object)

  p
}
