#' Calculate CIs of ROC and precision-recall AUCs
#'
#' The `auc_ci` function takes an `S3` object generated by
#'   [evalmod()] and calculates CIs of AUCs when multiple data sets
#'   are specified.
#'
#' @param curves An `S3` object generated by [evalmod()].
#'   The `auc_ci` function accepts the following S3 objects.
#'
#'   | **`S3` object** | **# of models** | **# of test datasets** |
#'   |-----------------|-----------------|------------------------|
#'   | smcurves        | single          | multiple               |
#'   | mmcurves        | multiple        | multiple               |
#'
#'    See the **Value** section of [evalmod()] for more details.
#'
#' @param alpha A numeric value of the significant level (default: 0.05)
#'
#' @param dtype A string to specify the distribution used for CI calculation.
#'
#'   | **dtype**        | **distribution**    |
#'   |------------------|---------------------|
#'   | normal (default) | Normal distribution |
#'   | z                | Normal distribution |
#'   | t                | t-distribution      |
#'
#' @return The `auc_ci` function returns a dataframe of AUC CIs.
#'
#' @seealso [evalmod()] for generating `S3` objects with
#'   performance evaluation measures. [auc()] for retrieving a dataset
#'   of AUCs.
#'
#' @examples
#'
#' ##################################################
#' ### Single model & multiple test datasets
#' ###
#'
#' ## Create sample datasets with 100 positives and 100 negatives
#' samps <- create_sim_samples(4, 100, 100, "good_er")
#' mdat <- mmdata(samps[["scores"]], samps[["labels"]],
#'   modnames = samps[["modnames"]],
#'   dsids = samps[["dsids"]]
#' )
#'
#' ## Generate an smcurve object that contains ROC and Precision-Recall curves
#' smcurves <- evalmod(mdat)
#'
#' ## Calculate CI of AUCs
#' sm_auc_cis <- auc_ci(smcurves)
#'
#' ## Shows the result
#' sm_auc_cis
#'
#' ##################################################
#' ### Multiple models & multiple test datasets
#' ###
#'
#' ## Create sample datasets with 100 positives and 100 negatives
#' samps <- create_sim_samples(4, 100, 100, "all")
#' mdat <- mmdata(samps[["scores"]], samps[["labels"]],
#'   modnames = samps[["modnames"]],
#'   dsids = samps[["dsids"]]
#' )
#'
#' ## Generate an mscurve object that contains ROC and Precision-Recall curves
#' mmcurves <- evalmod(mdat)
#'
#' ## Calculate CI of AUCs
#' mm_auc_ci <- auc_ci(mmcurves)
#'
#' ## Shows the result
#' mm_auc_ci
#'
#' @export
auc_ci <- function(curves, alpha = NULL, dtype = NULL) {
  UseMethod("auc_ci", curves)
}

#' @export
auc_ci.default <- function(curves, alpha = NULL, dtype = NULL) {
  stop("An object of unknown class is specified")
}

#
# Calculate an AUC CI
#
#' @rdname auc_ci
#' @export
auc_ci.aucs <- function(curves, alpha = 0.05, dtype = "normal") {
  # Validation
  .validate(curves)
  if (attr(curves, "dataset_type") != "multiple") {
    .stop_invalid_arg(
      "{.arg curves} must contain multiple datasets.",
      arg = "curves"
    )
  }
  .assert_number(alpha, "alpha", min = 0, max = 1)
  .assert_string(dtype, "dtype")

  # Check type of distribution
  dtype_tab <- c("normal", "z", "t")
  dype_match <- pmatch(tolower(dtype), dtype_tab)
  if (!is.na(dype_match)) {
    dtype <- dtype_tab[dype_match]
  }
  if (!(dtype %in% dtype_tab)) {
    .stop_invalid_arg(
      paste(
        "{.arg dtype} must be one of {.or {.val {dtype_tab}}},",
        "not {.val {dtype}}."
      ),
      arg = "dtype"
    )
  }

  # Get AUC scores
  aucs <- attr(curves, "aucs")

  # Get unique model names, data set IDs and curve types
  uniq_modnames <- attr(curves, "uniq_modnames")
  uniq_curvetype <- unique(aucs$curvetypes)

  ci_df <- NULL
  for (modname in uniq_modnames) {
    auc_mod <- aucs[aucs$modnames == modname, ]
    for (curvetype in uniq_curvetype) {
      aucs_subset <- auc_mod[auc_mod$curvetypes == curvetype, ]

      # Prepare for CI calculation
      aucs_mean <- mean(aucs_subset$aucs)
      aucs_n <- length(aucs_subset$aucs)
      if (aucs_n < 2) {
        ci_df <- rbind(
          ci_df,
          data.frame(
            modnames = modname,
            curvetypes = curvetype,
            mean = aucs_mean,
            error = 0,
            lower_bound = aucs_mean,
            upper_bound = aucs_mean,
            n = aucs_n
          )
        )
        next
      }
      aucs_sd <- sd(aucs_subset$aucs)

      # Calculate CI
      if (dtype == "normal" || dtype == "z") {
        aucs_q <- qnorm(1 - (alpha / 2))
      } else if (dtype == "t") {
        aucs_q <- qt(1 - (alpha / 2), df = aucs_n - 1)
      }

      aucs_error <- aucs_q * aucs_sd / sqrt(aucs_n)
      acus_lower <- max(aucs_mean - aucs_error, 0.0)
      acus_upper <- min(aucs_mean + aucs_error, 1.0)

      ci_df <- rbind(
        ci_df,
        data.frame(
          modnames = modname,
          curvetypes = curvetype,
          mean = aucs_mean,
          error = aucs_error,
          lower_bound = acus_lower,
          upper_bound = acus_upper,
          n = aucs_n
        )
      )
    }
  }

  ci_df
}
