#' Retrieve a data frame of AUC scores
#'
#' The `auc` function takes an `S3` object generated by
#'   [evalmod()] and retrieves a data frame with the Area Under
#'   the Curve (AUC) scores of ROC and Precision-Recall curves.
#'
#' @param curves An `S3` object generated by [evalmod()].
#'   The `auc` function accepts the following S3 objects.
#'
#'   | **`S3` object** | **# of models** | **# of test datasets** |
#'   |-----------------|-----------------|------------------------|
#'   | sscurves        | single          | single                 |
#'   | mscurves        | multiple        | single                 |
#'   | smcurves        | single          | multiple               |
#'   | mmcurves        | multiple        | multiple               |
#'
#'    See the **Value** section of [evalmod()] for more details.
#'
#' @param macro A Boolean value to specify whether the macro-average of the
#'   per-class AUCs is added. It is effective only for a multiclass
#'   evaluation - see the `multiclass` argument of [mmdata()] - and the
#'   added rows carry `macro-average` as their model name. Classes that
#'   could not be evaluated are left out of the average.
#'
#' @param macro_weight How the per-class AUCs are weighted in that average.
#'   `"uniform"`, the default, gives every class the same weight, so a rare
#'   class counts as much as a common one. `"prevalence"` weights each class
#'   by the number of observations it has, so the average follows the class
#'   distribution of the data. The weighted rows are named
#'   `macro-average-weighted` to keep the two apart. The two agree on a
#'   balanced dataset.
#'
#'   For a ROC evaluation the two are the measures other packages call
#'   `roc_aunu` and `roc_aunp` respectively.
#'
#' @return The `auc` function returns a data frame with AUC scores.
#'
#' @seealso [evalmod()] for generating `S3` objects with
#'   performance evaluation measures. [pauc()] for retrieving
#'   a dataset of pAUCs. [average_precision()] for the step estimator of
#'   the area under the precision-recall curve.
#'
#' @examples
#'
#' ##################################################
#' ### Single model & single test dataset
#' ###
#'
#' ## Load a dataset with 10 positives and 10 negatives
#' data(P10N10)
#'
#' ## Generate an sscurve object that contains ROC and Precision-Recall curves
#' sscurves <- evalmod(scores = P10N10$scores, labels = P10N10$labels)
#'
#' ## Shows AUCs
#' auc(sscurves)
#'
#'
#' ##################################################
#' ### Multiple models & single test dataset
#' ###
#'
#' ## Create sample datasets with 100 positives and 100 negatives
#' samps <- create_sim_samples(1, 100, 100, "all")
#' mdat <- mmdata(samps[["scores"]], samps[["labels"]],
#'   modnames = samps[["modnames"]]
#' )
#'
#' ## Generate an mscurve object that contains ROC and Precision-Recall curves
#' mscurves <- evalmod(mdat)
#'
#' ## Shows AUCs
#' auc(mscurves)
#'
#'
#' ##################################################
#' ### Single model & multiple test datasets
#' ###
#'
#' ## Create sample datasets with 100 positives and 100 negatives
#' samps <- create_sim_samples(4, 100, 100, "good_er")
#' mdat <- mmdata(samps[["scores"]], samps[["labels"]],
#'   modnames = samps[["modnames"]],
#'   dsids = samps[["dsids"]]
#' )
#'
#' ## Generate an smcurve object that contains ROC and Precision-Recall curves
#' smcurves <- evalmod(mdat, raw_curves = TRUE)
#'
#' ## Get AUCs
#' sm_aucs <- auc(smcurves)
#'
#' ## Shows AUCs
#' sm_aucs
#'
#' ## Get AUCs of Precision-Recall
#' sm_aucs_prc <- subset(sm_aucs, curvetypes == "PRC")
#'
#' ## Shows AUCs
#' sm_aucs_prc
#'
#' ##################################################
#' ### Multiple models & multiple test datasets
#' ###
#'
#' ## Create sample datasets with 100 positives and 100 negatives
#' samps <- create_sim_samples(4, 100, 100, "all")
#' mdat <- mmdata(samps[["scores"]], samps[["labels"]],
#'   modnames = samps[["modnames"]],
#'   dsids = samps[["dsids"]]
#' )
#'
#' ## Generate an mscurve object that contains ROC and Precision-Recall curves
#' mmcurves <- evalmod(mdat, raw_curves = TRUE)
#'
#' ## Get AUCs
#' mm_aucs <- auc(mmcurves)
#'
#' ## Shows AUCs
#' mm_aucs
#'
#' ## Get AUCs of Precision-Recall
#' mm_aucs_prc <- subset(mm_aucs, curvetypes == "PRC")
#'
#' ## Shows AUCs
#' mm_aucs_prc
#'
#'
#' ##################################################
#' ### Multiclass evaluation
#' ###
#'
#' ## Load a 3-class dataset with one score column per class
#' data(C3N150)
#'
#' ## One-vs-rest curves
#' mccurves <- evalmod(scores = C3N150$scores, labels = C3N150$labels)
#'
#' ## Per-class AUCs, plus their macro-average
#' auc(mccurves)
#'
#' ## Per-class AUCs only
#' auc(mccurves, macro = FALSE)
#'
#' ## Weighted by the class distribution instead
#' auc(mccurves, macro_weight = "prevalence")
#'
#' @export
auc <- function(curves, macro = TRUE,
                macro_weight = c("uniform", "prevalence")) {
  UseMethod("auc", curves)
}

#' @export
auc.default <- function(curves, macro = TRUE,
                        macro_weight = c("uniform", "prevalence")) {
  stop("An object of unknown class is specified")
}

#
# Print AUC scores
#
#' @rdname auc
#' @export
auc.aucs <- function(curves, macro = TRUE,
                     macro_weight = c("uniform", "prevalence")) {
  # Validation
  .validate(curves)
  .assert_flag(macro, "macro")
  macro_weight <- match.arg(macro_weight)

  # Return AUC scores as a plain data frame
  aucs <- .as_plain_df(attr(curves, "aucs"), copy = TRUE)
  if (!macro || !.is_multiclass(curves)) {
    return(aucs)
  }

  rbind(aucs, .macro_average_aucs(aucs, curves, macro_weight))
}

#
# Average the per-class AUCs of a one-vs-rest evaluation
#
# One row per dataset and curve type, the unweighted mean over the classes.
# Classes that could not be evaluated carry NA and are left out, so a fold
# missing one class still gets an average over the rest.
#
.macro_average_aucs <- function(aucs, curves, macro_weight = "uniform") {
  info <- .as_plain_df(attr(curves, "data_info"), copy = TRUE)

  # A model name is either the class on its own, when there is one model, or
  # "class:model". Strip the class back off to group by model.
  models <- ifelse(
    info[["modnames"]] == info[["classes"]], "",
    substring(info[["modnames"]], nchar(info[["classes"]]) + 2L)
  )
  names(models) <- info[["modnames"]]
  row_models <- unname(models[as.character(aucs[["modnames"]])])

  # The weight of a class is the number of positives it has, which for a
  # one-vs-rest expansion is the number of observations in that class. It is
  # looked up per dataset as well as per class, because a fold need not hold
  # the classes in the proportions the whole dataset does.
  weighted <- macro_weight == "prevalence"
  np <- info[["np"]]
  names(np) <- paste(info[["modnames"]], info[["dsids"]])
  row_np <- unname(np[paste(aucs[["modnames"]], aucs[["dsids"]])])

  label <- if (weighted) "macro-average-weighted" else "macro-average"

  parts <- list()
  for (model in unique(row_models)) {
    if (model == "") {
      modname <- label
    } else {
      modname <- paste0(label, ":", model)
    }
    for (dsid in unique(aucs[["dsids"]])) {
      for (curvetype in unique(aucs[["curvetypes"]])) {
        sel <- row_models == model & aucs[["dsids"]] == dsid &
          aucs[["curvetypes"]] == curvetype
        vals <- aucs[["aucs"]][sel]
        wts <- row_np[sel]

        # A class that could not be evaluated is dropped along with its
        # weight, so the remaining weights still sum to one over the
        # classes that are actually being averaged.
        keep <- !is.na(vals)
        vals <- vals[keep]
        wts <- wts[keep]

        if (length(vals) == 0L) {
          avg <- NA_real_
        } else if (weighted && !anyNA(wts) && sum(wts) > 0) {
          avg <- sum(vals * wts) / sum(wts)
        } else {
          avg <- mean(vals)
        }

        parts[[length(parts) + 1L]] <- data.table::data.table(
          modnames = modname,
          dsids = dsid,
          curvetypes = curvetype,
          aucs = avg
        )
      }
    }
  }

  # Freshly built, so setDF needs no copy
  .as_plain_df(.rbind_parts(parts))
}
