#' Calculate CIs of ROC and precision-recall AUCs
#'
#' The `auc_ci` function takes an `S3` object generated by
#'   [evalmod()] and calculates CIs of AUCs when multiple data sets
#'   are specified.
#'
#' @param curves An `S3` object generated by [evalmod()].
#'   The `auc_ci` function accepts the following S3 objects.
#'
#'   | **`S3` object** | **# of models** | **# of test datasets** |
#'   |-----------------|-----------------|------------------------|
#'   | smcurves        | single          | multiple               |
#'   | mmcurves        | multiple        | multiple               |
#'
#'    See the **Value** section of [evalmod()] for more details.
#'
#' @param alpha A numeric value of the significant level (default: 0.05)
#'
#' @param dtype A string to specify the distribution used for CI calculation.
#'
#'   | **dtype**        | **distribution**    |
#'   |------------------|---------------------|
#'   | normal (default) | Normal distribution |
#'   | z                | Normal distribution |
#'   | t                | t-distribution      |
#'
#' @return The `auc_ci` function returns a dataframe of AUC CIs.
#'
#' @seealso [evalmod()] for generating `S3` objects with
#'   performance evaluation measures. [auc()] for retrieving a dataset
#'   of AUCs.
#'
#' @examples
#'
#' ##################################################
#' ### Single model & multiple test datasets
#' ###
#'
#' ## Create sample datasets with 100 positives and 100 negatives
#' samps <- create_sim_samples(4, 100, 100, "good_er")
#' mdat <- mmdata(samps[["scores"]], samps[["labels"]],
#'   modnames = samps[["modnames"]],
#'   dsids = samps[["dsids"]]
#' )
#'
#' ## Generate an smcurve object that contains ROC and Precision-Recall curves
#' smcurves <- evalmod(mdat)
#'
#' ## Calculate CI of AUCs
#' sm_auc_cis <- auc_ci(smcurves)
#'
#' ## Shows the result
#' sm_auc_cis
#'
#' ##################################################
#' ### Multiple models & multiple test datasets
#' ###
#'
#' ## Create sample datasets with 100 positives and 100 negatives
#' samps <- create_sim_samples(4, 100, 100, "all")
#' mdat <- mmdata(samps[["scores"]], samps[["labels"]],
#'   modnames = samps[["modnames"]],
#'   dsids = samps[["dsids"]]
#' )
#'
#' ## Generate an mscurve object that contains ROC and Precision-Recall curves
#' mmcurves <- evalmod(mdat)
#'
#' ## Calculate CI of AUCs
#' mm_auc_ci <- auc_ci(mmcurves)
#'
#' ## Shows the result
#' mm_auc_ci
#'
#' @export
auc_ci <- function(curves, alpha = NULL, dtype = NULL) {
  UseMethod("auc_ci", curves)
}

#' @export
auc_ci.default <- function(curves, alpha = NULL, dtype = NULL) {
  stop("An object of unknown class is specified")
}

#
# Calculate an AUC CI
#
#' @rdname auc_ci
#' @export
auc_ci.aucs <- function(curves, alpha = 0.05, dtype = "normal") {
  # Validation
  .validate(curves)
  if (attr(curves, "dataset_type") != "multiple") {
    .stop_invalid_arg(
      "{.arg curves} must contain multiple datasets.",
      arg = "curves"
    )
  }
  .assert_number(alpha, "alpha", min = 0, max = 1)
  dtype <- .pmatch_dtype(dtype)

  # Get AUC scores. A plain data frame view, so the row subsetting below
  # keeps base semantics - inside `[.data.table` the `i` expression would
  # resolve `aucs` to the column of that name rather than the table.
  aucs <- .as_plain_df(attr(curves, "aucs"), copy = TRUE)

  # Get unique model names, data set IDs and curve types
  uniq_modnames <- attr(curves, "uniq_modnames")
  uniq_curvetype <- unique(aucs$curvetypes)

  ci_parts <- list()
  for (modname in uniq_modnames) {
    auc_mod <- aucs[aucs$modnames == modname, ]
    for (curvetype in uniq_curvetype) {
      aucs_subset <- auc_mod[auc_mod$curvetypes == curvetype, ]

      # AUCs cannot leave [0, 1], so the interval is clipped to it
      ci <- .calc_ci_stats(aucs_subset$aucs, alpha, dtype,
        lower = 0, upper = 1
      )

      ci_parts[[length(ci_parts) + 1L]] <- data.table::data.table(
        modnames = modname,
        curvetypes = curvetype,
        mean = ci[["mean"]],
        error = ci[["error"]],
        lower_bound = ci[["lower_bound"]],
        upper_bound = ci[["upper_bound"]],
        n = ci[["n"]]
      )
    }
  }

  # Freshly built, so setDF needs no copy
  .as_plain_df(.rbind_parts(ci_parts))
}
