#' Convert a curves and points object to a data.table
#'
#' The `as.data.table` function converts an `S3` object generated by
#'   [evalmod()] to a `data.table`. It is the counterpart of
#'   [as.data.frame()], for callers who would rather have the
#'   `data.table` that `precrec` builds internally than a copy of it as a
#'   plain data frame.
#'
#' @param x An `S3` object generated by [evalmod()]. The
#'   `as.data.table` function accepts the same objects as
#'   [as.data.frame()].
#'
#' @param keep.rownames Ignored. Present because
#'   `data.table::as.data.table` has it in its signature; the objects this
#'   method converts carry no row names.
#'
#' @param raw_curves A Boolean value to specify whether raw curves are
#'   shown instead of the average curve. It is effective only
#'   when `raw_curves` is set to `TRUE`
#'   of the [evalmod()] function.
#'
#' @param ... Not used by this method.
#'
#' @return The `as.data.table` function returns a `data.table` with the
#'   same columns as [as.data.frame()] returns for the same object.
#'
#' @seealso [evalmod()] for generating `S3` objects with performance
#'   evaluation measures. [as.data.frame()] for the plain data frame
#'   equivalent. [fortify()] for converting the same objects for
#'   `ggplot2`.
#'
#' @examples
#'
#' ## Load a dataset with 10 positives and 10 negatives
#' data(P10N10)
#'
#' ## Generate an sscurve object that contains ROC and Precision-Recall curves
#' sscurves <- evalmod(scores = P10N10$scores, labels = P10N10$labels)
#'
#' ## Convert sscurves to a data.table
#' if (requireNamespace("data.table", quietly = TRUE)) {
#'   head(data.table::as.data.table(sscurves))
#' }
#'
#' @name as.data.table
NULL

#' @rdname as.data.table
#' @exportS3Method data.table::as.data.table
as.data.table.sscurves <- function(x, keep.rownames = FALSE,
                                   raw_curves = NULL, ...) {
  arglist <- .get_dataframe_arglist(attr(x, "args"),
    def_raw_curves = TRUE, ...
  )

  .dataframe_common(x, raw_curves = arglist[["raw_curves"]], ...)
}

#' @rdname as.data.table
#' @exportS3Method data.table::as.data.table
as.data.table.mscurves <- function(x, keep.rownames = FALSE,
                                   raw_curves = NULL, ...) {
  arglist <- .get_dataframe_arglist(attr(x, "args"),
    def_raw_curves = TRUE, ...
  )

  .dataframe_common(x, raw_curves = arglist[["raw_curves"]], ...)
}

#' @rdname as.data.table
#' @exportS3Method data.table::as.data.table
as.data.table.smcurves <- function(x, keep.rownames = FALSE,
                                   raw_curves = NULL, ...) {
  arglist <- .get_dataframe_arglist(attr(x, "args"),
    def_raw_curves = raw_curves, ...
  )

  .dataframe_common(x, raw_curves = arglist[["raw_curves"]], ...)
}

#' @rdname as.data.table
#' @exportS3Method data.table::as.data.table
as.data.table.mmcurves <- function(x, keep.rownames = FALSE,
                                   raw_curves = NULL, ...) {
  arglist <- .get_dataframe_arglist(attr(x, "args"),
    def_raw_curves = raw_curves, ...
  )

  .dataframe_common(x, raw_curves = arglist[["raw_curves"]], ...)
}

#' @rdname as.data.table
#' @exportS3Method data.table::as.data.table
as.data.table.sspoints <- function(x, keep.rownames = FALSE,
                                   raw_curves = NULL, ...) {
  arglist <- .get_dataframe_arglist(attr(x, "args"),
    def_raw_curves = TRUE, ...
  )

  .dataframe_common(x,
    mode = "basic", raw_curves = arglist[["raw_curves"]], ...
  )
}

#' @rdname as.data.table
#' @exportS3Method data.table::as.data.table
as.data.table.mspoints <- function(x, keep.rownames = FALSE,
                                   raw_curves = NULL, ...) {
  arglist <- .get_dataframe_arglist(attr(x, "args"),
    def_raw_curves = TRUE, ...
  )

  .dataframe_common(x,
    mode = "basic", raw_curves = arglist[["raw_curves"]], ...
  )
}

#' @rdname as.data.table
#' @exportS3Method data.table::as.data.table
as.data.table.smpoints <- function(x, keep.rownames = FALSE,
                                   raw_curves = NULL, ...) {
  arglist <- .get_dataframe_arglist(attr(x, "args"),
    def_raw_curves = raw_curves, ...
  )

  .dataframe_common(x,
    mode = "basic", raw_curves = arglist[["raw_curves"]], ...
  )
}

#' @rdname as.data.table
#' @exportS3Method data.table::as.data.table
as.data.table.mmpoints <- function(x, keep.rownames = FALSE,
                                   raw_curves = NULL, ...) {
  arglist <- .get_dataframe_arglist(attr(x, "args"),
    def_raw_curves = raw_curves, ...
  )

  .dataframe_common(x,
    mode = "basic", raw_curves = arglist[["raw_curves"]], ...
  )
}

#' @rdname as.data.table
#' @exportS3Method data.table::as.data.table
as.data.table.aucroc <- function(x, keep.rownames = FALSE, ...) {
  # A copy: the stored table must not be reachable for modification by
  # reference through the returned one
  data.table::copy(x[["uaucs"]])
}
