#' Convert a curves object to a data frame for ggplot2.
#'
#' \code{fortify} takes a \code{curves} object generated by
#' \code{\link{evalmod}} or \code{\link{create_curves}}
#' and convert it to a data frame .
#' \code{fortify} requires \code{\link[ggplot2]{ggplot2}}.
#'
#' @param model \code{curves} object generated by
#'   \code{\link{evalmod}} or \code{\link{create_curves}}.
#' @param data Not used by this method.
#' @param ... Further arguments (ignored).
#' @return \code{fortify} retruns a data frame for \code{ggplot2}.
#'
#' @examples
#' library(ggplot2)
#' data(P10N10)
#' curves <- evalmod(pscores = P10N10$scores, olabs = P10N10$labels)
#'
#' df <- fortify(curves)
#' p_roc <- ggplot2::ggplot(subset(df, group == "ROC"), aes(x = x, y = y))
#' p_roc <- p_roc + geom_line()
#' p_roc
#'
#' p_prc <- ggplot2::ggplot(subset(df, group == "PRC"), aes(x = x, y = y))
#' p_prc <- p_prc + geom_line()
#' p_prc
fortify.sscurves <- function(model, data = NULL, ...) {
  # === Check package availability  ===
  .load_ggplot2()

  # === Validate input arguments ===
  .validate(model)

  # === Prepare a data frame for ggplot2 ===
  roc_df <- fortify(model[["rocs"]])
  prc_df <- fortify(model[["prcs"]])
  x <- c(roc_df[["x"]], prc_df[["x"]])
  y <- c(roc_df[["y"]], prc_df[["y"]])
  group = factor(c(rep("ROC", length(roc_df[["x"]])),
                   rep("PRC", length(prc_df[["x"]]))))
  df <- data.frame(x = x, y = y, group = group)
}

#' Convert a roc_curve object to a data frame for ggplot2.
#'
#' \code{fortify} takes a \code{roc_curve} object generated by
#' \code{\link{create_roc}} and convert it to a data frame .
#' \code{fortify} requires \code{\link[ggplot2]{ggplot2}}.
#'
#' @param model \code{roc_curve} object generated by
#'   \code{\link{create_roc}}.
#' @param data Not used by this method.
#' @param ... Further arguments (ignored).
#' @return \code{fortify} retruns a data frame for \code{ggplot2}.
#'
#' @examples
#' library(ggplot2)
#' data(P10N10)
#' curves <- evalmod(pscores = P10N10$scores, olabs = P10N10$labels)
#'
#' df <- fortify(curves[["rocs"]])
#' p <- ggplot2::ggplot(df, aes(x = x, y = y))
#' p <- p + geom_line()
#' p
fortify.ssroc <- function(model, data = NULL, ...) {
  fortify(model[[1]])
}

#' Convert a prc_curve object to a data frame for ggplot2.
#'
#' \code{fortify} takes a \code{prc_curve} object generated by
#' \code{\link{create_prc}} and convert it to a data frame .
#' \code{fortify} requires \code{\link[ggplot2]{ggplot2}}.
#'
#' @param model \code{prc_curve} object generated by
#'   \code{\link{create_prc}}.
#' @param data Not used by this method.
#' @param ... Further arguments (ignored).
#' @return \code{fortify} retruns a data frame for \code{ggplot2}.
#'
#' @examples
#' library(ggplot2)
#' data(P10N10)
#' curves <- evalmod(pscores = P10N10$scores, olabs = P10N10$labels)
#'
#' df <- fortify(curves[["prcs"]])
#' p <- ggplot2::ggplot(df, aes(x = x, y = y))
#' p <- p + geom_line()
#' p
fortify.ssprc <- function(model, data = NULL, ...) {
  fortify(model[[1]])
}
