#' Convert mscurves object to a data frame for ggplot2.
#'
#' \code{fortify} converts an \code{mscurves} object generated by
#'   \code{\link{evalmods}} to a data frame for
#'   \code{\link[ggplot2]{ggplot2}}.
#'
#' @param model \code{mscurves} object generated by
#'   \code{\link{evalmods}}.
#'
#' @param ... Not used by this method.
#'
#' @return The \code{fortify} function retruns a data frame for
#'   \code{\link[ggplot2]{ggplot2}}.
#'
#' @seealso \code{\link{evalmods}} for generating \code{mscurves}.
#'  \code{\link{autoplot.mscurves}} for plotting curves.
#'
#' @examples
#'
#' ## Load ggplot2
#' library(ggplot2)
#'
#' ## Create sample datasets with 100 positives and 100 negatives
#' samps <- create_sim_samples(1, 100, 100, "all")
#' mdat <- mmdata(samps[["scores"]], samps[["labels"]],
#'                model_names = samps[["model_names"]],
#'                setids = samps[["setids"]])
#'
#' ## Convert sscurve object to a data frame
#' curves <- evalmod(scores = P10N10$scores, labels = P10N10$labels)
#' df <- fortify(curves)
#'
#' ## Fortified data frame can be used for plotting a ROC curve
#' df_roc <- subset(df, group == "ROC")
#' p_roc <- ggplot(df_roc, aes(x = x, y = y, color = model_name))
#' p_roc <- p_roc + geom_line()
#' p_roc
#'
#' ## Fortified data frame can be used for plotting a Precision-Recall curve
#' df_prc <- subset(df, group == "PRC")
#' p_prc <- ggplot(df_prc, aes(x = x, y = y, color = model_name))
#' p_prc <- p_prc + geom_line()
#' p_prc
#'
#' @export
fortify.mscurves <- function(model, ...) {
  # === Check package availability  ===
  .load_ggplot2()

  # === Validate input arguments ===
  .validate(model)

  # === Prepare a data frame for ggplot2 ===
  roc_df <- ggplot2::fortify(model[["rocs"]])
  prc_df <- ggplot2::fortify(model[["prcs"]])
  x <- c(roc_df[["x"]], prc_df[["x"]])
  y <- c(roc_df[["y"]], prc_df[["y"]])
  model_name <- factor(c(roc_df[["model_name"]], prc_df[["model_name"]]),
                       labels = levels(roc_df[["model_name"]]))
  group = factor(c(rep("ROC", length(roc_df[["x"]])),
                   rep("PRC", length(prc_df[["x"]]))))

  df <- data.frame(x = x, y = y, group = group, model_name = model_name)
}

#
# Convert a mroc_curves object to a data frame for ggplot2.
#
fortify.msroc <- function(model, ...) {
  # === Check package availability  ===
  .load_ggplot2()

  # === Validate input arguments ===
  .validate(model)

  # === Prepare a data frame for ggplot2 ===
  df <- NULL
  modnames <- attr(model, "model_names")
  for (i in seq_along(model)) {
    x = model[[i]][["x"]]
    y = model[[i]][["y"]]
    model_name = factor(rep(modnames[i], length(x)), levels = modnames)
    df <- rbind(df, data.frame(x = x, y = y, model_name = model_name))
  }

  df
}

#
# Convert a mprc_curves object to a data frame for ggplot2.
#
fortify.msprc <- function(model, ...) {
  fortify.msroc(model, ...)
}
