#' Convert sscurves to a data frame for ggplot2.
#'
#' \code{fortify} converts an \code{sscurves} object generated by
#'   \code{\link{evalmod}} to a data frame for
#'   \code{\link[ggplot2]{ggplot2}}.
#'
#' @param model \code{sscurves} object generated by
#'   \code{\link{evalmod}}.
#'
#' @param ... Not used by this method.
#'
#' @return The \code{fortify} function retruns a data frame for
#'   \code{\link[ggplot2]{ggplot2}}.
#'
#' @seealso \code{\link{evalmod}} for generating \code{sscurves}.
#'  \code{\link{autoplot.sscurves}} for plotting curves.
#'
#' @examples
#'
#' ## Load ggplot2
#' library(ggplot2)
#'
#' ## Load a dataset with 10 positives and 10 negatives
#' data(P10N10)
#'
#' ## Convert sscurve object to a data frame
#' curves <- evalmod(scores = P10N10$scores, labels = P10N10$labels)
#' df <- fortify(curves)
#'
#' ## Fortified data frame can be used for plotting a ROC curve
#' p_roc <- ggplot(subset(df, group == "ROC"), aes(x = x, y = y))
#' p_roc <- p_roc + geom_line()
#' p_roc
#'
#' ## Fortified data frame can be used for plotting a Precision-Recall curve
#' p_prc <- ggplot(subset(df, group == "PRC"), aes(x = x, y = y))
#' p_prc <- p_prc + geom_line()
#' p_prc
#'
#' @export
fortify.sscurves <- function(model, ...) {
  .fortify_common(model, ...)
}

#' Convert mscurves object to a data frame for ggplot2.
#'
#' \code{fortify} converts an \code{mscurves} object generated by
#'   \code{\link{evalmods}} to a data frame for
#'   \code{\link[ggplot2]{ggplot2}}.
#'
#' @param model \code{mscurves} object generated by
#'   \code{\link{evalmods}}.
#'
#' @param ... Not used by this method.
#'
#' @return The \code{fortify} function retruns a data frame for
#'   \code{\link[ggplot2]{ggplot2}}.
#'
#' @seealso \code{\link{evalmods}} for generating \code{mscurves}.
#'  \code{\link{autoplot.mscurves}} for plotting curves.
#'
#' @examples
#'
#' ## Load ggplot2
#' library(ggplot2)
#'
#' ## Create sample datasets with 100 positives and 100 negatives
#' samps <- create_sim_samples(1, 100, 100, "all")
#' mdat <- mmdata(samps[["scores"]], samps[["labels"]],
#'                modnames = samps[["modnames"]],
#'                dsids = samps[["dsids"]])
#'
#' ## Convert sscurve object to a data frame
#' curves <- evalmod(scores = P10N10$scores, labels = P10N10$labels)
#' df <- fortify(curves)
#'
#' ## Fortified data frame can be used for plotting a ROC curve
#' df_roc <- subset(df, group == "ROC")
#' p_roc <- ggplot(df_roc, aes(x = x, y = y, color = modname))
#' p_roc <- p_roc + geom_line()
#' p_roc
#'
#' ## Fortified data frame can be used for plotting a Precision-Recall curve
#' df_prc <- subset(df, group == "PRC")
#' p_prc <- ggplot(df_prc, aes(x = x, y = y, color = modname))
#' p_prc <- p_prc + geom_line()
#' p_prc
#'
#' @export
fortify.mscurves <- function(model, ...) {
  .fortify_common(model, ...)
}

#' Convert smcurves object to a data frame for ggplot2.
#'
#' \code{fortify} converts an \code{smcurves} object generated by
#'   \code{\link{evalmod_m}} to a data frame for
#'   \code{\link[ggplot2]{ggplot2}}.
#'
#' @param model \code{smcurves} object generated by
#'   \code{\link{evalmod_m}}.
#'
#' @param ... Not used by this method.
#'
#' @return The \code{fortify} function retruns a data frame for
#'   \code{\link[ggplot2]{ggplot2}}.
#'
#' @seealso \code{\link{evalmod_m}} for generating \code{smcurves}.
#'  \code{\link{autoplot.smcurves}} for plotting curves.
#'
#' @examples
#'
#' ## Load ggplot2
#' library(ggplot2)
#'
#' ## Prepare input data
#' samps <- create_sim_samples(10, 100, 100, "poor_er")
#' mdat <- mmdata(samps[["scores"]], samps[["labels"]],
#'                modnames = samps[["modnames"]],
#'                dsids = samps[["dsids"]])
#'
#' ## Convert sscurve object to a data frame
#' curves <- evalmod_m(mdat)
#' df <- fortify(curves)
#'
#' ## Fortified data frame can be used for plotting a ROC curve
#' df_roc <- subset(df, group == "ROC")
#' p_roc <- ggplot(df_roc, aes(x = x, y = y, ymin = ymin, ymax = ymax))
#' p_roc <- p_roc + geom_smooth(stat = "identity")
#' p_roc
#'
#' ## Fortified data frame can be used for plotting a Precision-Recall curve
#' df_prc <- subset(df, group == "PRC")
#' p_prc <- ggplot(df_roc, aes(x = x, y = y, ymin = ymin, ymax = ymax))
#' p_prc <- p_roc + geom_smooth(stat = "identity")
#' p_prc
#'
#' @export
fortify.smcurves <- function(model, ...) {
  .fortify_common(model, ...)
}

#' Convert mmcurves object to a data frame for ggplot2.
#'
#' \code{fortify} converts an \code{mmcurves} object generated by
#'   \code{\link{evalmods_m}} to a data frame for
#'   \code{\link[ggplot2]{ggplot2}}.
#'
#' @param model \code{mmcurves} object generated by
#'   \code{\link{evalmods_m}}.
#'
#' @param ... Not used by this method.
#'
#' @return The \code{fortify} function retruns a data frame for
#'   \code{\link[ggplot2]{ggplot2}}.
#'
#' @seealso \code{\link{evalmods_m}} for generating \code{smcurves}.
#'  \code{\link{autoplot.mmcurves}} for plotting curves.
#'
#' @examples
#'
#' ## Load ggplot2
#' library(ggplot2)
#'
#' ## Prepare input data
#' samps <- create_sim_samples(10, 100, 100, "all")
#' mdat <- mmdata(samps[["scores"]], samps[["labels"]],
#'                modnames = samps[["modnames"]],
#'                dsids = samps[["dsids"]])
#'
#' ## Convert sscurve object to a data frame
#' curves <- evalmods_m(mdat)
#' df <- fortify(curves)
#'
#' ## Fortified data frame can be used for plotting a ROC curve
#' df_roc <- subset(df, group == "ROC")
#' p_roc <- ggplot(df_roc, aes(x = x, y = y, ymin = ymin, ymax = ymax,
#'                             color = modname))
#' p_roc <- p_roc + geom_smooth(stat = "identity")
#' p_roc
#'
#' ## Fortified data frame can be used for plotting a Precision-Recall curve
#' df_prc <- subset(df, group == "PRC")
#' p_prc <- ggplot(df_roc, aes(x = x, y = y, ymin = ymin, ymax = ymax,
#'                             color = modname))
#' p_prc <- p_roc + geom_smooth(stat = "identity")
#' p_prc
#'
#' @export
fortify.mmcurves <- function(model, ...) {
  .fortify_common(model, ...)
}
