#' Convert a fmdat object to a data frame for ggplot2.
#'
#' \code{fortify} takes a \code{fmdat} object generated by
#' \code{\link{reformat_data}} and convert it to a data frame .
#' \code{fortify} requires \code{\link[ggplot2]{ggplot2}}.
#'
#' @param model \code{fmdat} object generated by
#'   \code{\link{reformat_data}}.
#' @param data Not used by this method.
#' @param ... Further arguments (ignored).
#' @return \code{fortify} retruns a data frame for \code{ggplot2}.
#'
#' @examples
#' library(ggplot2)
#' data(B500)
#' fmdat <- reformat_data(B500$good_er_scores, B500$labels)
#' df <- fortify(fmdat)
#' p <- ggplot(df, aes(x = x, y = y, color = x))
#' p <- p + geom_jitter()
#' p <- p + coord_flip()
#' p
fortify.fmdat <- function(model, data = NULL, ...) {
  # === Check package availability  ===
  .load_ggplot2()

  # === Validate input arguments ===
  .validate(model)

  # === Prepare a data frame for ggplot2 ===
  df <- data.frame(x = model[["obslabs"]],
                   y = model[["ranks"]])
}

#' Convert a cmats object to a data frame for ggplot2.
#'
#' \code{fortify} takes a \code{cmats} object generated by
#' \code{\link{create_confmats}} and convert it to a data frame .
#' \code{fortify} requires \code{\link[ggplot2]{ggplot2}}.
#'
#' @param model \code{cmats} object generated by
#'   \code{\link{create_confmats}}.
#' @param data Not used by this method.
#' @param ... Further arguments (ignored).
#' @return \code{fortify} retruns a data frame for \code{ggplot2}.
#'
#' @examples
#' library(ggplot2)
#' data(B500)
#' cmat <- create_confmats(scores = B500$good_er_scores,
#'                         obslabs = B500$labels)
#' df <- fortify(cmat)
#' p <- ggplot2::ggplot(df, aes(x = x, y = y, color = group))
#' p <- p + geom_line()
#' p
fortify.cmats <- function(model, data = NULL, ...) {
  # === Check package availability  ===
  .load_ggplot2()

  # === Validate input arguments ===
  .validate(model)

  # === Prepare a data frame for ggplot2 ===
  n <- length(model[["ranks"]])
  df <- data.frame(x = rep(1:length(model[["ranks"]]), 4),
                   y = c(model[["tp"]],
                         model[["fn"]],
                         model[["fp"]],
                         model[["tn"]]),
                   group = factor(c(rep("TPs", n), rep("FNs", n),
                                    rep("FPs", n), rep("TNs", n)),
                                  levels = c("TPs", "FNs", "FPs", "TNs")))
}

#' Convert an evals object to a data frame for ggplot2.
#'
#' \code{fortify} takes an \code{evals} object generated by
#' \code{\link{calc_measures}} and convert it to a data frame .
#' \code{fortify} requires \code{\link[ggplot2]{ggplot2}}.
#'
#' @param model \code{evals} object generated by
#'   \code{\link{calc_measures}}.
#' @param data Not used by this method.
#' @param ... Further arguments (ignored).
#' @return \code{fortify} retruns a data frame for \code{ggplot2}.
#'
#' @examples
#' library(ggplot2)
#' data(B500)
#' evals <- calc_measures(scores = B500$good_er_scores,
#'                        obslabs = B500$labels)
#' df <- fortify(evals)
#' p <- ggplot(df, aes(x = x, y = y))
#' p <- p + facet_wrap(~ group, ncol = 2)
#' p <- p + geom_line()
#' p
fortify.evals <- function(model, data = NULL, ...) {
  # === Check package availability  ===
  .load_ggplot2()

  # === Validate input arguments ===
  .validate(model)

  # === Prepare a data frame for ggplot2 ===
  n <- length(model[["error"]])
  df <- data.frame(x = rep(1:n, 6),
                   y = c(model[["error"]],
                         model[["accuracy"]],
                         model[["specificity"]],
                         model[["sensitivity"]],
                         1 - model[["specificity"]],
                         model[["precision"]]),
                   group = factor(c(rep("error", n),
                                    rep("accuracy", n),
                                    rep("specificity", n),
                                    rep("sensitivity", n),
                                    rep("1 - specificity", n),
                                    rep("precision", n)),
                                  levels = c("error", "accuracy",
                                             "specificity", "sensitivity",
                                             "1 - specificity",
                                             "precision")))
}

#' Convert a roc_curve object to a data frame for ggplot2.
#'
#' \code{fortify} takes a \code{roc_curve} object generated by
#' \code{\link{create_roc}} and convert it to a data frame .
#' \code{fortify} requires \code{\link[ggplot2]{ggplot2}}.
#'
#' @param model \code{roc_curve} object generated by
#'   \code{\link{create_roc}}.
#' @param data Not used by this method.
#' @param ... Further arguments (ignored).
#' @return \code{fortify} retruns a data frame for \code{ggplot2}.
#'
#' @examples
#' library(ggplot2)
#' data(B500)
#' roc_curve <- create_roc(scores = B500$good_er_scores,
#'                         obslabs = B500$labels)
#' df <- fortify(roc_curve)
#' p <- ggplot2::ggplot(df, aes(x = x, y = y))
#' p <- p + geom_line()
#' p
fortify.roc_curve <- function(model, data = NULL, ...) {
  # === Check package availability  ===
  .load_ggplot2()

  # === Validate input arguments ===
  .validate(model)

  # === Prepare a data frame for ggplot2 ===
  df <- data.frame(x = model[["x"]], y = model[["y"]])

}

#' Convert a prc_curve object to a data frame for ggplot2.
#'
#' \code{fortify} takes a \code{prc_curve} object generated by
#' \code{\link{create_prc}} and convert it to a data frame .
#' \code{fortify} requires \code{\link[ggplot2]{ggplot2}}.
#'
#' @param model \code{prc_curve} object generated by
#'   \code{\link{create_prc}}.
#' @param data Not used by this method.
#' @param ... Further arguments (ignored).
#' @return \code{fortify} retruns a data frame for \code{ggplot2}.
#'
#' @examples
#' library(ggplot2)
#' data(B500)
#' prc_curve <- create_prc(scores = B500$good_er_scores,
#'                         obslabs = B500$labels)
#' df <- fortify(prc_curve)
#' p <- ggplot2::ggplot(df, aes(x = x, y = y))
#' p <- p + geom_line()
#' p
fortify.prc_curve <- function(model, data = NULL, ...) {
  fortify.roc_curve(model, data, ...)
}

#' Convert a curves object to a data frame for ggplot2.
#'
#' \code{fortify} takes a \code{curves} object generated by
#' \code{\link{evalmod}} or \code{\link{create_curves}}
#' and convert it to a data frame .
#' \code{fortify} requires \code{\link[ggplot2]{ggplot2}}.
#'
#' @param model \code{curves} object generated by
#'   \code{\link{evalmod}} or \code{\link{create_curves}}.
#' @param data Not used by this method.
#' @param ... Further arguments (ignored).
#' @return \code{fortify} retruns a data frame for \code{ggplot2}.
#'
#' @examples
#' library(ggplot2)
#' data(B500)
#' curves <- create_curves(scores = B500$good_er_scores,
#'                         obslabs = B500$labels)
#' df <- fortify(curves)
#' p_roc <- ggplot2::ggplot(subset(df, group == "ROC"), aes(x = x, y = y))
#' p_roc <- p_roc + geom_line()
#' p_roc
#'
#' p_prc <- ggplot2::ggplot(subset(df, group == "PRC"), aes(x = x, y = y))
#' p_prc <- p_prc + geom_line()
#' p_prc
fortify.curves <- function(model, data = NULL, ...) {
  # === Check package availability  ===
  .load_ggplot2()

  # === Validate input arguments ===
  .validate(model)

  # === Prepare a data frame for ggplot2 ===
  roc_df <- fortify(model[["roc"]])
  prc_df <- fortify(model[["prc"]])
  x <- c(roc_df[["x"]], prc_df[["x"]])
  y <- c(roc_df[["y"]], prc_df[["y"]])
  group = factor(c(rep("ROC", length(roc_df[["x"]])),
                   rep("PRC", length(prc_df[["x"]]))))
  df <- data.frame(x = x, y = y, group = group)
}

# Convert a mroc_curves object to a data frame for ggplot2.
fortify.mroc_curves <- function(model, data = NULL, ...) {
  # === Check package availability  ===
  .load_ggplot2()

  # === Validate input arguments ===
  .validate(model)

  # === Prepare a data frame for ggplot2 ===
  curves = model[["curves"]]
  df <- NULL
  for (nm in names(curves)) {
    x = curves[[nm]][["x"]]
    y = curves[[nm]][["y"]]
    model_name = factor(rep(nm, length(x)), levels = names(curves))
    df <- rbind(df, data.frame(x = x, y = y, model_name = model_name))
  }

  df
}

# Convert a mprc_curves object to a data frame for ggplot2.
fortify.mprc_curves <- function(model, data = NULL, ...) {
  fortify.mroc_curves(model, data = NULL, ...)
}

#' Convert an mcurves object to a data frame for ggplot2.
#'
#' \code{fortify} takes an \code{mcurves} object generated by
#' \code{\link{evalmulti}} and convert it to a data frame .
#' \code{fortify} requires \code{\link[ggplot2]{ggplot2}}.
#'
#' @param model \code{mcurves} object generated by
#'   \code{\link{evalmulti}}.
#' @param data Not used by this method.
#' @param ... Further arguments (ignored).
#' @return \code{fortify} retruns a data frame for \code{ggplot2}.
#'
#' @examples
#' library(ggplot2)
#' s1 <- c(1, 2, 3, 4)
#' s2 <- c(5, 6, 7, 8)
#' s3 <- c(2, 4, 6, 8)
#' mscores <- combine_scores(s1, s2, s3)
#'
#' l1 <- c(1, 0, 1, 1)
#' l2 <- c(1, 1, 0, 0)
#' l3 <- c(0, 1, 0, 1)
#' mobslabs <- combine_obslbs(l1, l2, l3)
#'
#' mdat <- create_mdat(mscores, mobslabs)
#'
#' mcurves <- evalmulti(mdat)
#' df <- fortify(mcurves)
#'
#' df_roc <- subset(df, group == "ROC")
#' p_roc <- ggplot2::ggplot(df_roc, aes(x = x, y = y, color = model_name))
#' p_roc <- p_roc + geom_line()
#' p_roc
#'
#' df_prc <- subset(df, group == "PRC")
#' p_prc <- ggplot2::ggplot(df_prc, aes(x = x, y = y, color = model_name))
#' p_prc <- p_prc + geom_line()
#' p_prc
fortify.mcurves <- function(model, data = NULL, ...) {
  # === Check package availability  ===
  .load_ggplot2()

  # === Validate input arguments ===
  .validate(model)

  # === Prepare a data frame for ggplot2 ===
  roc_df <- fortify(model[["mroc_curves"]])
  prc_df <- fortify(model[["mprc_curves"]])
  x <- c(roc_df[["x"]], prc_df[["x"]])
  y <- c(roc_df[["y"]], prc_df[["y"]])
  model_name <- factor(c(roc_df[["model_name"]], prc_df[["model_name"]]),
                       labels = levels(roc_df[["model_name"]]))
  group = factor(c(rep("ROC", length(roc_df[["x"]])),
                   rep("PRC", length(prc_df[["x"]]))))

  df <-data.frame(x = x, y = y, group = group, model_name = model_name)
}
