#' Convert a fmdat object to a data frame for ggplot2.
#'
#' \code{fortify} takes a \code{fmdat} object generated by
#' \code{\link{reformat_data}} and convert it to a data frame .
#' \code{fortify} requires \code{\link[ggplot2]{ggplot2}}.
#'
#' @param model \code{fmdat} object generated by
#'   \code{\link{reformat_data}}.
#' @param data Not used by this method.
#' @param ... Further arguments (ignored).
#' @return \code{fortify} retruns a data frame for \code{ggplot2}.
#'
#' @examples
#' library(ggplot2)
#' data(B500)
#' fmdat <- reformat_data(B500$good_er_scores, B500$labels)
#' df <- fortify(fmdat)
#' p <- ggplot(df, aes(x = x, y = y, color = x))
#' p <- p + geom_jitter()
#' p <- p + coord_flip()
#' p
fortify.fmdat <- function(model, data = NULL, ...) {
  # === Check package availability  ===
  .load_ggplot2()

  # === Validate input arguments ===
  .validate(model)

  # === Prepare a data frame for ggplot2 ===
  df <- data.frame(x = model[["olabs"]],
                   y = model[["ranks"]])
}

#' Convert a cmats object to a data frame for ggplot2.
#'
#' \code{fortify} takes a \code{cmats} object generated by
#' \code{\link{create_confmats}} and convert it to a data frame .
#' \code{fortify} requires \code{\link[ggplot2]{ggplot2}}.
#'
#' @param model \code{cmats} object generated by
#'   \code{\link{create_confmats}}.
#' @param data Not used by this method.
#' @param ... Further arguments (ignored).
#' @return \code{fortify} retruns a data frame for \code{ggplot2}.
#'
#' @examples
#' library(ggplot2)
#' data(B500)
#' cmat <- create_confmats(pscores = B500$good_er_scores,
#'                         olabs = B500$labels)
#' df <- fortify(cmat)
#' p <- ggplot2::ggplot(df, aes(x = x, y = y, color = group))
#' p <- p + geom_line()
#' p
fortify.cmats <- function(model, data = NULL, ...) {
  # === Check package availability  ===
  .load_ggplot2()

  # === Validate input arguments ===
  .validate(model)

  # === Prepare a data frame for ggplot2 ===
  n <- length(model[["ranks"]])
  df <- data.frame(x = rep(1:length(model[["ranks"]]), 4),
                   y = c(model[["tp"]],
                         model[["fn"]],
                         model[["fp"]],
                         model[["tn"]]),
                   group = factor(c(rep("TPs", n), rep("FNs", n),
                                    rep("FPs", n), rep("TNs", n)),
                                  levels = c("TPs", "FNs", "FPs", "TNs")))
}

#' Convert a pevals object to a data frame for ggplot2.
#'
#' \code{fortify} takes a \code{pevals} object generated by
#' \code{\link{calc_measures}} and convert it to a data frame .
#' \code{fortify} requires \code{\link[ggplot2]{ggplot2}}.
#'
#' @param model \code{pevals} object generated by
#'   \code{\link{calc_measures}}.
#' @param data Not used by this method.
#' @param ... Further arguments (ignored).
#' @return \code{fortify} retruns a data frame for \code{ggplot2}.
#'
#' @examples
#' library(ggplot2)
#' data(B500)
#' pevals <- calc_measures(pscores = B500$good_er_scores,
#'                         olabs = B500$labels)
#' df <- fortify(pevals)
#' p <- ggplot(df, aes(x = x, y = y))
#' p <- p + facet_wrap(~ group, ncol = 2)
#' p <- p + geom_line()
#' p
fortify.pevals <- function(model, data = NULL, ...) {
  # === Check package availability  ===
  .load_ggplot2()

  # === Validate input arguments ===
  .validate(model)

  # === Prepare a data frame for ggplot2 ===
  n <- length(model[["error"]])
  df <- data.frame(x = rep(1:n, 6),
                   y = c(model[["error"]],
                         model[["accuracy"]],
                         model[["specificity"]],
                         model[["sensitivity"]],
                         1 - model[["specificity"]],
                         model[["precision"]]),
                   group = factor(c(rep("error", n),
                                    rep("accuracy", n),
                                    rep("specificity", n),
                                    rep("sensitivity", n),
                                    rep("1 - specificity", n),
                                    rep("precision", n)),
                                  levels = c("error", "accuracy",
                                             "specificity", "sensitivity",
                                             "1 - specificity",
                                             "precision")))
}

# Convert a roc_curve object to a data frame for ggplot2
fortify.roc_curve <- function(model, data = NULL, ...) {
  # === Check package availability  ===
  .load_ggplot2()

  # === Validate input arguments ===
  .validate(model)

  # === Prepare a data frame for ggplot2 ===
  df <- data.frame(x = model[["x"]], y = model[["y"]])

}

# Convert a prc_curve object to a data frame for ggplot2
fortify.prc_curve <- function(model, data = NULL, ...) {
  fortify.roc_curve(model, data, ...)
}
