#' Convert mmcurves object to a data frame for ggplot2.
#'
#' \code{fortify} converts an \code{mmcurves} object generated by
#'   \code{\link{evalmods_m}} to a data frame for
#'   \code{\link[ggplot2]{ggplot2}}.
#'
#' @param model \code{mmcurves} object generated by
#'   \code{\link{evalmods_m}}.
#'
#' @param ... Not used by this method.
#'
#' @return The \code{fortify} function retruns a data frame for
#'   \code{\link[ggplot2]{ggplot2}}.
#'
#' @seealso \code{\link{evalmods_m}} for generating \code{smcurves}.
#'  \code{\link{autoplot.mmcurves}} for plotting curves.
#'
#' @examples
#'
#' ## Load ggplot2
#' library(ggplot2)
#'
#' ## Prepare input data
#' samps <- create_sim_samples(10, 100, 100, "all")
#' mdat <- mmdata(samps[["scores"]], samps[["labels"]],
#'                modnames = samps[["modnames"]],
#'                setids = samps[["setids"]])
#'
#' ## Convert sscurve object to a data frame
#' curves <- evalmods_m(mdat)
#' df <- fortify(curves)
#'
#' ## Fortified data frame can be used for plotting a ROC curve
#' df_roc <- subset(df, group == "ROC")
#' p_roc <- ggplot(df_roc, aes(x = x, y = y, ymin = ymin, ymax = ymax,
#'                             color = modname))
#' p_roc <- p_roc + geom_smooth(stat = "identity")
#' p_roc
#'
#' ## Fortified data frame can be used for plotting a Precision-Recall curve
#' df_prc <- subset(df, group == "PRC")
#' p_prc <- ggplot(df_roc, aes(x = x, y = y, ymin = ymin, ymax = ymax,
#'                             color = modname))
#' p_prc <- p_roc + geom_smooth(stat = "identity")
#' p_prc
#'
#' @export
fortify.mmcurves <- function(model, ...) {
  # === Check package availability  ===
  .load_ggplot2()

  # === Validate input arguments ===
  .validate(model)

  # === Prepare a data frame for ggplot2 ===
  roc_df <- ggplot2::fortify(model[["rocs"]])
  prc_df <- ggplot2::fortify(model[["prcs"]])

  x <- c(roc_df[["x"]], prc_df[["x"]])
  y <- c(roc_df[["y"]], prc_df[["y"]])
  ymin <- c(roc_df[["ymin"]], prc_df[["ymin"]])
  ymax <- c(roc_df[["ymax"]], prc_df[["ymax"]])
  group = factor(c(rep("ROC", length(roc_df[["x"]])),
                   rep("PRC", length(prc_df[["x"]]))))
  modname <- factor(c(roc_df[["modname"]], prc_df[["modname"]]),
                    labels = levels(roc_df[["modname"]]))

  df <- data.frame(x = x, y = y, ymin = ymin, ymax = ymax,
                   modname = modname, group = group)
}

#
# Convert a mroc_curves object to a data frame for ggplot2.
#
fortify.mmroc <- function(model, ...) {
  # === Check package availability  ===
  .load_ggplot2()

  # === Validate input arguments ===
  .validate(model)

  # === Prepare a data frame for ggplot2 ===
  avgcurves <- attr(model, "avgcurves")
  df <- NULL
  modnames <- attr(avgcurves, "uniq_modnames")
  for (i in seq_along(avgcurves)) {
    x = avgcurves[[i]][["x"]]
    y = avgcurves[[i]][["y_avg"]]
    ymin = avgcurves[[i]][["y_ci_l"]]
    ymax = avgcurves[[i]][["y_ci_h"]]
    modname = factor(rep(modnames[i], length(x)), levels = modnames)
    df <- rbind(df, data.frame(x = x, y = y, ymin = ymin, ymax = ymax,
                               modname = modname))
  }

  df
}

#
# Convert a mprc_curves object to a data frame for ggplot2.
#
fortify.mmprc <- function(model, ...) {
  fortify.mmroc(model, use_raw, ...)
}
