#' Convert sscurves to a data frame for ggplot2.
#'
#' \code{fortify} converts an \code{sscurves} object generated by
#'   \code{\link{evalmod}} to a data frame for
#'   \code{\link[ggplot2]{ggplot2}}.
#'
#' @param model \code{sscurves} object generated by
#'   \code{\link{evalmod}}.
#'
#' @param ... Not used by this method.
#'
#' @return The \code{fortify} function retruns a data frame for
#'   \code{\link[ggplot2]{ggplot2}}.
#'
#' @seealso \code{\link{evalmod}} for generating \code{sscurves}.
#'  \code{\link{autoplot.sscurves}} for plotting curves.
#'
#' @examples
#'
#' ## Load ggplot2
#' library(ggplot2)
#'
#' ## Load a dataset with 10 positives and 10 negatives
#' data(P10N10)
#'
#' ## Convert sscurve object to a data frame
#' curves <- evalmod(scores = P10N10$scores, labels = P10N10$labels)
#' df <- fortify(curves)
#'
#' ## Fortified data frame can be used for plotting a ROC curve
#' p_roc <- ggplot(subset(df, group == "ROC"), aes(x = x, y = y))
#' p_roc <- p_roc + geom_line()
#' p_roc
#'
#' ## Fortified data frame can be used for plotting a Precision-Recall curve
#' p_prc <- ggplot(subset(df, group == "PRC"), aes(x = x, y = y))
#' p_prc <- p_prc + geom_line()
#' p_prc
#'
#' @export
fortify.sscurves <- function(model, ...) {
  # === Check package availability  ===
  .load_ggplot2()

  # === Validate input arguments ===
  .validate(model)

  # === Prepare a data frame for ggplot2 ===
  roc_df <- ggplot2::fortify(model[["rocs"]])
  prc_df <- ggplot2::fortify(model[["prcs"]])
  x <- c(roc_df[["x"]], prc_df[["x"]])
  y <- c(roc_df[["y"]], prc_df[["y"]])
  group = factor(c(rep("ROC", length(roc_df[["x"]])),
                   rep("PRC", length(prc_df[["x"]]))))
  df <- data.frame(x = x, y = y, group = group)
}

#
# Convert a roc_curve object to a data frame for ggplot2
#
fortify.ssroc <- function(model, ...) {
  ggplot2::fortify(model[[1]], ...)
}

#
# Convert a prc_curve object to a data frame for ggplot2
#
fortify.ssprc <- function(model, ...) {
  ggplot2::fortify(model[[1]], ...)
}
