#' Plot ROC and Precision-Recall curves for multiple models
#'
#' \code{plot} plots ROC and Precion-Recall curves.
#'
#' @param x \code{sscurves} object generated by
#'   \code{\link{evalmod}}.
#'
#' @param y Not used by this method.
#'
#' @param curvetype a character vector with the following curve types
#'   \itemize{
#'     \item "ROC"
#'     \item "PRC"
#'     \item c("ROC", "PRC")
#'   }
#'
#' @param show_legend A boolean value to indicate whether the legend is added.
#'
#' @param ... Not used by this method.
#'
#' @return \code{plot} shows a plot and returns NULL.
#'
#' @seealso \code{\link{evalmulti}} for generating \code{mscurves}.
#'   \code{\link{autoplot.mscurves}} for plotting curves with
#'   \code{\link[ggplot2]{ggplot2}}.
#'
#'  @examples
#'
#' ## Create sample datasets with 100 positives and 100 negatives
#' samps <- create_sim_samples(1, 100, 100, "all")
#' mdat <- mmdata(samps[["scores"]], samps[["labels"]],
#'                model_names = samps[["model_names"]],
#'                data_nos = samps[["data_nos"]])
#'
#' ## Generate an mscurve object
#' curves <- evalmulti(mdat)
#'
#' ## Plot both ROC and Precision-Recall curves
#' plot(curves)
#'
#' ## Plot a ROC curve
#' plot(curves, curvetype = "ROC")
#'
#' ## Plot a Precision-Recall curve
#' plot(curves, curvetype = "PRC")
#'
#' ## Hide the legend
#' plot(curves, show_legend = FALSE)
#'
#' @export
plot.mscurves <- function(x, curvetype = c("ROC", "PRC"),
                          show_legend = TRUE, ...) {

  # === Validate input arguments ===
  .check_show_legend(show_legend)
  .validate(x)

  if (!is.atomic(curvetype) || !is.character(curvetype)
      || length(curvetype) > 2
      || length(setdiff(curvetype, c("ROC", "PRC"))) != 0)
  {
    stop("Invalid 'curvetype' value")
  }

  # === Create a plot ===
  show_legend2 <- show_legend
  if ("ROC" %in% curvetype && "PRC" %in% curvetype) {
    if (show_legend) {
      m <- matrix(c(1, 2, 3, 3), nrow = 2, ncol = 2, byrow = TRUE)
      layout(mat = m, heights = c(0.85, 0.15))
    } else {
      m <- matrix(c(1, 2), nrow = 1, ncol = 2)
      layout(mat = m)
    }
    on.exit(layout(1), add = TRUE)
    show_legend2 <- FALSE
  }

  if ("ROC" %in% curvetype) {
    plot(x[["rocs"]], show_legend = show_legend2)
  }

  if ("PRC" %in% curvetype) {
    plot(x[["prcs"]], show_legend = show_legend2)
  }

  if ("ROC" %in% curvetype && "PRC" %in% curvetype) {
    .show_legend(x, show_legend)
  }
}

#
# Plot ROC curves
#
plot.msroc <- function(x, show_legend = TRUE, ...) {
  old_pty <- par(pty = "s")
  on.exit(par(old_pty), add = TRUE)

  if (show_legend) {
    m <- matrix(c(1, 2), nrow = 2, ncol = 1)
    layout(mat = m, heights = c(0.85, 0.15))
    on.exit(layout(1), add = TRUE)
  }

  # === Create a plot ===
  .matplot_wrapper(x, "ROC", "1 - Specificity", "Sensitivity")
  abline(a = 0, b = 1, col = "grey", lty = 3)

  .show_legend(x, show_legend)

}

#
# Plot Precision-Recall curves
#
plot.msprc <- function(x, show_legend = TRUE, ...) {
  old_pty <- par(pty = "s")
  on.exit(par(old_pty), add = TRUE)

  if (show_legend) {
    m <- matrix(c(1, 2), nrow = 2, ncol = 1)
    layout(mat = m, heights = c(0.85, 0.15))
    on.exit(layout(1), add = TRUE)
  }

  # === Create a plot ===
  np <- attr(x[[1]], "np")
  nn <- attr(x[[1]], "nn")

  .matplot_wrapper(x, "Precision-Recall", "Recall", "Precision")
  abline(h = np / (np + nn), col = "grey", lty = 3)

  .show_legend(x, show_legend)
}

#
# Show legend
#
.show_legend <- function(obj, show_legend) {
  if (show_legend) {
    old_mar <- par(mar = c(0, 0, 0, 0))
    on.exit(par(old_mar), add = TRUE)
    old_pty <- par(pty = "m")
    on.exit(par(old_pty), add = TRUE)

    model_names <- attr(obj, "model_names")
    plot(1, type = "n", axes = FALSE, xlab = "", ylab = "")
    legend(x = "top", lty = 1,
           legend = model_names,
           col = rainbow(length(model_names)),
           horiz = TRUE)
  }
}

#
# matplot wrapper
#
.matplot_wrapper <- function(obj, curve_name, xlab, ylab) {
  # === Validate input arguments ===
  .validate(obj)

  # === Create a plot ===
  np <- attr(obj[[1]], "np")
  nn <- attr(obj[[1]], "nn")

  mats <- .make_matplot_mats(obj)

  matplot(mats[["x"]], mats[["y"]], type = "l", lty = 1,
          col = rainbow(ncol(mats[["x"]])),
          main = paste0(curve_name, " - P: ", np, ", N: ", nn),
          xlab = xlab, ylab = ylab,
          ylim = c(0, 1), xlim = c(0, 1))
}

#
# Make matrices for matplot
#
.make_matplot_mats <- function(obj) {
  ncol <- length(obj)

  max_nrow <- max(unlist(lapply(obj, function(o) length(o[["x"]]))))

  x <- matrix(as.double(NA), nrow = max_nrow, ncol = ncol)
  y <- matrix(as.double(NA), nrow = max_nrow, ncol = ncol)

  for (i in seq_along(obj)) {
    x[1:length(obj[[i]][["x"]]), i] <- obj[[i]][["x"]]
    y[1:length(obj[[i]][["y"]]), i] <- obj[[i]][["y"]]
  }

  list(x = x, y = y)
}
