#' Plot a ROC curve.
#'
#' \code{plot} takes \code{roc_curve} object generated by
#' \code{\link{create_roc}} and plot a ROC curve.
#'
#' @param object \code{roc_curve} object generated by
#'   \code{\link{create_roc}}.
#' @param ... Other arguments (ignored).
#'
#' @examples
#' data(B500)
#' roc_curve <- create_roc(scores = B500$good_er_scores,
#'                         obslabs = B500$labels)
#' plot(roc_curve)
plot.roc_curve <- function(object, ...) {
  old_pty <- par(pty = "s")

  # === Validate input arguments ===
  .validate(object)

  # === Create a plot ===
  np <- attr(object, "np")
  nn <- attr(object, "nn")

  plot(object[["x"]], object[["y"]], type = "l",
       main = paste("ROC - P: ", np, ", N: ", nn, sep=""),
       xlab = "1 - Specificity", ylab = "Sensitivity")
  abline(a = 0, b = 1, col = "grey", lty = 3)

  par(old_pty)
}

#' Plot a Precision-Recall curve.
#'
#' \code{plot} takes \code{prc_curve} object generated by
#' \code{\link{create_prc}} and plot a ROC curve.
#'
#' @param object \code{prc_curve} object generated by
#'   \code{\link{create_prc}}.
#' @param ... Other arguments (ignored).
#'
#' @examples
#' data(B500)
#' prc_curve <- create_prc(scores = B500$good_er_scores,
#'                         obslabs = B500$labels)
#' plot(prc_curve)
plot.prc_curve <- function(object, ...) {
  old_pty <- par(pty = "s")

  # === Validate input arguments ===
  .validate(object)

  # === Create a plot ===
  np <- attr(object, "np")
  nn <- attr(object, "nn")

  plot(object[["x"]], object[["y"]], type = "l",
       main = paste("Precision-Recall - P: ", np, ", N: ", nn, sep=""),
       xlab = "Recall", ylab = "Precision",
       ylim = c(0, 1))
  abline(h = np / (np + nn), col = "grey", lty = 3)

  par(old_pty)
}

#' Plot ROC and Precision-Recall curves.
#'
#' \code{plot} takes \code{curves} object generated by
#' \code{\link{create_curves}} and plot ROC and Precion-Recall curves.
#'
#' @param object \code{curves} object generated by
#'   \code{\link{create_curves}}.
#' @param ... Other arguments.
#'
#' @examples
#' data(B500)
#' curves <- create_curves(scores = B500$good_er_scores,
#'                         obslabs = B500$labels)
#' plot(curves)
plot.curves <- function(object, curvetype = c("ROC", "PRC"), ...) {
  old_mfrow <- NULL

  if ("ROC" %in% curvetype && "PRC" %in% curvetype) {
    old_mfrow <- par(mfrow = c(1, 2))
  }

  # === Validate input arguments ===
  .validate(object)

  if (!is.atomic(curvetype) || !is.character(curvetype)
      || length(curvetype) > 2
      || length(setdiff(curvetype, c("ROC", "PRC"))) != 0)
  {
    stop("Invalid 'curvetype' value")
  }

  # === Create a plot ===
  if ("ROC" %in% curvetype) {
    plot(object[["roc"]])
  }

  if ("PRC" %in% curvetype) {
    plot(object[["prc"]])
  }

  if (!is.null(old_mfrow)) {
    par(old_mfrow)
  }
}

# Make matrices for matplot
.make_matplot_mats <- function(obj) {

  nrowx <- length(obj[[1]][["x"]])
  nrowx <- length(obj[[1]][["x"]])
  ncol <- length(names(obj))

  max_nrow <- max(unlist(lapply(obj, function(o) length(o[["x"]]))))

  x <- matrix(as.double(NA), nrow = max_nrow, ncol = ncol)
  y <- matrix(as.double(NA), nrow = max_nrow, ncol = ncol)

  for (i in seq_along(obj)) {
    x[1:length(obj[[i]][["x"]]), i] <- obj[[i]][["x"]]
    y[1:length(obj[[i]][["y"]]), i] <- obj[[i]][["y"]]
  }

  list(x = x, y = y)
}

# matplot wrapper
.matplot_wrapper <- function(object, curve_name, xlab, ylab) {
  # === Validate input arguments ===
  .validate(object)

  # === Create a plot ===
  np <- object[["curves"]][[1]][["pos_num"]]
  nn <- object[["curves"]][[1]][["neg_num"]]

  mats <- .make_matplot_mats(object[["curves"]])

  matplot(mats[["x"]], mats[["y"]], type = "l", lty = 1,
          col = rainbow(ncol(mats[["x"]])),
          main = paste0(curve_name, " - P: ", np, ", N: ", nn),
          xlab = "1 - Specificity", ylab = "Sensitivity")
}

# prepare layout for legend
.prepare_layout <- function(show_legend) {
  if (show_legend) {
    m <- matrix(c(1, 2), nrow = 2, ncol = 1)
    layout(mat = m, heights = c(0.85, 0.15))
  }
}

# show legend
.show_legend <- function(object, show_legend) {
  if (show_legend) {
    model_names <- names(object[["curves"]])
    print(model_names)
    par(mar = c(0, 0, 0, 0))
    par(pty = "m")
    plot(1, type = "n", axes = FALSE, xlab = "", ylab = "")
    legend(x = "top", lty = 1,
           legend = model_names,
           col = rainbow(length(model_names)),
           horiz = TRUE)
  }
}

# Plot ROC curves
plot.mroc_curves <- function(object, show_legend = TRUE, ...) {
  old_pty <- par(pty = "s")
  old_mar <- par("mar")

  .prepare_layout(show_legend)

  # === Create a plot ===
  .matplot_wrapper(object, "ROC", "1 - Specificity", "Sensitivity")
  abline(a = 0, b = 1, col = "grey", lty = 3)

  .show_legend(object, show_legend)

  par(old_pty)
  par(mar = old_mar)
}

# Plot Precision-Recall curves
plot.mprc_curves <- function(object, show_legend = TRUE, ...) {
  old_pty <- par(pty = "s")
  old_mar <- par("mar")

  .prepare_layout(show_legend)

  # === Create a plot ===
  np <- object[["curves"]][[1]][["pos_num"]]
  nn <- object[["curves"]][[1]][["neg_num"]]

  .matplot_wrapper(object, "Precision-Recall", "Recall", "Precision")
  abline(h = np / (np + nn), col = "grey", lty = 3)

  .show_legend(object, show_legend)

  par(old_pty)
  par(mar = old_mar)
}

#' Plot ROC and Precision-Recall curves.
#'
#' \code{autoplot} takes \code{mcurves} object generated by
#' \code{\link{evalmulti}} and plot ROC and Precion-Recall curves.
#' \code{autoplot} requires \code{\link[ggplot2]{ggplot2}} and
#' \code{\link[gridExtra]{grid.arrange}}.
#'
#' @param object \code{mcurves} object generated by
#'   \code{\link{evalmulti}}.
#' @param ... Other arguments (ignored).
#' @return \code{autoplot} automatically shows a plot or returns
#'   a \code{ggplot} object.
#'
#' @examples
#' s1 <- c(1, 2, 3, 4)
#' s2 <- c(5, 6, 7, 8)
#' s3 <- c(2, 4, 6, 8)
#' mscores <- combine_scores(s1, s2, s3)
#'
#' l1 <- c(1, 0, 1, 1)
#' l2 <- c(1, 1, 0, 0)
#' l3 <- c(0, 1, 0, 1)
#' mobslabs <- combine_obslbs(l1, l2, l3)
#'
#' mdat <- create_mdat(mscores, mobslabs)
#'
#' mcurves <- evalmulti(mdat)
#' plot(mcurves)
plot.mcurves <- function(object, curvetype = c("ROC", "PRC"), ...) {
  old_mar <- par("mar")

  if ("ROC" %in% curvetype && "PRC" %in% curvetype) {
    m <- matrix(c(1, 2, 3, 3), nrow = 2, ncol = 2, byrow = TRUE)
    layout(mat = m, heights = c(0.85, 0.15))
  }

  # === Validate input arguments ===
  .validate(object)

  if (!is.atomic(curvetype) || !is.character(curvetype) || length(curvetype) > 2
      || length(setdiff(curvetype, c("ROC", "PRC"))) != 0)
  {
    stop("Invalid 'curvetype' value")
  }

  # === Create a plot ===
  if ("ROC" %in% curvetype) {
    plot(object[["mroc_curves"]], show_legend = FALSE)
  }

  if ("PRC" %in% curvetype) {
    plot(object[["mprc_curves"]], show_legend = FALSE)
  }

  if ("ROC" %in% curvetype && "PRC" %in% curvetype) {
    .show_legend(object[["mroc_curves"]], TRUE)
  }

  par(mar = old_mar)
}
