#' Plot ROC and Precision-Recall curves for a single model with multiple datasets
#'
#' The \code{plot} function plots ROC and Precion-Recall curves.
#'
#' @param x \code{smcurves} object generated by
#'   \code{\link{evalmod_m}}.
#'
#' @param curvetype a character vector with the following curve types.
#'   \itemize{
#'     \item "ROC"
#'     \item "PRC"
#'     \item c("ROC", "PRC")
#'   }
#'
#' @param show_legend A boolean value to indicate whether the legend is added.
#'
#' @param ... Not used by this method.
#'
#' @return The \code{plot} function shows a plot and returns NULL.
#'
#' @seealso \code{\link{evalmods}} for generating \code{smcurves}.
#'   \code{\link{autoplot.smcurves}} for plotting curves with
#'   \code{\link[ggplot2]{ggplot2}}.
#'
#' @examples
#'
#' ## Prepare input data
#' samps <- create_sim_samples(10, 100, 100, "poor_er")
#' mdat <- mmdata(samps[["scores"]], samps[["labels"]],
#'                model_names = samps[["model_names"]],
#'                setids = samps[["setids"]])
#'
#' ## Generate an mscurve object
#' curves <- evalmod_m(mdat)
#'
#' ## Plot both ROC and Precision-Recall curves
#' plot(curves)
#'
#' ## Plot a ROC curve
#' plot(curves, curvetype = "ROC")
#'
#' ## Plot a Precision-Recall curve
#' plot(curves, curvetype = "PRC")
#'
#' @export
plot.smcurves <- function(x, curvetype = c("ROC", "PRC"), show_ci = TRUE,
                          show_raw = FALSE, ...) {

  # === Validate input arguments ===
  .validate(x)
  .check_curvetype(curvetype)

  # === Create a plot ===
  if ("ROC" %in% curvetype && "PRC" %in% curvetype) {
    m <- matrix(c(1, 2), nrow = 1, ncol = 2)
    layout(mat = m)
    on.exit(layout(1), add = TRUE)
  }

  if ("ROC" %in% curvetype) {
    plot(x[["rocs"]], show_ci, show_raw, ...)
  }

  if ("PRC" %in% curvetype) {
    plot(x[["prcs"]], show_ci, show_raw, ...)
  }
}

#
# Plot ROC curves
#
plot.smroc <- function(x, show_ci = TRUE, show_raw = FALSE, ...) {
  old_pty <- par(pty = "s")
  on.exit(par(old_pty), add = TRUE)

  # === Create a plot ===
  if (show_raw) {
    .matplot_wrapper(x, "ROC", "1 - Specificity", "Sensitivity", "single")
  } else {
  .plot_avg(x, "ROC", "1 - Specificity", "Sensitivity", show_ci)
  }

  abline(a = 0, b = 1, col = "grey", lty = 3)
}

#
# Plot Precision-Recall curves
#
plot.smprc <- function(x, show_ci = TRUE, show_raw = FALSE, ...) {
  old_pty <- par(pty = "s")
  on.exit(par(old_pty), add = TRUE)

  # === Create a plot ===
  np <- attr(x[[1]], "np")
  nn <- attr(x[[1]], "nn")

  if (show_raw) {
    .matplot_wrapper(x, "Precision-Recall", "Recall", "Precision", "single")
  } else {
    .plot_avg(x, "Precision-Recall", "Recall", "Precision", show_ci)
  }

  abline(h = np / (np + nn), col = "grey", lty = 3)

}

