#' Plot ROC and Precision-Recall curves of a single model
#'
#' The \code{plot} function plots ROC and Precion-Recall curves.
#'
#' @param x \code{sscurves} object generated by
#'   \code{\link{evalmod}}.
#'
#' @param curvetype a character vector with the following curve types.
#'   \itemize{
#'     \item "ROC"
#'     \item "PRC"
#'     \item c("ROC", "PRC")
#'   }
#'
#' @param ... Not used by this method.
#'
#' @return The \code{plot} function shows a plot and returns NULL.
#'
#' @seealso \code{\link{evalmod}} for generating \code{sscurves}.
#'   \code{\link{autoplot.sscurves}} for plotting curves with
#'   \code{\link[ggplot2]{ggplot2}}.
#'
#' @examples
#'
#' ## Load a dataset with 10 positives and 10 negatives
#' data(P10N10)
#'
#' ## Generate an sscurve object
#' curves <- evalmod(scores = P10N10$scores, labels = P10N10$labels)
#'
#' ## Plot both ROC and Precision-Recall curves
#' plot(curves)
#'
#' ## Plot a ROC curve
#' readline("Press <Enter> to continue...")
#' plot(curves, curvetype = "ROC")
#'
#' ## Plot a Precision-Recall curve
#' readline("Press <Enter> to continue...")
#' plot(curves, curvetype = "PRC")
#'
#' @export
plot.sscurves <- function(x, curvetype = c("ROC", "PRC"), ...) {

  .plot_multi(x, curvetype = curvetype, show_ci = FALSE, all_curves = TRUE,
              add_np_nn = TRUE, show_legend = FALSE, ...)

}

#' Plot ROC and Precision-Recall curves for multiple models
#'
#' The \code{plot} function plots ROC and Precion-Recall curves.
#'
#' @param x \code{sscurves} object generated by
#'   \code{\link{evalmod}}.
#'
#' @param curvetype a character vector with the following curve types.
#'   \itemize{
#'     \item "ROC"
#'     \item "PRC"
#'     \item c("ROC", "PRC")
#'   }
#'
#' @param show_legend A boolean value to indicate whether the legend is added.
#'
#' @param ... Not used by this method.
#'
#' @return The \code{plot} function shows a plot and returns NULL.
#'
#' @seealso \code{\link{evalmods}} for generating \code{mscurves}.
#'   \code{\link{autoplot.mscurves}} for plotting curves with
#'   \code{\link[ggplot2]{ggplot2}}.
#'
#' @examples
#'
#' ## Create sample datasets with 100 positives and 100 negatives
#' samps <- create_sim_samples(1, 100, 100, "all")
#' mdat <- mmdata(samps[["scores"]], samps[["labels"]],
#'                modnames = samps[["modnames"]],
#'                dsids = samps[["dsids"]])
#'
#' ## Generate an mscurve object
#' curves <- evalmod(mdat)
#'
#' ## Plot both ROC and Precision-Recall curves
#' plot(curves)
#'
#' ## Plot a ROC curve
#' plot(curves, curvetype = "ROC")
#'
#' ## Plot a Precision-Recall curve
#' plot(curves, curvetype = "PRC")
#'
#' ## Hide the legend
#' plot(curves, show_legend = FALSE)
#'
#' @export
plot.mscurves <- function(x, curvetype = c("ROC", "PRC"),
                          show_legend = TRUE, ...) {

  .plot_multi(x, curvetype = curvetype, show_ci = FALSE, all_curves = TRUE,
              add_np_nn = TRUE, show_legend = show_legend, ...)
}

#' Plot ROC and Precision-Recall curves for a single model with multiple datasets
#'
#' The \code{plot} function plots ROC and Precion-Recall curves.
#'
#' @param x \code{smcurves} object generated by
#'   \code{\link{evalmod_m}}.
#'
#' @param curvetype a character vector with the following curve types.
#'   \itemize{
#'     \item "ROC"
#'     \item "PRC"
#'     \item c("ROC", "PRC")
#'   }
#'
#' @param show_legend A boolean value to indicate whether the legend is added.
#'
#' @param ... Not used by this method.
#'
#' @return The \code{plot} function shows a plot and returns NULL.
#'
#' @seealso \code{\link{evalmods}} for generating \code{smcurves}.
#'   \code{\link{autoplot.smcurves}} for plotting curves with
#'   \code{\link[ggplot2]{ggplot2}}.
#'
#' @examples
#'
#' ## Prepare input data
#' samps <- create_sim_samples(10, 100, 100, "poor_er")
#' mdat <- mmdata(samps[["scores"]], samps[["labels"]],
#'                modnames = samps[["modnames"]],
#'                dsids = samps[["dsids"]])
#'
#' ## Generate an mscurve object
#' curves <- evalmod(mdat)
#'
#' ## Plot both ROC and Precision-Recall curves
#' plot(curves)
#'
#' ## Plot a ROC curve
#' plot(curves, curvetype = "ROC")
#'
#' ## Plot a Precision-Recall curve
#' plot(curves, curvetype = "PRC")
#'
#' @export
plot.smcurves <- function(x, curvetype = c("ROC", "PRC"), show_ci = TRUE,
                          all_curves = FALSE, ...) {

  .plot_multi(x, curvetype = curvetype, show_ci = show_ci,
              all_curves = all_curves, add_np_nn = TRUE,
              show_legend = FALSE, ...)

}

#' Plot ROC and Precision-Recall curves for multiple models with multiple datasets
#'
#' The \code{plot} function plots ROC and Precion-Recall curves.
#'
#' @param x \code{smcurves} object generated by
#'   \code{\link{evalmods_m}}.
#'
#' @param curvetype a character vector with the following curve types.
#'   \itemize{
#'     \item "ROC"
#'     \item "PRC"
#'     \item c("ROC", "PRC")
#'   }
#'
#' @param show_legend A boolean value to indicate whether the legend is added.
#'
#' @param ... Not used by this method.
#'
#' @return The \code{plot} function shows a plot and returns NULL.
#'
#' @seealso \code{\link{evalmods}} for generating \code{smcurves}.
#'   \code{\link{autoplot.smcurves}} for plotting curves with
#'   \code{\link[ggplot2]{ggplot2}}.
#'
#' @examples
#'
#' ## Prepare input data
#' samps <- create_sim_samples(10, 100, 100, "all")
#' mdat <- mmdata(samps[["scores"]], samps[["labels"]],
#'                modnames = samps[["modnames"]],
#'                dsids = samps[["dsids"]])
#'
#' ## Generate an mscurve object
#' curves <- evalmod(mdat)
#'
#' ## Plot both ROC and Precision-Recall curves
#' plot(curves)
#'
#' ## Plot a ROC curve
#' plot(curves, curvetype = "ROC")
#'
#' ## Plot a Precision-Recall curve
#' plot(curves, curvetype = "PRC")
#'
#' @export
plot.mmcurves <- function(x, curvetype = c("ROC", "PRC"), show_ci = FALSE,
                          all_curves = FALSE, show_legend = TRUE, ...) {

  .plot_multi(x, curvetype = curvetype, show_ci = show_ci,
              all_curves = all_curves, add_np_nn = TRUE,
              show_legend = show_legend, ...)

}
