#' Plot ROC and Precision-Recall curves.
#'
#' \code{plot} takes \code{curves} object generated by
#' \code{\link{create_curves}} and plot ROC and Precion-Recall curves.
#'
#' @param object \code{curves} object generated by
#'   \code{\link{create_curves}}.
#' @param ... Other arguments.
#'
#' @examples
#' data(P10N10)
#' curves <- evalmod(scores = P10N10$scores, labels = P10N10$labels)
#'
#' plot(curves)
plot.sscurves <- function(x, y = NULL, curvetype = c("ROC", "PRC"), ...) {
  if ("ROC" %in% curvetype && "PRC" %in% curvetype) {
    old_mfrow <- par(mfrow = c(1, 2))
    on.exit(par(old_mfrow), add = TRUE)
  }

  # === Validate input arguments ===
  .validate(x)

  if (!is.atomic(curvetype) || !is.character(curvetype)
      || length(curvetype) > 2
      || length(setdiff(curvetype, c("ROC", "PRC"))) != 0)
  {
    stop("Invalid 'curvetype' value")
  }

  # === Create a plot ===
  if ("ROC" %in% curvetype) {
    plot(x[["rocs"]], ...)
  }

  if ("PRC" %in% curvetype) {
    plot(x[["prcs"]], ...)
  }
}

#' Plot a ROC curve.
#'
#' \code{plot} takes \code{roc_curve} object generated by
#' \code{\link{create_roc}} and plot a ROC curve.
#'
#' @param object \code{roc_curve} object generated by
#'   \code{\link{create_roc}}.
#' @param ... Other arguments (ignored).
#'
#' @examples
#' data(P10N10)
#' curves <- evalmod(scores = P10N10$scores, labels = P10N10$labels)
#'
#' plot(curves[["rocs"]])
plot.ssroc <- function(x, y = NULL, ...) {
  plot(x[[1]], ...)
}

#' Plot a Precision-Recall curve.
#'
#' \code{plot} takes \code{prc_curve} object generated by
#' \code{\link{create_prc}} and plot a ROC curve.
#'
#' @param object \code{prc_curve} object generated by
#'   \code{\link{create_prc}}.
#' @param ... Other arguments (ignored).
#'
#' @examples
#' data(P10N10)
#' curves <- evalmod(scores = P10N10$scores, labels = P10N10$labels)
#'
#' plot(curves[["prcs"]])
plot.ssprc <- function(x, y = NULL, ...) {
  plot(x[[1]], ...)
}
