#' Plot ROC and Precision-Recall curves of a single model
#'
#' \code{plot} plots ROC and Precion-Recall curves.
#'
#' @param x \code{sscurves} object generated by
#'   \code{\link{evalmod}}.
#'
#' @param curvetype a character vector with the following curve types
#'   \itemize{
#'     \item "ROC"
#'     \item "PRC"
#'     \item c("ROC", "PRC")
#'   }
#'
#' @param ... Not used by this method.
#'
#' @return \code{plot} shows a plot and returns NULL.
#'
#' @seealso \code{\link{evalmod}} for generating \code{sscurves}.
#'   \code{\link{autoplot.sscurves}} for plotting curves with
#'   \code{\link[ggplot2]{ggplot2}}.
#'
#' @examples
#'
#' ## Load a dataset with 10 positives and 10 negatives
#' data(P10N10)
#'
#' ## Generate an sscurve object
#' curves <- evalmod(scores = P10N10$scores, labels = P10N10$labels)
#'
#' ## Plot both ROC and Precision-Recall curves
#' plot(curves)
#'
#' ## Plot a ROC curve
#' readline("Press <Enter> to continue...")
#' plot(curves, curvetype = "ROC")
#'
#' ## Plot a Precision-Recall curve
#' readline("Press <Enter> to continue...")
#' plot(curves, curvetype = "PRC")
#'
#' @export
plot.sscurves <- function(x, curvetype = c("ROC", "PRC"), ...) {
  if ("ROC" %in% curvetype && "PRC" %in% curvetype) {
    old_mfrow <- par(mfrow = c(1, 2))
    on.exit(par(old_mfrow), add = TRUE)
  }

  # === Validate input arguments ===
  .validate(x)

  if (!is.atomic(curvetype) || !is.character(curvetype)
      || length(curvetype) > 2
      || length(setdiff(curvetype, c("ROC", "PRC"))) != 0)
  {
    stop("Invalid 'curvetype' value")
  }

  # === Create a plot ===
  if ("ROC" %in% curvetype) {
    plot(x[["rocs"]], ...)
  }

  if ("PRC" %in% curvetype) {
    plot(x[["prcs"]], ...)
  }
}

#
# Plot a ROC curve
#
plot.ssroc <- function(x, ...) {
  plot(x[[1]], ...)
}

#
# Plot a Precision-Recall curve
#
plot.ssprc <- function(x, ...) {
  plot(x[[1]], ...)
}
