#' Calculate the precision-recall break-even point
#'
#' The `prbe` function finds the points of a precision-recall curve at
#'   which precision and recall are equal. It takes an `S3` object
#'   generated by [evalmod()] and returns a data frame with one row per
#'   break-even point.
#'
#' @param curves An `S3` object generated by [evalmod()].
#'
#' @return The `prbe` function returns a data frame with the columns
#'   `modnames`, `dsids` and `prbe`. `prbe` is the common
#'   value of precision and recall at the break-even point.
#'
#'   A curve can cross the diagonal more than once, and then the data frame
#'   holds one row per crossing, ordered by recall. A curve that never
#'   reaches equal precision and recall gets a single row of `NA`.
#'
#' @section How this differs from ROCR:
#'
#' `ROCR::performance(pred, "prbe")` interpolates linearly between adjacent
#'   raw precision-recall points to find the crossing. Linear interpolation
#'   between precision-recall points is not correct, which is the reason
#'   this package exists, so `prbe` reads the crossing off the curve
#'   [evalmod()] has already interpolated properly. The two agree wherever
#'   the crossing falls on a point both of them hold, and differ where it
#'   falls between two of them.
#'
#' @seealso [evalmod()] for generating `S3` objects with performance
#'   evaluation measures. [auc()] for the areas under the curves.
#'
#' @examples
#'
#' ##################################################
#' ### Single model & single test dataset
#' ###
#' samps <- create_sim_samples(1, 50, 50, "good_er")
#' sscurves <- evalmod(scores = samps[["scores"]], labels = samps[["labels"]])
#' prbe(sscurves)
#'
#' ##################################################
#' ### Multiple models & multiple test datasets
#' ###
#' samps2 <- create_sim_samples(2, 50, 50, c("poor_er", "good_er"))
#' mmdat <- mmdata(samps2[["scores"]], samps2[["labels"]],
#'   modnames = samps2[["modnames"]], dsids = samps2[["dsids"]]
#' )
#' mmcurves <- evalmod(mmdat, raw_curves = TRUE)
#' prbe(mmcurves)
#'
#' @export
prbe <- function(curves) UseMethod("prbe", curves)

#' @export
prbe.default <- function(curves) {
  stop("An object of unknown class is specified")
}

#' @rdname prbe
#' @export
prbe.curve_info <- function(curves) {
  # === Validate input arguments ===
  .validate(curves)

  prcs <- curves[["prcs"]]
  data_info <- attr(curves, "data_info")

  # `evalmod(raw_curves = FALSE)` keeps only the averages, and the per-dataset
  # curves this reads are gone. The object still carries a `prcs` item, so the
  # count is what says so rather than its absence.
  if (is.null(prcs) || length(prcs) != length(data_info[["modnames"]])) {
    stop(paste(
      "The precision-recall curves of each dataset are not available.",
      "Use evalmod(raw_curves = TRUE) to keep them."
    ), call. = FALSE)
  }

  parts <- .map_idx(prcs, function(i) {
    points <- .find_break_even(prcs[[i]][["x"]], prcs[[i]][["y"]])
    data.table::data.table(
      modnames = rep(data_info[["modnames"]][i], length(points)),
      dsids = rep(data_info[["dsids"]][i], length(points)),
      prbe = points
    )
  })

  .as_plain_df(.rbind_parts(parts))
}

#
# Find where a precision-recall curve crosses the diagonal
#
# The curve arrives as supporting points that `create_curves()` has already
# interpolated, so the crossing is read off those rather than off the raw
# per-cutoff points - which is the whole difference from ROCR. Between two
# neighbouring supporting points a linear step is what the curve itself does,
# so a straight root-find on `precision - recall` is exact to the resolution
# of `x_bins`.
#
# Returns NA rather than nothing when there is no crossing, so that every
# dataset keeps a row and the result lines up with the input.
#
.find_break_even <- function(rec, prec) {
  keep <- is.finite(rec) & is.finite(prec)
  rec <- rec[keep]
  prec <- prec[keep]
  if (length(rec) < 2L) {
    return(NA_real_)
  }

  diff <- prec - rec
  out <- numeric(0)

  exact <- which(diff == 0)
  cross <- which(diff[-length(diff)] * diff[-1] < 0)

  for (i in exact) {
    out <- c(out, rec[i])
  }
  for (i in cross) {
    # Linear interpolation of the crossing between the two supporting points
    w <- diff[i] / (diff[i] - diff[i + 1])
    out <- c(out, rec[i] + w * (rec[i + 1] - rec[i]))
  }

  if (length(out) == 0L) {
    return(NA_real_)
  }

  sort(unique(out))
}
