#' Calculate the precision-recall break-even point
#'
#' The `prbe` function finds the points of a precision-recall curve at
#'   which precision and recall are equal. It takes an `S3` object
#'   generated by [evalmod()] and returns a data frame with one row per
#'   break-even point.
#'
#' @param curves An `S3` object generated by [evalmod()].
#'
#' @return The `prbe` function returns a data frame with the columns
#'   `modnames`, `dsids`, `prbe` and `baselines`. `prbe` is the common
#'   value of precision and recall at the break-even point.
#'
#'   A curve can cross the diagonal more than once, and then the data frame
#'   holds one row per crossing, ordered by recall. A curve that never
#'   reaches equal precision and recall gets a single row of `NA`, which at
#'   a low proportion of positives is a common and correct answer: such a
#'   curve can leave the origin below the diagonal and never catch up.
#'
#'   `baselines` is the proportion of positives, which is where a classifier
#'   that ranks at random breaks even - at chance the curve is flat at the
#'   prevalence, so it meets the diagonal at that recall. A break-even point
#'   of `0.2` is chance on data that is 20% positive and five times chance
#'   on data that is 4% positive. See `Reading an area against its baseline`
#'   in [auc()].
#'
#'   The origin is not reported as a break-even point. A curve is anchored
#'   at recall `0`, where precision is `1` if the top-ranked instance is a
#'   positive and `0` if it is a negative; in the second case precision and
#'   recall are equal there, but nothing has been retrieved and the equality
#'   is an artifact of where the curve starts rather than a point at which
#'   the classifier balances the two.
#'
#' @section How this differs from ROCR:
#'
#' `ROCR::performance(pred, "prbe")` interpolates linearly between adjacent
#'   raw precision-recall points to find the crossing. Linear interpolation
#'   between precision-recall points is not correct, which is the reason
#'   this package exists, so `prbe` reads the crossing off the curve
#'   [evalmod()] has already interpolated properly. The two agree wherever
#'   the crossing falls on a point both of them hold, and differ where it
#'   falls between two of them.
#'
#' @seealso [evalmod()] for generating `S3` objects with performance
#'   evaluation metrics. [auc()] for the areas under the curves.
#'
#' @examples
#'
#' ##################################################
#' ### Single model & single test dataset
#' ###
#' samps <- create_sim_samples(1, 50, 50, "good_er")
#' sscurves <- evalmod(scores = samps[["scores"]], labels = samps[["labels"]])
#' prbe(sscurves)
#'
#' ##################################################
#' ### Multiple models & multiple test datasets
#' ###
#' samps2 <- create_sim_samples(2, 50, 50, c("poor_er", "good_er"))
#' mmdat <- mmdata(samps2[["scores"]], samps2[["labels"]],
#'   modnames = samps2[["modnames"]], dsids = samps2[["dsids"]]
#' )
#' mmcurves <- evalmod(mmdat, raw_curves = TRUE)
#' prbe(mmcurves)
#'
#' @export
prbe <- function(curves) UseMethod("prbe", curves)

#' @export
prbe.default <- function(curves) {
  stop("An object of unknown class is specified")
}

#' @rdname prbe
#' @export
prbe.curve_info <- function(curves) {
  # === Validate input arguments ===
  .validate(curves)

  prcs <- curves[["prcs"]]
  data_info <- attr(curves, "data_info")

  # `evalmod(raw_curves = FALSE)` keeps only the averages, and the per-dataset
  # curves this reads are gone. The object still carries a `prcs` item, so the
  # count is what says so rather than its absence.
  if (is.null(prcs) || length(prcs) != length(data_info[["modnames"]])) {
    stop(paste(
      "The precision-recall curves of each dataset are not available.",
      "Use evalmod(raw_curves = TRUE) to keep them."
    ), call. = FALSE)
  }

  parts <- .map_idx(prcs, function(i) {
    points <- .find_break_even(prcs[[i]][["x"]], prcs[[i]][["y"]])
    data.table::data.table(
      modnames = rep(data_info[["modnames"]][i], length(points)),
      dsids = rep(data_info[["dsids"]][i], length(points)),
      prbe = points
    )
  })

  prbes <- .as_plain_df(.rbind_parts(parts))

  # At chance the curve is flat at the proportion of positives, so it meets
  # the diagonal at that recall: the prevalence is the break-even point of a
  # classifier that ranks at random, exactly as it is the area of one
  prbes[["baselines"]] <- .curve_baselines(
    rep("PRC", nrow(prbes)), prbes[["modnames"]], prbes[["dsids"]],
    data_info
  )

  prbes
}

#
# Find where a precision-recall curve crosses the diagonal
#
# The curve arrives as supporting points that `create_curves()` has already
# interpolated, so the crossing is read off those rather than off the raw
# per-cutoff points - which is the whole difference from ROCR. Between two
# neighboring supporting points a linear step is what the curve itself does,
# so a straight root-find on `precision - recall` is exact to the resolution
# of `x_bins`.
#
# Returns NA rather than nothing when there is no crossing, so that every
# dataset keeps a row and the result lines up with the input.
#
.find_break_even <- function(rec, prec) {
  keep <- is.finite(rec) & is.finite(prec)
  rec <- rec[keep]
  prec <- prec[keep]
  if (length(rec) < 2L) {
    return(NA_real_)
  }

  diff <- prec - rec
  out <- numeric(0)

  # The curve is anchored at recall 0, where precision is 1 if the
  # top-ranked instance is a positive and 0 if it is a negative. In the
  # second case precision and recall are trivially equal at the origin, but
  # nothing has been retrieved there and the classifier is not balancing the
  # two - the equality is an artifact of where the curve starts. At a low
  # proportion of positives the top-ranked instance is nearly always a
  # negative, so leaving it in would put a spurious 0 in front of almost
  # every imbalanced result.
  exact <- which(diff == 0)
  exact <- exact[rec[exact] > 0]

  # `diff` is exactly 0 at the origin in that case, and `0 * x < 0` is
  # false, so the first interval cannot produce a crossing either
  cross <- which(diff[-length(diff)] * diff[-1] < 0)

  for (i in exact) {
    out <- c(out, rec[i])
  }
  for (i in cross) {
    # Linear interpolation of the crossing between the two supporting points
    w <- diff[i] / (diff[i] - diff[i + 1])
    out <- c(out, rec[i] + w * (rec[i + 1] - rec[i]))
  }

  if (length(out) == 0L) {
    return(NA_real_)
  }

  sort(unique(out))
}
