#' Print the summary of ROC and Precision-Recall curves with multiple models.
#'
#' \code{print} takes \code{mcurves} object generated by
#' \code{\link{evalmulti}} and plot ROC and Precion-Recall curves.
#'
#' @param x \code{curves} object generated by
#'   \code{\link{evalmulti}}.
#' @param ... Other arguments.
#'
#' @examples
#' s1 <- c(1, 2, 3, 4)
#' s2 <- c(5, 6, 7, 8)
#' s3 <- c(2, 4, 6, 8)
#' mscores <- join_scores(s1, s2, s3)
#'
#' l1 <- c(1, 0, 1, 1)
#' l2 <- c(1, 1, 0, 0)
#' l3 <- c(0, 1, 0, 1)
#' mlabels <- join_labels(l1, l2, l3)
#'
#' mcurves <- evalmulti(mscores, mlabels)
#' print(mcurves)
print.mscurves <- function(x, show_test_data = FALSE, ...) {
  # === Validate input arguments ===
  .validate(x)

  # === Print summary ===
  print(x[["rocs"]])
  print(x[["prcs"]])
  if (show_test_data) {
    .print_testdat_ms(x[["rocs"]])
  }
}

# Print msroc
print.msroc <- function(x, ...) {
  cat("\n  ROC curves\n\n")
  .print_mmcurves_base(x, ...)
}

# Print msprc
print.msprc <- function(x, ...) {
  # === Print summary ===
  cat("\n  Precision-Recall curves\n\n")
  .print_mmcurves_base(x, ...)
}

# Print test data
.print_testdat_ms <- function(x, ...) {
  # === Print summary ===
  cat("\n  Test data\n\n")
  pfunc <- function(s) {
    cat("    Model name:", attr(x[[s]], "model_name"), "\n")
    cat("      # of positives:", attr(x[[s]], "np"), "\n")
    cat("      # of negatives:", attr(x[[s]], "nn"), "\n\n")
  }
  lapply(seq_along(x), pfunc)

  invisible(NULL)
}

# Print mmcurves
.print_mmcurves_base <- function(x, ...) {
  # === Validate input arguments ===
  .validate(x)

  # === Print summary ===
  pfunc <- function(s) {
    cat("    Model name:", attr(x[[s]], "model_name"), "\n")
    cat("      AUC:", attr(x[[s]], "auc"), "\n\n")
  }
  lapply(seq_along(x), pfunc)

  invisible(NULL)
}
