# Print model name and data size
.print_basic_curve_info <- function(x, indent_space = " ",
                                    show_test_data = FALSE) {

  if (show_test_data) {
    cat(indent_space, "Test data\n")
    cat(indent_space, "  # of positives:", attr(x, "np"), "\n")
    cat(indent_space, "  # of negatives:", attr(x, "nn"), "\n")
    cat("\n")
  }

  cat(indent_space, "Model name:", attr(x, "model_name"), "\n")
  cat("\n")
}

#' Print ROC curve summary.
#'
#' \code{print} takes \code{roc_curve} object generated by
#' \code{\link{create_roc}} and print the summry of the ROC curve.
#'
#' @param x \code{roc_curve} object generated by
#'   \code{\link{create_roc}}.
#' @param ... Other arguments (ignored).
#'
#' @examples
#' data(B500)
#' roc_curve <- create_roc(scores = B500$good_er_scores,
#'                         obslabs = B500$labels)
#' print(roc_curve)
print.roc_curve <- function(x, show_test_data = FALSE, ...) {
  # === Validate input arguments ===
  .validate(x)

  # === Print summary ===
  cat("\n  ROC curve\n\n")
  .print_basic_curve_info(x, "   ", show_test_data = show_test_data)
  cat("    AUC:", attr(x, "auc"), "\n\n")
}

#' Print Precision-Recall curve summary.
#'
#' \code{print} takes \code{prc_curve} object generated by
#' \code{\link{create_prc}} and print the summary of the Precision-Recall
#' curve.
#'
#' @param x \code{prc_curve} object generated by
#'   \code{\link{create_prc}}.
#' @param ... Other arguments (ignored).
#'
#' @examples
#' data(B500)
#' prc_curve <- create_prc(scores = B500$good_er_scores,
#'                         obslabs = B500$labels)
#' print(prc_curve)
print.prc_curve <- function(x, show_test_data = FALSE, ...) {
  # === Validate input arguments ===
  .validate(x)

  # === Print summary ===
  cat("\n  Precision-Recall curve\n\n")
  .print_basic_curve_info(x, "   ", show_test_data = show_test_data)
  cat("    AUC:", attr(x, "auc"), "\n\n")
}

#' Print the summary of ROC and Precision-Recall curves.
#'
#' \code{print} takes \code{curves} object generated by
#' \code{\link{create_curves}} and plot ROC and Precion-Recall curves.
#'
#' @param x \code{curves} object generated by
#'   \code{\link{create_curves}}.
#' @param ... Other arguments.
#'
#' @examples
#' data(B500)
#' curves <- create_curves(scores = B500$good_er_scores,
#'                         obslabs = B500$labels)
#' print(curves)
print.curves <- function(x, show_test_data = FALSE, ...) {
  # === Validate input arguments ===
  .validate(x)

  # === Print summary ===
  cat("\n")
  .print_basic_curve_info(x[["roc"]], show_test_data = show_test_data)

  cat("  ROC curve\n")
  cat("    AUC:", attr(x[["roc"]], "auc"), "\n\n")

  cat("  Precision-Recall curve\n")
  cat("    AUC:", attr(x[["prc"]], "auc"), "\n\n")

}

# Print mcurves
.print_mcurves_base <- function(x, ...) {
  # === Validate input arguments ===
  .validate(x)

  # === Print summary ===
  for (nm in names(x[["curves"]])) {
    cat("    Model name:", nm, "\n")
    cat("      AUC:",  x[["curves"]][[nm]][["auc"]], "\n\n")
  }
}

# Print test data
.print_testdat_info <- function(x, ...) {
  # === Print summary ===
  cat("\n  Test data\n\n")
  for (nm in names(x[["curves"]])) {
    cat("    Model name:", nm, "\n")
    cat("      # of positives:", x[["curves"]][[nm]][["pos_num"]], "\n")
    cat("      # of negatives:", x[["curves"]][[nm]][["neg_num"]], "\n\n")
  }
}

# Print mroc_curves
print.mroc_curves <- function(x, ...) {
  cat("\n  ROC curves\n\n")
  .print_mcurves_base(x, ...)
}

# Print mprc_curves
print.mprc_curves <- function(x, ...) {
  # === Print summary ===
  cat("\n  Precision-Recall curves\n\n")
  .print_mcurves_base(x, ...)
}

#' Print the summary of ROC and Precision-Recall curves with multiple models.
#'
#' \code{print} takes \code{mcurves} object generated by
#' \code{\link{evalmulti}} and plot ROC and Precion-Recall curves.
#'
#' @param x \code{curves} object generated by
#'   \code{\link{evalmulti}}.
#' @param ... Other arguments.
#'
#' @examples
#' s1 <- c(1, 2, 3, 4)
#' s2 <- c(5, 6, 7, 8)
#' s3 <- c(2, 4, 6, 8)
#' mscores <- combine_scores(s1, s2, s3)
#'
#' l1 <- c(1, 0, 1, 1)
#' l2 <- c(1, 1, 0, 0)
#' l3 <- c(0, 1, 0, 1)
#' mobslabs <- combine_obslbs(l1, l2, l3)
#'
#' mdat <- create_mdat(mscores, mobslabs)
#'
#' mcurves <- evalmulti(mdat)
#' print(mcurves)
print.mcurves <- function(x, show_test_data = FALSE, ...) {
  # === Validate input arguments ===
  .validate(x)

  # === Print summary ===
 print(x[["mroc_curves"]])
 print(x[["mprc_curves"]])
 if (show_test_data) {
   .print_testdat_info(x[["mprc_curves"]])
 }
}
