# Create either a ROC or a Precision-Recall curve
.create_curve <- function(x_name, y_name, func, func_name, class_name,
                          evals, x_interval = 0.001, scores = NULL,
                          obslabs = NULL, ...) {

  # === Validate input arguments ===
  # Create evals from scores and obslabs if it's missing
  evals <- .create_by_scores_and_labels(evals, "evals", calc_measures,
                                        scores, obslabs, ...)

  .validate_create_curves_args(x_interval, ...)

  # === Create a curve ===
  # Calculate a curve
  crv <- func(attr(evals, "src")[["tp"]], attr(evals, "src")[["fp"]],
              evals[[x_name]], evals[[y_name]], x_interval)
  .check_cpp_func_error(crv, func_name)

  # Calculate AUC
  auc <- calc_auc(crv[["x"]], crv[["y"]])
  if (auc[["errmsg"]] == "invalid-x-vals") {
    warning(paste("Invalid", x_name, "values detected. AUC can be inaccurate."))
  } else {
    .check_cpp_func_error(auc, "calc_auc")
  }

  # === Create an S3 object ===
  cpp_errmsg1 <- crv[["errmsg"]]
  cpp_errmsg2 <- auc[["errmsg"]]
  crv[["errmsg"]] <- NULL
  s3obj <- structure(crv, class = class_name)

  # Set attributes
  attr(s3obj, "model_name") <- attr(evals, "model_name")
  attr(s3obj, "nn") <- attr(evals, "nn")
  attr(s3obj, "np") <- attr(evals, "np")
  attr(s3obj, "auc") <- auc[["auc"]]
  attr(s3obj, "auc2") <- NA
  attr(s3obj, "partial") <- FALSE
  attr(s3obj, "x_limits") <- c(0, 1)
  attr(s3obj, "y_limits") <- c(0, 1)
  attr(s3obj, "args") <- c(list(x_interval = x_interval), list(...))
  attr(s3obj, "cpp_errmsg1") <- cpp_errmsg1
  attr(s3obj, "cpp_errmsg2") <- cpp_errmsg2
  attr(s3obj, "src") <- evals
  attr(s3obj, "validated") <- FALSE

  # Call .validate.roc_curve() or .validate.prc_curve()
  .validate(s3obj)
}

#' Create a ROC curve.
#'
#' \code{create_roc} takes basic evaluation measures as
#' \code{evals} object and returns a \code{roc_curve} object.
#' \code{roc_curve} contains a ROC curve.
#' \code{create_roc} can also take scores and lables directly.
#'
#' @param evals \code{evals} S3 object generated by
#'   \code{\link{calc_measures}}.
#' @param x_interval A numeric value to specifiy an interval of the
#'   x-axis (TPRs).
#' @param scores A numeric vector of predicted scores.
#'   Ignored when \code{cmats} is set.
#' @param obslabs A numeric vector or a factor of observed labels.
#'   Ignored when \code{cmats} is set.
#' @param ... Other arguments passed to \code{\link{reformat_data}} via
#'   \code{\link{calc_measures}} and \code{\link{create_confmats}}.
#' @return \code{create_roc} returns a \code{roc_curve} S3 object that
#'   contains a ROC curve.
#'
#' @examples
#' data(P10N10)
#' fmdat <- reformat_data(P10N10$scores, P10N10$labels)
#' cdat <- create_confmats(fmdat)
#' evals <- calc_measures(cdat)
#' create_roc(evals)
#' create_roc(scores = P10N10$scores, obslabs = P10N10$labels)
create_roc <- function(evals, x_interval = 0.001, scores = NULL,
                       obslabs = NULL, ...) {
  # === Create a ROC curve ===
  .create_curve("specificity", "sensitivity", create_roc_curve,
                "create_roc_curve", "roc_curve", evals, x_interval,
                scores, obslabs, ...)
}

#' Create a Precision-Recall curve.
#'
#' \code{create_prc} takes basic evaluation measures as
#' \code{evals} object and returns a \code{prc_curve} object.
#' \code{prc_curve} contains a Precision-Recall curve.
#' \code{create_roc} can also take scores and lables directly.
#'
#' @param evals \code{evals} S3 object generated by
#'   \code{\link{calc_measures}}.
#' @param x_interval A numeric value to specifiy an interval of the
#'   x-axis (recall).
#' @param scores A numeric vector of predicted scores.
#'   Ignored when \code{cmats} is set.
#' @param obslabs A numeric vector or a factor of observed labels.
#'   Ignored when \code{cmats} is set.
#' @param ... Other arguments passed to \code{\link{reformat_data}} via
#'   \code{\link{calc_measures}} and \code{\link{create_confmats}}.
#' @return \code{create_prc} returns a \code{prc_curve} S3 object that
#'   contains a Precision-Recall curve.
#'
#' @examples
#' data(P10N10)
#' fmdat <- reformat_data(P10N10$scores, P10N10$labels)
#' cdat <- create_confmats(fmdat)
#' evals <- calc_measures(cdat)
#' create_roc(evals)
#' create_roc(scores = P10N10$scores, obslabs = P10N10$labels)
create_prc <- function(evals, x_interval = 0.001, scores = NULL,
                       obslabs = NULL, ...) {
  # === Create a Precision-Recall curve ===
  .create_curve("sensitivity", "precision", create_prc_curve,
                "create_prc_curve", "prc_curve", evals, x_interval,
                scores, obslabs, ...)
}

#' Create ROC and Precision-Recall curves.
#'
#' \code{create_curves} takes basic evaluation measures as
#' \code{evals} object and returns a \code{curves} object.
#' \code{curves} contains ROC and Precision-Recall curves.
#' \code{create_curves} can also take scores and lables directly.
#'
#' @param evals \code{evals} S3 object generated by
#'   \code{\link{calc_measures}}.
#' @param x_interval A numeric value to specifiy an interval of the
#'   x-axis (TPRs for ROC and recall for Precision-Recall).
#' @param scores A numeric vector of predicted scores.
#'   Ignored when \code{cmats} is set.
#' @param obslabs A numeric vector or a factor of observed labels.
#'   Ignored when \code{cmats} is set.
#' @param ... Other arguments passed to \code{\link{reformat_data}} via
#'   \code{\link{calc_measures}} and \code{\link{create_confmats}}.
#' @return \code{create_curves} returns a \code{curves} S3 object that
#'   contains ROC and Precision-Recall curves.
#'
#' @examples
#' data(P10N10)
#' fmdat <- reformat_data(P10N10$scores, P10N10$labels)
#' cdat <- create_confmats(fmdat)
#' evals <- calc_measures(cdat)
#' create_curves(evals)
#' create_curves(scores = P10N10$scores, obslabs = P10N10$labels)
create_curves <- function(evals, x_interval = 0.001, scores = NULL,
                          obslabs = NULL, ...) {
  # === Validate input arguments ===
  # Create evals from scores and obslabs if it's missing
  evals <- .create_by_scores_and_labels(evals, "evals", calc_measures,
                                        scores, obslabs, ...)

  .validate_create_curves_args(x_interval, ...)

  # === Create ROC and Precision-Recall curves ===
  roc_curve <- create_roc(evals, x_interval)
  prc_curve <- create_prc(evals, x_interval)
  curves <- list(roc = roc_curve, prc = prc_curve)

  # === Create an S3 object ===
  s3obj <- structure(curves, class = "curves")

  # Set attributes
  attr(s3obj, "model_name") <- attr(evals, "model_name")
  attr(s3obj, "nn") <- attr(evals, "nn")
  attr(s3obj, "np") <- attr(evals, "np")
  attr(s3obj, "args") <- c(list(x_interval = x_interval), list(...))
  attr(s3obj, "src") <- evals
  attr(s3obj, "validated") <- FALSE

  # Call .validate.curves()
  .validate(s3obj)
}
