#' Calculate confusion matrices for all possible threshold values.
#'
#' \code{create_confmats} takes predicted scores and binary lables as
#' \code{fmdat} object and returns a \code{cmats} object.
#' \code{cmats} contains TPs, FPs, FNs, TNs, and ranks that are used
#' by a subsequent function, \code{\link{calc_measures}}, in the perforamcne
#' evaluation pipeline. \code{create_confmats} can also take scores and lables
#' directly.
#'
#' @param fmdat \code{fmdat} S3 object generated by
#'   \code{\link{reformat_data}}.
#' @param pscores A numeric vector of predicted scores.
#'   Ignored when \code{fmdat} is set.
#' @param olabs A numeric vector or a factor of observed labels.
#'   Ignored when \code{fmdat} is set.
#' @param ... Other arguments passed to \code{\link{reformat_data}}.
#' @return \code{create_confmats} returns a \code{cmats} S3 object that
#'   contains TPs, FPs, FNs, and TNs.
#'
#' @examples
#' data(P10N10)
#' fmdat <- reformat_data(P10N10$scores, P10N10$labels)
#' create_confmats(fmdat)
#' create_confmats(pscores = P10N10$scores, olabs = P10N10$labels)
create_confmats <- function(fmdat, pscores = NULL, olabs = NULL, ...) {
  # === Validate input arguments ===
  # Create fmdat from scores and labels if fmdat is missing
  fmdat <- .create_by_scores_and_labels(fmdat, "fmdat", reformat_data,
                                        pscores, olabs, ...)

  # === Create confusion matrices for all possible threshold values ===
  # Call a cpp function via Rcpp interface
  cmats <- create_confusion_matrices(fmdat[["olabs"]], fmdat[["ranks"]],
                                     fmdat[["rank_idx"]])
  .check_cpp_func_error(cmats, "create_confusion_matrices")

  # === Create an S3 object ===
  cpp_errmsg <- cmats[["errmsg"]]
  cmats[["errmsg"]] <- NULL
  s3obj <- structure(cmats, class = "cmats")

  # Set attributes
  attr(s3obj, "model_name") <- attr(fmdat, "model_name")
  attr(s3obj, "data_no") <- attr(fmdat, "data_no")
  attr(s3obj, "nn") <- attr(fmdat, "nn")
  attr(s3obj, "np") <- attr(fmdat, "np")
  attr(s3obj, "args") <- list(...)
  attr(s3obj, "cpp_errmsg") <- cpp_errmsg
  attr(s3obj, "src") <- fmdat
  attr(s3obj, "validated") <- FALSE

  # Call .validate.cmats()
  .validate(s3obj)
}
