#
# Control the main pipeline iterations for ROC and Precision-Recall curves
#
.pl_main_rocprc <- function(mdat, model_type, dataset_type, class_name_pf,
                            calc_avg = TRUE, ci_alpha = 0.05, all_curves = FALSE,
                            x_bins = 1000, orig_points = TRUE) {

  # === Create ROC and Precision-Recall curves ===
  # Create curves
  plfunc <- function(s) {
    cdat <- create_confmats(mdat[[s]])
    pevals <- calc_measures(cdat)
    curves <- create_curves(pevals, x_bins = x_bins)
  }
  lcurves <- lapply(seq_along(mdat), plfunc)

  # Group curves by line type
  grpfunc <- function(lt) {
    .group_curves(lcurves, lt, "crvgrp", mdat, dataset_type,
                  calc_avg, ci_alpha, x_bins)
  }
  grp_curves <- lapply(c("roc", "prc"), grpfunc)
  names(grp_curves)<- c("rocs", "prcs")

  # Summarize AUC
  aucs <- .group_aucs(lcurves, mdat)

  # === Create an S3 object ===
  s3obj <- structure(grp_curves, class = c(paste0(class_name_pf, "curves"),
                                           "curve_info"))

  # Set attributes
  attr(s3obj, "aucs") <- aucs
  attr(s3obj, "data_info") <- attr(mdat, "data_info")
  attr(s3obj, "uniq_modnames") <- attr(mdat, "uniq_modnames")
  attr(s3obj, "uniq_dsids") <- attr(mdat, "uniq_dsids")
  attr(s3obj, "model_type") <- model_type
  attr(s3obj, "dataset_type") <- dataset_type
  attr(s3obj, "args") <- list(calc_avg = calc_avg,
                              ci_alpha = ci_alpha,
                              all_curves = all_curves,
                              x_bins = x_bins,
                              orig_points = orig_points)
  attr(s3obj, "validated") <- FALSE

  # Call .validate.class_name()
  .validate(s3obj)
}

#
# Get ROC or Precision-Recall curves from curves
#
.group_curves <- function(lcurves, curve_type, class_name, mdat,
                          dataset_type, calc_avg, ci_alpha, x_bins) {

  # Group ROC or PRC curves
  mc <- lapply(seq_along(lcurves), function(s) lcurves[[s]][[curve_type]])

  # === Create an S3 object ===
  s3obj <- structure(mc, class = class_name)

  # Set attributes
  attr(s3obj, "data_info") <- attr(mdat, "data_info")
  attr(s3obj, "curve_type") <- attr(mdat, "curve_type")
  attr(s3obj, "uniq_modnames") <- attr(mdat, "uniq_modnames")
  attr(s3obj, "uniq_dsids") <- attr(mdat, "uniq_dsids")
  attr(s3obj, "avgcurve") <- NA
  attr(s3obj, "validated") <- FALSE

  # Call .validate.class_name()
  s3obj <- .validate(s3obj)

  # Calculate the average curves
  if (dataset_type == "multiple" && calc_avg) {
    attr(s3obj, "avgcurves") <- calc_avg_rocprc(s3obj, ci_alpha, x_bins)
  }

  s3obj
}

#
# Get AUCs
#
.group_aucs <- function(lcurves, mdat) {

  # Group AUC of ROC or PRC curves
  modnames <- attr(mdat, "data_info")[["modnames"]]
  dsids <- attr(mdat, "data_info")[["dsids"]]
  aucs <- data.frame(modnames = rep(modnames, each = 2),
                     dsids = rep(dsids, each = 2),
                     curvetypes = rep(c("ROC", "PRC"), length(modnames)),
                     aucs = rep(NA, length(modnames) * 2),
                     stringsAsFactors = FALSE)

  j <- 1
  for (i in seq_along(lcurves)) {
    aucs[["aucs"]][j] <- attr(lcurves[[i]][["roc"]], "auc")
    j <- j + 1
    aucs[["aucs"]][j] <- attr(lcurves[[i]][["prc"]], "auc")
    j <- j + 1
  }

  aucs
}

#
# Validate curves object generated by pl_main_rocprc()
#
.validate_curves_common <- function(curves, class_name) {
  # Need to validate only once
  if (is(curves, class_name) && attr(curves, "validated")) {
    return(curves)
  }

  # Check curves
  if (!is(curves, class_name)) {
    stop(paste0(class_name, " object created by pl_main_rocprc() expected"))
  }

  attr(curves, "validated") <- TRUE
  curves
}

#
# Validate 'sscurves' object generated by pl_main_rocprc()
#
.validate.sscurves <- function(sscurves) {
  .validate_curves_common(sscurves, "sscurves")
}

#
# Validate 'mscurves' object generated by pl_main_rocprc()
#
.validate.mscurves <- function(mscurves) {
  .validate_curves_common(mscurves, "mscurves")
}

#
# Validate 'smcurves' object generated by pl_main_rocprc()
#
.validate.smcurves <- function(smcurves) {
  .validate_curves_common(smcurves, "smcurves")
}

#
# Validate 'mmcurves' object generated by pl_main_rocprc()
#
.validate.mmcurves <- function(mmcurves) {
  .validate_curves_common(mmcurves, "mmcurves")
}

#
# Validate 'crvgrp' object generated by pl_main_rocprc()
#
.validate.crvgrp <- function(crvgrp) {
  .validate_curves_common(crvgrp, "crvgrp")
}

