#
# Control the main pipeline iterations for basic evaluation messures
#
.pl_main_basic <- function(mdat, model_type, dataset_type, class_name_pf,
                           calc_avg = TRUE, ci_alpha = 0.05,
                           all_curves = FALSE) {

  # === Create ROC and Precision-Recall curves ===
  # Create points
  plfunc <- function(s) {
    cdat <- create_confmats(mdat[[s]])
    pevals <- calc_measures(cdat)
  }
  lpoints <- lapply(seq_along(mdat), plfunc)

  # Group points by evaluation measure
  grpfunc <- function(m) {
    .group_points(lpoints, m, "pointgrp", mdat, dataset_type,
                  calc_avg, ci_alpha)
  }
  grp_points <- lapply(c("error", "accuracy", "specificity", "sensitivity",
                         "precision"), grpfunc)
  names(grp_points)<- c("err", "acc", "sp", "sn", "prec")

  # Summarize basic evaluation measures
  eval_summary <- .summarize_basic(lpoints, mdat)

  # === Create an S3 object ===
  s3obj <- structure(grp_points, class = c(paste0(class_name_pf, "points"),
                                           "beval_info"))

  # Set attributes
  attr(s3obj, "eval_summary") <- eval_summary
  attr(s3obj, "data_info") <- attr(mdat, "data_info")
  attr(s3obj, "uniq_modnames") <- attr(mdat, "uniq_modnames")
  attr(s3obj, "uniq_dsids") <- attr(mdat, "uniq_dsids")
  attr(s3obj, "model_type") <- model_type
  attr(s3obj, "dataset_type") <- dataset_type
  attr(s3obj, "args") <- list(calc_avg = calc_avg,
                              ci_alpha = ci_alpha,
                              all_curves = all_curves)
  attr(s3obj, "validated") <- FALSE

  # Call .validate.class_name()
  .validate(s3obj)
}

#
# Get evaluation measures at all threshold values by models
#
.group_points <- function(lpoints, eval_type, class_name, mdat, dataset_type,
                          calc_avg, ci_alpha) {

  # Group by basic evaluation measure
  grp_func <- function(s) {
    list(x = lpoints[[s]][["basic"]][["threshold"]],
         y = lpoints[[s]][["basic"]][[eval_type]])
  }
  pevals <- lapply(seq_along(lpoints), grp_func)

  # === Create an S3 object ===
  s3obj <- structure(pevals, class = class_name)

  # Set attributes
  attr(s3obj, "data_info") <- attr(mdat, "data_info")
  attr(s3obj, "eval_type") <- eval_type
  attr(s3obj, "uniq_modnames") <- attr(mdat, "uniq_modnames")
  attr(s3obj, "uniq_dsids") <- attr(mdat, "uniq_dsids")
  attr(s3obj, "avgpoints") <- NA
  attr(s3obj, "validated") <- FALSE

  # Call .validate.class_name()
  s3obj <- .validate(s3obj)

  # Calculate the average curves
  if (dataset_type == "multiple" && calc_avg) {
    attr(s3obj, "avgcurves") <- calc_avg_basic(s3obj, ci_alpha)
  }

  s3obj

}

#
# Summarize basic evaluation measures
#
.summarize_basic <- function(lpoints, mdat) {
  # Group AUC of ROC or PRC curves
  modnames <- attr(mdat, "data_info")[["modnames"]]
  dsids <- attr(mdat, "data_info")[["dsids"]]
  evaltypes <- c("threshold", "error", "accuracy", "specificity",
                 "sensitivity", "precision")
  elen <- length(evaltypes)

  sbasic <- data.frame(modnames = rep(modnames, each = elen),
                       dsids = rep(dsids, each = elen),
                       evaltypes = rep(evaltypes, length(modnames)),
                       minvals = rep(NA, length(modnames) * elen),
                       q25vals = rep(NA, length(modnames) * elen),
                       medianvals = rep(NA, length(modnames) * elen),
                       meanvals = rep(NA, length(modnames) * elen),
                       q75vals = rep(NA, length(modnames) * elen),
                       maxvals = rep(NA, length(modnames) * elen),
                       stringsAsFactors = FALSE)

  for (i in seq_along(lpoints)) {
    for (j in seq_along(evaltypes)) {
      vals <- lpoints[[i]][["basic"]][[evaltypes[j]]]
      sbasic[(i - 1) * length(evaltypes) + j, 4:9] <- summary(vals)
    }
  }

  sbasic
}

#
# Validate point object generated by .pl_main_basic()
#
.validate_points_common <- function(points, class_name) {
  # Need to validate only once
  if (is(points, class_name) && attr(points, "validated")) {
    return(points)
  }

  # Check points
  if (!is(points, class_name)) {
    stop(paste0(class_name, " object created by .pl_main_basic() expected"))
  }

  attr(points, "validated") <- TRUE
  points
}

#
# Validate 'sspoints' object generated by .pl_main_basic()
#
.validate.sspoints <- function(sspoints) {
  .validate_points_common(sspoints, "sspoints")
}

#
# Validate 'mspoints' object generated by .pl_main_basic()
#
.validate.mspoints <- function(mspoints) {
  .validate_points_common(mspoints, "mspoints")
}

#
# Validate 'smpoints' object generated by .pl_main_basic()
#
.validate.smpoints <- function(smpoints) {
  .validate_points_common(smpoints, "smpoints")
}

#
# Validate 'mmpoints' object generated by .pl_main_basic()
#
.validate.mmpoints <- function(mmpoints) {
  .validate_points_common(mmpoints, "mmpoints")
}

#
# Validate 'pointgrp' object generated by .pl_main_basic()
#
.validate.pointgrp <- function(pointgrp) {
  .validate_points_common(pointgrp, "pointgrp")
}
