#' Calculate basic evaluation measurs from confusion matrices.
#'
#' \code{calc_measures} takes confusion matrices as
#' \code{cmats} object and returns a \code{pevals} object.
#' \code{pevals} contains basic evaluation measures that are used
#' by a subsequent function, \code{\link{create_curves}}, in the perforamcne
#' evaluation pipeline. \code{calc_measures} can also take scores and lables
#' directly.
#'
#' @param cmats \code{cmats} S3 object generated by
#'   \code{\link{create_confmats}}.
#' @param scores A numeric vector of predicted scores.
#'   Ignored when \code{cmats} is set.
#' @param olabs A numeric vector or a factor of observed labels.
#'   Ignored when \code{cmats} is set.
#' @param ... Other arguments passed to \code{\link{reformat_data}} via
#'   \code{\link{create_confmats}}.
#' @return \code{calc_measures} returns a \code{pevals} S3 object that
#'   contains basic evaluation measures, such as specificity,
#'   sensitvity/reall, and precision values.
#'
#' @examples
#' data(P10N10)
#' fmdat <- reformat_data(P10N10$scores, P10N10$labels)
#' cmats <- create_confmats(fmdat)
#' calc_measures(cmats)
#' calc_measures(scores = P10N10$scores, olabs = P10N10$labels)
calc_measures <- function(cmats, scores = NULL, olabs = NULL, ...) {
  # === Validate input arguments ===
  # Create cmats from scores and labels if cmats is missing
  cmats <- .create_by_scores_and_labels(cmats, "cmats", create_confmats,
                                        scores, olabs, ...)
  .validate(cmats)

  # === Create confusion matrices for all possible threshold values ===
  # Call a cpp function via Rcpp interface
  pevals <- calc_basic_measures(cmats[["pos_num"]], cmats[["neg_num"]], cmats[["tp"]],
                                cmats[["fp"]], cmats[["tn"]], cmats[["fn"]])
  .check_cpp_func_error(pevals, "calc_basic_measures")

  # === Create an S3 object ===
  cpp_errmsg <- pevals[["errmsg"]]
  pevals[["errmsg"]] <- NULL
  s3obj <- structure(pevals, class = "pevals")

  # Set attributes
  attr(s3obj, "model_name") <- attr(cmats, "model_name")
  attr(s3obj, "data_no") <- attr(cmats, "data_no")
  attr(s3obj, "nn") <- attr(cmats, "nn")
  attr(s3obj, "np") <- attr(cmats, "np")
  attr(s3obj, "args") <- list(...)
  attr(s3obj, "cpp_errmsg") <- cpp_errmsg
  attr(s3obj, "src") <- cmats
  attr(s3obj, "validated") <- FALSE

  # Call .validate.cmats()
  .validate(s3obj)
}
