#' Create ROC and Precision-Recall curves.
#'
#' \code{create_curves} takes basic evaluation measures as
#' \code{pevals} object and returns a \code{curves} object.
#' \code{curves} contains ROC and Precision-Recall curves.
#' \code{create_curves} can also take scores and lables directly.
#'
#' @param pevals \code{pevals} S3 object generated by
#'   \code{\link{calc_measures}}.
#' @param x_interval A numeric value to specifiy an interval of the
#'   x-axis (TPRs for ROC and recall for Precision-Recall).
#' @param pscores A numeric vector of predicted scores.
#'   Ignored when \code{cmats} is set.
#' @param olabs A numeric vector or a factor of observed labels.
#'   Ignored when \code{cmats} is set.
#' @param ... Other arguments passed to \code{\link{reformat_data}} via
#'   \code{\link{calc_measures}} and \code{\link{create_confmats}}.
#' @return \code{create_curves} returns a \code{curves} S3 object that
#'   contains ROC and Precision-Recall curves.
#'
#' @examples
#' data(P10N10)
#' fmdat <- reformat_data(P10N10$scores, P10N10$labels)
#' cdat <- create_confmats(fmdat)
#' pevals <- calc_measures(cdat)
#' create_curves(pevals)
#' create_curves(pscores = P10N10$scores, olabs = P10N10$labels)
create_curves <- function(pevals, x_interval = 0.001, pscores = NULL,
                          olabs = NULL, ...) {
  # === Validate input arguments ===
  # Create pevals from scores and labels if pevals is missing
  pevals <- .create_by_scores_and_labels(pevals, "pevals", calc_measures,
                                         pscores, olabs, ...)
  .validate_x_interval(x_interval)
  .validate(pevals)

  # === Create ROC and Precision-Recall curves ===
  roc_curve <- create_roc(pevals, x_interval)
  prc_curve <- create_prc(pevals, x_interval)
  curves <- list(roc = roc_curve, prc = prc_curve)

  # === Create an S3 object ===
  s3obj <- structure(curves, class = "curves")

  # Set attributes
  attr(s3obj, "model_name") <- attr(pevals, "model_name")
  attr(s3obj, "data_no") <- attr(pevals, "data_no")
  attr(s3obj, "nn") <- attr(pevals, "nn")
  attr(s3obj, "np") <- attr(pevals, "np")
  attr(s3obj, "args") <- c(list(x_interval = x_interval), list(...))
  attr(s3obj, "src") <- pevals
  attr(s3obj, "validated") <- FALSE

  # Call .validate.curves()
  .validate(s3obj)
}

#' Create a ROC curve.
#'
#' \code{create_roc} takes basic evaluation measures as
#' \code{pevals} object and returns a \code{roc_curve} object.
#' \code{roc_curve} contains a ROC curve.
#' \code{create_roc} can also take scores and lables directly.
#'
#' @param pevals \code{pevals} S3 object generated by
#'   \code{\link{calc_measures}}.
#' @param x_interval A numeric value to specifiy an interval of the
#'   x-axis (TPRs).
#' @param pscores A numeric vector of predicted scores.
#'   Ignored when \code{cmats} is set.
#' @param olabs A numeric vector or a factor of observed labels.
#'   Ignored when \code{cmats} is set.
#' @param ... Other arguments passed to \code{\link{reformat_data}} via
#'   \code{\link{calc_measures}} and \code{\link{create_confmats}}.
#' @return \code{create_roc} returns a \code{roc_curve} S3 object that
#'   contains a ROC curve.
#'
#' @examples
#' data(P10N10)
#' fmdat <- reformat_data(P10N10$scores, P10N10$labels)
#' cdat <- create_confmats(fmdat)
#' pevals <- calc_measures(cdat)
#' create_roc(pevals)
#' create_roc(pscores = P10N10$scores, olabs = P10N10$labels)
create_roc <- function(pevals, x_interval = 0.001, pscores = NULL, olabs = NULL,
                       ...) {
  # === Create a ROC curve ===
  .create_curve("specificity", "sensitivity", create_roc_curve,
                "create_roc_curve", "roc_curve", pevals, x_interval,
                pscores, olabs, ...)
}

#' Create a Precision-Recall curve.
#'
#' \code{create_prc} takes basic evaluation measures as
#' \code{pevals} object and returns a \code{prc_curve} object.
#' \code{prc_curve} contains a Precision-Recall curve.
#' \code{create_roc} can also take scores and lables directly.
#'
#' @param pevals \code{pevals} S3 object generated by
#'   \code{\link{calc_measures}}.
#' @param x_interval A numeric value to specifiy an interval of the
#'   x-axis (recall).
#' @param pscores A numeric vector of predicted scores.
#'   Ignored when \code{cmats} is set.
#' @param olabs A numeric vector or a factor of observed labels.
#'   Ignored when \code{cmats} is set.
#' @param ... Other arguments passed to \code{\link{reformat_data}} via
#'   \code{\link{calc_measures}} and \code{\link{create_confmats}}.
#' @return \code{create_prc} returns a \code{prc_curve} S3 object that
#'   contains a Precision-Recall curve.
#'
#' @examples
#' data(P10N10)
#' fmdat <- reformat_data(P10N10$scores, P10N10$labels)
#' cdat <- create_confmats(fmdat)
#' pevals <- calc_measures(cdat)
#' create_roc(pevals)
#' create_roc(pscores = P10N10$scores, olabs = P10N10$labels)
create_prc <- function(pevals, x_interval = 0.001, pscores = NULL, olabs = NULL,
                       ...) {
  # === Create a Precision-Recall curve ===
  .create_curve("sensitivity", "precision", create_prc_curve,
                "create_prc_curve", "prc_curve", pevals, x_interval,
                pscores, olabs, ...)
}

#
# Create either a ROC or a Precision-Recall curve
#
.create_curve <- function(x_name, y_name, func, func_name, class_name,
                          pevals, x_interval = 0.001, pscores = NULL,
                          olabs = NULL, ...) {

  # === Validate input arguments ===
  # Create pevals from scores and labels if pevals us missing
  pevals <- .create_by_scores_and_labels(pevals, "pevals", calc_measures,
                                         pscores, olabs, ...)
  .validate_x_interval(x_interval)
  .validate(pevals)

  # === Create a curve ===
  # Calculate a curve
  crv <- func(attr(pevals, "src")[["tp"]], attr(pevals, "src")[["fp"]],
              pevals[[x_name]], pevals[[y_name]], x_interval)
  .check_cpp_func_error(crv, func_name)

  # Calculate AUC
  auc <- calc_auc(crv[["x"]], crv[["y"]])
  if (auc[["errmsg"]] == "invalid-x-vals") {
    warning(paste("Invalid", x_name, "values detected. AUC can be inaccurate."))
  } else {
    .check_cpp_func_error(auc, "calc_auc")
  }

  # === Create an S3 object ===
  cpp_errmsg1 <- crv[["errmsg"]]
  cpp_errmsg2 <- auc[["errmsg"]]
  crv[["errmsg"]] <- NULL
  s3obj <- structure(crv, class = class_name)

  # Set attributes
  attr(s3obj, "model_name") <- attr(pevals, "model_name")
  attr(s3obj, "data_no") <- attr(pevals, "data_no")
  attr(s3obj, "nn") <- attr(pevals, "nn")
  attr(s3obj, "np") <- attr(pevals, "np")
  attr(s3obj, "auc") <- auc[["auc"]]
  attr(s3obj, "partial") <- FALSE
  attr(s3obj, "pauc") <- NA
  attr(s3obj, "x_limits") <- c(0, 1)
  attr(s3obj, "y_limits") <- c(0, 1)
  attr(s3obj, "args") <- c(list(x_interval = x_interval), list(...))
  attr(s3obj, "cpp_errmsg1") <- cpp_errmsg1
  attr(s3obj, "cpp_errmsg2") <- cpp_errmsg2
  attr(s3obj, "src") <- pevals
  attr(s3obj, "validated") <- FALSE

  # Call .validate.roc_curve() or .validate.prc_curve()
  .validate(s3obj)
}
