#
# Calculate the average curve for a model
#
calc_avg_rocprc <- function(curves, ci_alpha, x_bins) {
  .calc_avg_common(curves, "curve", "avgcurves", ci_alpha, x_bins)
}

#
# Calculate the average points for a model
#
calc_avg_basic <- function(epoints, ci_alpha) {
  .calc_avg_common(epoints, "point", "avgpoints", ci_alpha, NULL)
}

#
# Calculate averages
#
.calc_avg_common <- function(obj, mode, class_name, ci_alpha, x_bins) {

  # === Validate input arguments ===
  .validate_ci_alpha(ci_alpha)
  .validate_x_bins(x_bins)
  .validate(obj)

  modnames <- attr(obj, "data_info")[["modnames"]]
  uniq_modnames <- attr(obj, "uniq_modnames")

  # === Summarize curves by by models ===
  # Quantile of CI
  ci_q <- qnorm((1.0 - ci_alpha) + (ci_alpha * 0.5))

  # Filter curves by model
  ffunc <- function(mname) {
    obj[modnames == mname]
  }
  obj_by_model <- lapply(uniq_modnames, ffunc)

  # Calcualte averages and confidence interval
  vfunc <- function(i) {
    if (mode == "curve") {
      avgs <- calc_avg_curve(obj_by_model[[i]], x_bins, ci_q)
      .check_cpp_func_error(avgs, "calc_avg_curve")

    } else if (mode == "point") {
      avgs <- calc_avg_basic(obj_by_model[[i]], ci_q)
      .check_cpp_func_error(avgs, "calc_avg_basic")
    }
    avgs[["avg"]]
  }
  lavgs <- lapply(seq_along(obj_by_model), vfunc)

  # === Create an S3 object ===
  s3obj <- structure(lavgs, class = class_name)

  # Set attributes
  attr(s3obj, "uniq_modnames") <- uniq_modnames
  attr(s3obj, "args") <- list(ci_alpha = ci_alpha,
                              x_bins = x_bins)
  attr(s3obj, "validated") <- FALSE

  # Call .validate()
  .validate(s3obj)
}


#
# Validate 'avgcurves' object generated by create_curves()
#
.validate.avgcurves <- function(avgcurves) {
  # Need to validate only once
  if (is(avgcurves, "avgcurves") && attr(avgcurves, "validated")) {
    return(avgcurves)
  }

  # Validate class items and attributes
  item_names <- NULL
  attr_names <- c("args", "validated")
  arg_names <- c("ci_alpha", "x_bins")
  .validate_basic(avgcurves, "avgcurves", "calc_avg", item_names, attr_names,
                  arg_names)

  # Check values of class items


  attr(avgcurves, "validated") <- TRUE
  avgcurves
}
