#' Plot a ROC curve.
#'
#' \code{plot} takes \code{roc_curve} object generated by
#' \code{\link{create_roc}} and plot a ROC curve.
#'
#' @param object \code{roc_curve} object generated by
#'   \code{\link{create_roc}}.
#' @param ... Other arguments (ignored).
#'
#' @examples
#' data(B500)
#' roc_curve <- create_roc(scores = B500$good_er_scores,
#'                         obslabs = B500$labels)
#' plot(roc_curve)
plot.roc_curve <- function(object, ...) {
  # === Validate input arguments ===
  .validate(object)

  # === Create a plot ===
  np <- object[["pos_num"]]
  nn <- object[["neg_num"]]

  plot(object[["x"]], object[["y"]], type = "l",
       main = paste("ROC - P: ", np, ", N: ", nn, sep=""),
       xlab = "1 - Specificity", ylab = "Sensitivity")
  abline(a = 0, b = 1, col = "grey", lty = 3)
}

#' Plot a Precision-Recall curve.
#'
#' \code{plot} takes \code{prc_curve} object generated by
#' \code{\link{create_prc}} and plot a ROC curve.
#'
#' @param object \code{prc_curve} object generated by
#'   \code{\link{create_prc}}.
#' @param ... Other arguments (ignored).
#'
#' @examples
#' data(B500)
#' prc_curve <- create_prc(scores = B500$good_er_scores,
#'                         obslabs = B500$labels)
#' plot(prc_curve)
plot.prc_curve <- function(object, ...) {
  # === Validate input arguments ===
  .validate(object)

  # === Create a plot ===
  np <- object[["pos_num"]]
  nn <- object[["neg_num"]]

  plot(object[["x"]], object[["y"]], type = "l",
       main = paste("Precision-Recall - P: ", np, ", N: ", nn, sep=""),
       xlab = "Recall", ylab = "Precision",
       ylim = c(0, 1))
  abline(h = np / (np + nn), col = "grey", lty = 3)
}

#' Plot ROC and Precision-Recall curves.
#'
#' \code{plot} takes \code{curves} object generated by
#' \code{\link{create_curves}} and plot ROC and Precion-Recall curves.
#'
#' @param object \code{curves} object generated by
#'   \code{\link{create_curves}}.
#' @param ... Other arguments.
#'
#' @examples
#' data(B500)
#' curves <- create_curves(scores = B500$good_er_scores,
#'                         obslabs = B500$labels)
#' plot(curves)
plot.curves <- function(object, curvetype = c("ROC", "PRC"), ...) {
  opar <- par(no.readonly = TRUE)
  if ("ROC" %in% curvetype && "PRC" %in% curvetype) {
    par(mfrow=c(1,2))
  }

  # === Validate input arguments ===
  .validate(object)

  if (!is.atomic(curvetype) || !is.character(curvetype) || length(curvetype) > 2
      || length(setdiff(curvetype, c("ROC", "PRC"))) != 0)
  {
    stop("Invalid 'curvetype' value")
  }

  # === Create a plot ===
  if ("ROC" %in% curvetype) {
    plot(object[["roc"]])
  }

  if ("PRC" %in% curvetype) {
    plot(object[["prc"]])
  }

  par(opar)
}
