#' precrec: A package for computing accurate ROC and Precision-Recall curves
#'
#' The precrec package contains several functions and `S3` generics to
#' provide a robust platform for performance evaluation of binary classifiers.
#'
#' @section Functions:
#' The precrec package provides the following six functions.
#'
#'   | **Function**           | **Description**                                            |
#'   |------------------------|------------------------------------------------------------|
#'   | [evalmod()]            | Main function to calculate evaluation metrics             |
#'   | [mmdata()]             | Reformat input data for performance evaluation calculation |
#'   | [join_scores()]        | Join scores of multiple models into a list                 |
#'   | [join_labels()]        | Join observed labels of multiple test datasets into a list |
#'   | [create_sim_samples()] | Create random samples for simulations                      |
#'   | [format_nfold()]       | Create n-fold cross validation dataset from data frame     |
#'
#' @section S3 generics:
#' The precrec package provides nine different `S3` generics for the
#'  `S3` objects generated by the [evalmod()] function.
#'
#'   | **S3 generic**    | **Library** | **Description**                                                |
#'   |-------------------|-------------|----------------------------------------------------------------|
#'   | `print`           | base        | Print the calculation results and the summary of the test data |
#'   | [as.data.frame()] | base        | Convert a precrec object to a data frame                       |
#'   | [plot()]          | graphics    | Plot performance evaluation metrics                           |
#'   | [autoplot()]      | ggplot2     | Plot performance evaluation metrics with ggplot2              |
#'   | [fortify()]       | ggplot2     | Prepare a data frame for ggplot2                               |
#'   | [auc()]           | precrec     | Make a data frame with AUC scores                              |
#'   | [part()]          | precrec     | Calculate partial curves and partial AUC scores                |
#'   | [pauc()]          | precrec     | Make a data frame with pAUC scores                             |
#'   | [auc_ci()]        | precrec     | Calculate confidence intervals of AUC scores                   |
#'
#' @section Performance metric calculations:
#' The [evalmod()] function calculates ROC and Precision-Recall
#'   curves and returns an `S3` object. The generated `S3` object can
#'   be used with several different `S3` generics, such as `print` and
#'   [plot()]. The [evalmod()] function can also
#'   calculate basic evaluation metrics - error rate, accuracy, specificity,
#'   sensitivity, precision, Matthews correlation coefficient, F-score,
#'   balanced accuracy, negative predictive value, informedness, markedness,
#'   and Cohen's kappa.
#'
#' @section Data preparation:
#' The [mmdata()] function creates an input dataset for
#'  the [evalmod()] function. The generated dataset contains
#'  formatted scores and labels.
#'
#' [join_scores()] and [join_labels()] are helper
#'  functions to combine multiple scores and labels.
#'
#' The [create_sim_samples()] function creates test datasets with
#'  five different performance levels.
#'
#' @section Data visualization:
#' [plot()] takes an `S3` object generated
#' by [evalmod()] as input and plot corresponding curves.
#'
#' [autoplot()] uses `ggplot` to plot curves.
#'
#' @section Result retrieval:
#' [as.data.frame()] takes an `S3` object generated
#' by [evalmod()] as input and and returns a data frame
#' with calculated curve points.
#'
#' [auc()] and [pauc()] returns a data frame with AUC scores
#' and partial AUC scores, respectively. [auc_ci()]
#' returns confidence intervals of AUCs for both ROC
#' and precision-recall curves.
#'
#' [average_precision()] returns the step estimator of the area under the
#' precision-recall curve, and [prbe()] the precision-recall break-even
#' point.
#'
#' @section Probability-based metrics:
#' [prob_metrics()] calculates the Brier score and the log loss of
#' prediction scores that are probabilities, and [prob_metrics_ci()]
#' returns their confidence intervals over multiple test datasets.
#'
#' @section Uncertainty from one test set:
#' [auc_boot()] resamples a single test set so that [auc_ci()] can put a
#' percentile interval around its AUC, and [auc_diff()] can compare two
#' models on the same resamples.
#'
#' @section Classification report:
#' [classification_report()] reports precision, recall and the F-score of
#' every class at one operating point, in the layout `scikit-learn`'s
#' function of that name prints.
#'
#'
#' @name precrec
#'
#' @useDynLib precrec, .registration = TRUE
#' @importFrom Rcpp sourceCpp
#' @importFrom ggplot2 autoplot
#' @importFrom ggplot2 fortify
#' @importFrom grDevices col2rgb rainbow rgb
#' @importFrom graphics abline layout legend lines
#' @importFrom graphics matplot plot plot.new polygon
#' @importFrom methods is
#' @importFrom rlang sym
#' @importFrom stats qnorm rbeta rnorm sd qt quantile pnorm
#' @importFrom data.table frank
#'
"_PACKAGE"

.onUnload <- function(libpath) {
  library.dynam.unload("precrec", libpath)
}

#' Balanced data with 500 positives and 500 negatives.
#'
#' A list contains labels and scores of five different performance levels.
#' All scores were randomly generated.
#'
#' @format A list with 8 items.
#' \describe{
#'   \item{np}{number of positives: 500}
#'   \item{nn}{number of negatives: 500}
#'   \item{labels}{labels of observed data}
#'   \item{random_scores}{scores of a random performance level}
#'   \item{poor_er_scores}{scores of a poor early retrieval level}
#'   \item{good_er_scores}{scores of a good early retrieval level}
#'   \item{excel_scores}{scores of an excellent level}
#'   \item{perf_scores}{scores of the perfect level}
#' }
#'
#' @docType data
#' @keywords datasets
#' @name B500
#' @usage data(B500)
NULL

#' Balanced data with 1000 positives and 1000 negatives.
#'
#' A list contains labels and scores of five different performance levels.
#' All scores were randomly generated.
#'
#' @format A list with 8 items.
#' \describe{
#'   \item{np}{number of positives: 1000}
#'   \item{nn}{number of negatives: 1000}
#'   \item{labels}{labels of observed data}
#'   \item{random_scores}{scores of a random performance level}
#'   \item{poor_er_scores}{scores of a poor early retrieval level}
#'   \item{good_er_scores}{scores of a good early retrieval level}
#'   \item{excel_scores}{scores of an excellent level}
#'   \item{perf_scores}{scores of the perfect level}
#' }
#'
#' @docType data
#' @keywords datasets
#' @name B1000
#' @usage data(B1000)
NULL

#' Imbalanced data with 500 positives and 5000 negatives.
#'
#' A list contains labels and scores of five different performance levels.
#' All scores were randomly generated.
#'
#' @format A list with 8 items.
#' \describe{
#'   \item{np}{number of positives: 500}
#'   \item{nn}{number of negatives: 5000}
#'   \item{labels}{labels of observed data}
#'   \item{random_scores}{scores of a random performance level}
#'   \item{poor_er_scores}{scores of a poor early retrieval level}
#'   \item{good_er_scores}{scores of a good early retrieval level}
#'   \item{excel_scores}{scores of an excellent level}
#'   \item{perf_scores}{scores of the perfect level}
#' }
#'
#' @docType data
#' @keywords datasets
#' @name IB500
#' @usage data(IB500)
NULL

#' Imbalanced data with 1000 positives and 10000 negatives.
#'
#' A list contains labels and scores of five different performance levels.
#' All scores were randomly generated.
#'
#' @format A list with 8 items.
#' \describe{
#'   \item{np}{number of positives: 1000}
#'   \item{nn}{number of negatives: 10000}
#'   \item{labels}{labels of observed data}
#'   \item{random_scores}{scores of a random performance level}
#'   \item{poor_er_scores}{scores of a poor early retrieval level}
#'   \item{good_er_scores}{scores of a good early retrieval level}
#'   \item{excel_scores}{scores of an excellent level}
#'   \item{perf_scores}{scores of the perfect level}
#' }
#'
#' @docType data
#' @keywords datasets
#' @name IB1000
#' @usage data(IB1000)
NULL

#' A small example dataset with several tied scores.
#'
#' A list contains labels and scores for 10 positives and 10 negatives.
#'
#' @format A list with 4 items.
#' \describe{
#'   \item{np}{number of positives: 10}
#'   \item{nn}{number of negatives: 10}
#'   \item{labels}{20 labels of observed data}
#'   \item{scores}{20 scores with some ties}
#' }
#'
#' @docType data
#' @keywords datasets
#' @name P10N10
#' @usage data(P10N10)
NULL

#' 5-fold cross validation sample.
#'
#' A data frame contains labels and scores for 5-fold test sets.
#'
#' @format A data frame with 4 columns.
#' \describe{
#'   \item{score1}{50 random scores}
#'   \item{score2}{50 random scores}
#'   \item{label}{50 labels as 'pos' or 'neg'}
#'   \item{fold}{50 fold IDs as 1:5}
#' }
#'
#' @docType data
#' @keywords datasets
#' @name M2N50F5
#' @usage data(M2N50F5)
NULL

#' Multiclass sample with three classes.
#'
#' A list contains labels and one score column per class for a 3-class
#'   dataset. The three classes are separated to different degrees, so that a
#'   one-vs-rest evaluation of them shows three clearly different curves.
#'
#' @format A list with 2 items.
#' \describe{
#'   \item{scores}{a 150 by 3 matrix of scores, one column per class,
#'                 with the column names 'c1', 'c2' and 'c3'}
#'   \item{labels}{150 labels as 'c1', 'c2' or 'c3', 50 of each}
#' }
#'
#' @docType data
#' @keywords datasets
#' @name C3N150
#' @usage data(C3N150)
NULL
