# Print model name and data size
.print_basic_curve_info <- function(x, indent_space = " ") {
  cat(indent_space, "Model name:",
      x[["evals"]][["cmats"]][["fmdat"]][["model_name"]], "\n")
  cat(indent_space, "\n")
  cat(indent_space, "Test data\n")
  cat(indent_space, "  # of positives:", x[["pos_num"]], "\n")
  cat(indent_space, "  # of negatives:", x[["neg_num"]], "\n")
  cat("\n")
}

#' Print ROC curve summary.
#'
#' \code{print} takes \code{roc_curve} object generated by
#' \code{\link{create_roc}} and print the summry of the ROC curve.
#'
#' @param x \code{roc_curve} object generated by
#'   \code{\link{create_roc}}.
#' @param ... Other arguments (ignored).
#'
#' @examples
#' data(B500)
#' roc_curve <- create_roc(scores = B500$good_er_scores,
#'                         obslabs = B500$labels)
#' print(roc_curve)
print.roc_curve <- function(x, ...) {
  # === Validate input arguments ===
  .validate(x)

  # === Print summary ===
  cat("\n  ROC curve\n\n")
  .print_basic_curve_info(x, "   ")
  cat("    AUC:", x[["auc"]], "\n\n")
}

#' Print Precision-Recall curve summary.
#'
#' \code{print} takes \code{prc_curve} object generated by
#' \code{\link{create_prc}} and print the summary of the Precision-Recall
#' curve.
#'
#' @param x \code{prc_curve} object generated by
#'   \code{\link{create_prc}}.
#' @param ... Other arguments (ignored).
#'
#' @examples
#' data(B500)
#' prc_curve <- create_prc(scores = B500$good_er_scores,
#'                         obslabs = B500$labels)
#' print(prc_curve)
print.prc_curve <- function(x, ...) {
  # === Validate input arguments ===
  .validate(x)

  # === Print summary ===
  cat("\n  Precision-Recall curve\n\n")
  .print_basic_curve_info(x, "   ")
  cat("    AUC:", x[["auc"]], "\n\n")
}

#' Print the summary of ROC and Precision-Recall curves.
#'
#' \code{print} takes \code{curves} object generated by
#' \code{\link{create_curves}} and plot ROC and Precion-Recall curves.
#'
#' @param x \code{curves} object generated by
#'   \code{\link{create_curves}}.
#' @param ... Other arguments.
#'
#' @examples
#' data(B500)
#' curves <- create_curves(scores = B500$good_er_scores,
#'                         obslabs = B500$labels)
#' print(curves)
print.curves <- function(x, ...) {
  # === Validate input arguments ===
  .validate(x)

  # === Print summary ===
  cat("\n")
  .print_basic_curve_info(x[["roc"]])

  cat("  ROC curve\n")
  cat("    AUC:", x[["roc"]][["auc"]], "\n\n")

  cat("  Precision-Recall curve\n")
  cat("    AUC:", x[["prc"]][["auc"]], "\n\n")

}
