# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

calc_auc <- function(xs, ys) {
    .Call('precrec_calc_auc', PACKAGE = 'precrec', xs, ys)
}

calc_avg_curve <- function(curves, x_interval, ci_q) {
    .Call('precrec_calc_avg_curve', PACKAGE = 'precrec', curves, x_interval, ci_q)
}

calc_basic_measures <- function(np, nn, tps, fps, tns, fns) {
    .Call('precrec_calc_basic_measures', PACKAGE = 'precrec', np, nn, tps, fps, tns, fns)
}

create_confusion_matrices <- function(olabs, ranks, rank_idx) {
    .Call('precrec_create_confusion_matrices', PACKAGE = 'precrec', olabs, ranks, rank_idx)
}

create_prc_curve <- function(tps, fps, sn, pr, x_interval) {
    .Call('precrec_create_prc_curve', PACKAGE = 'precrec', tps, fps, sn, pr, x_interval)
}

create_roc_curve <- function(tps, fps, sp, sn, x_interval) {
    .Call('precrec_create_roc_curve', PACKAGE = 'precrec', tps, fps, sp, sn, x_interval)
}

